### ISSUE TITLE
Token name on password entry window

### ISSUE THREAD

**Issue by donskov** [PeculiarVentures/fortify#107]
On the password input screen it is not clear for which token the password is being entered:

![image](https://user-images.githubusercontent.com/9417251/35386527-00637b38-01d5-11e8-8d10-d4781016fb92.png)

**Comment by microshine** [comment]
Fortify v.1.0.13
![image](https://user-images.githubusercontent.com/7333669/35387697-d6df301a-01e1-11e8-8daa-3ef450c98bc3.png)

**Comment by donskov** [comment]
@microshine Thanks
