### ISSUE TITLE
Add support for '3bd595ff8091fe1fc38073c8211385' token

### ISSUE THREAD

**Issue by charlienux** [PeculiarVentures/fortify#113]
Reader name: AseIIIeUSB 00 00
ATR: 3BD595FF8091FE1FC38073C8211385

```js
{
   "cards": [{
   	"atr": "3BD595FF8091FE1FC38073C8211385",
   	"name": "Token name",
   	"driver": "286D743DCE078CFADC161BBA1D3AEADD419F20B0"
   }],
   "drivers": [{
   	"id": "286D743DCE078CFADC161BBA1D3AEADD419F20B0",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BD595FF8091FE1FC38073C8211385](https://smartcard-atr.appspot.com/parse?ATR=3BD595FF8091FE1FC38073C8211385)

**Comment by microshine** [comment]
@charlienux what PKCS11 library do you use for your reader (windows, osx, linux)?

**Comment by charlienux** [comment]
In Windows Fortify, find the card reader and display the smart card information.

In Windows the name of the reader driver appears as Athena ASEDrive IIIe USB.
C: Windows \ System32 \ ASEDriveProp.dll

In Windows, the name of the smart card driver appears as ASECard Minidriver
C: Windows \ System32 \ asemd.dll

In Linux (Ubuntu 18.04), Fortify detects that a smart card is inserted in the card reader,  however I can not see the information because Fortify indicates that it is not supported.

The driver that uses Linux is the following:
/usr/lib/x86-athena/libASEP11.so

I have not tested with any other operating system.

I found that if in linux I add the following lines in card.json, Fortify reads the smart card. I do not know if the change affects the operation in Windows.

```
{
   "cards": [{
        "atr": "3BD595FF8091FE1FC38073C8211385",
        "name": "Athena IDProtect - Cryptographic Java Card",
        "driver": "29a2bd60c4b841c686be68d2874c0c02"
   }],
   "drivers": [{
        "id": "29a2bd60c4b841c686be68d2874c0c02",
        "name": "Athena IDProtect",
        "file": {
             "linux": {
             "x86": "/usr/lib/x86-athena/libASEP11.so",
             "x64": "/usr/lib/x64-athena/libASEP11.so"
        },
             "osx": "/Library/Application Support/Athena/libASEP11.dylib",
             "windows": "%WINDIR/System32/asepkcs.dll"
   	}
   }]
}
```

**Comment by microshine** [comment]
@charlienux Thank you
I updated card.json to v1.0.18 and uploaded to server
Your Fortify will update your local file on next Fortify start

If you want to disable card.json update, you can add `"disableCardUpdate": false` option to your `~/.fortify/config.json`
