### ISSUE TITLE
Add support for '3bda11ff81b1fe551f0300318473800180009000e4' token

### ISSUE THREAD

**Issue by jcca** [PeculiarVentures/fortify#116]
Reader name: Free Software Initiative of Japan Gnuk (FSIJ-1.2.10-67103354) 00 00
ATR: 3BDA11FF81B1FE551F0300318473800180009000E4

```js
{
   "cards": [{
   	"atr": "3BDA11FF81B1FE551F0300318473800180009000E4",
   	"name": "Token name",
   	"driver": "F1130F40823D7C0D7B49ECF91A9A53B0289E7C48"
   }],
   "drivers": [{
   	"id": "F1130F40823D7C0D7B49ECF91A9A53B0289E7C48",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDA11FF81B1FE551F0300318473800180009000E4](https://smartcard-atr.appspot.com/parse?ATR=3BDA11FF81B1FE551F0300318473800180009000E4)

**Comment by microshine** [comment]
@jcca what PKCS#11 lib does this reader uses (win, linux, osx)?

**Comment by jcca** [comment]
I am sorry,  OpenSC.

**Comment by microshine** [comment]
@jcca Can you add this card to your `~/.fortify/cards.json` file and relaunch Fortify application?
```json
{
  "atr": "3BDA11FF81B1FE551F0300318473800180009000E4",
  "name": "Gnuk OpenPGP Token (PKI)",
  "driver": "993988460d8f49a2ac519a2935f11533"
}
```
> OpenSC must be installed

**Comment by jcca** [comment]
I've tried it and it works correctly. I can see my certificate at tools.fortifyapp.com

**Comment by microshine** [comment]
What OS do you use?

**Comment by jcca** [comment]
I am using ArchLinux with Gnome shell, I can't see tray icon but fortify works correctly.
