### ISSUE TITLE
Add web page with list of supported smart cards

### ISSUE THREAD

**Issue by microshine** [PeculiarVentures/fortify#117]
We can use [card.jws](https://github.com/PeculiarVentures/fortify/blob/gh-pages/packages/card.jws) file for list building

@rmhrisk what do you think about it?

**Comment by rmhrisk** [comment]
Sure

**Comment by rmhrisk** [comment]
![image](https://user-images.githubusercontent.com/1619279/55422751-36a43380-5531-11e9-8848-3c91eca33e32.png)

Done
