### ISSUE TITLE
Add support for '3bdf18008131fe7d006b150c0180011101434e53103180e9' token

### ISSUE THREAD

**Issue by LeonardoBorselli** [PeculiarVentures/fortify#118]
Reader name: ACS ACR38U-CCID
ATR: 3BDF18008131FE7D006B150C0180011101434E53103180E9

```js
{
   "cards": [{
   	"atr": "3BDF18008131FE7D006B150C0180011101434E53103180E9",
   	"name": "Actalis S.p.A. Card",
   	"driver": "EDA3D12BE4EBFB06246E57F0E67B1FDEA3139983"
   }],
   "drivers": [{
   	"id": "EDA3D12BE4EBFB06246E57F0E67B1FDEA3139983",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDF18008131FE7D006B150C0180011101434E53103180E9](https://smartcard-atr.appspot.com/parse?ATR=3BDF18008131FE7D006B150C0180011101434E53103180E9)

**Comment by rmhrisk** [comment]
Does this device have a PKCS11 library for it?

**Comment by rmhrisk** [comment]
We need more info to add support for this, your help is appreciated.

**Comment by microshine** [comment]
Duplicate issue https://github.com/PeculiarVentures/fortify/issues/136
