### ISSUE TITLE
Add support for '3b7d96000080318065b0830201f383009000' token

### ISSUE THREAD

**Issue by ssijak** [PeculiarVentures/fortify#120]
Reader name: Gemalto PC Twin Reader
ATR: 3B7D96000080318065B0830201F383009000

```js
{
   "cards": [{
   	"atr": "3B7D96000080318065B0830201F383009000",
   	"name": "Token name",
   	"driver": "D1FCD58D08D66F2C4F67D0F30E03497CCA8CDC97"
   }],
   "drivers": [{
   	"id": "D1FCD58D08D66F2C4F67D0F30E03497CCA8CDC97",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3B7D96000080318065B0830201F383009000](https://smartcard-atr.appspot.com/parse?ATR=3B7D96000080318065B0830201F383009000)

**Comment by rmhrisk** [comment]
@ssijak do you have any idea what token this is?

Do you know what PKCS#11 libraries you use to make it work? If so do you know where those libraries are installed by default?

**Comment by donskov** [comment]
Related with https://github.com/PeculiarVentures/fortify/issues/239
