### ISSUE TITLE
Add support for '3bdf18008131fe7d006b020c0182011101434e53103180fc' token

### ISSUE THREAD

**Issue by licarigianluca** [PeculiarVentures/fortify#130]
Reader name: ACS ACR38U-CCID 00 00
ATR: 3BDF18008131FE7D006B020C0182011101434E53103180FC

```js
{
	"cards": [{
		"atr": "3BDF18008131FE7D006B020C0182011101434E53103180FC",
		"name": "Italian healtcare card (TS) National Service Card (CNS) (HealthCare)",
		"driver": "993988460d8f49a2ac519a2935f11533"
	}]
}
```

[Smart card ATR parsing 3BDF18008131FE7D006B020C0182011101434E53103180FC](https://smartcard-atr.appspot.com/parse?ATR=3BDF18008131FE7D006B020C0182011101434E53103180FC)

**Comment by licarigianluca** [comment]
other info

PC/SC device scanner
V 1.4.27 (c) 2001-2011, Ludovic Rousseau <ludovic.rousseau@free.fr>
Compiled with PC/SC lite version: 1.8.17
Using reader plug'n play mechanism
Scanning present readers...
0: ACS ACR38U-CCID 00 00

Wed Feb  6 10:55:37 2019
Reader 0: ACS ACR38U-CCID 00 00
  Card state: Card inserted, Shared Mode,
  ATR: 3B DF 18 00 81 31 FE 7D 00 6B 02 0C 01 82 01 11 01 43 4E 53 10 31 80 FC

ATR: 3B DF 18 00 81 31 FE 7D 00 6B 02 0C 01 82 01 11 01 43 4E 53 10 31 80 FC
+ TS = 3B --> Direct Convention
+ T0 = DF, Y(1): 1101, K: 15 (historical bytes)
  TA(1) = 18 --> Fi=372, Di=12, 31 cycles/ETU
    129032 bits/s at 4 MHz, fMax for Fi = 5 MHz => 161290 bits/s
  TC(1) = 00 --> Extra guard time: 0
  TD(1) = 81 --> Y(i+1) = 1000, Protocol T = 1 
-----
  TD(2) = 31 --> Y(i+1) = 0011, Protocol T = 1 
-----
  TA(3) = FE --> IFSC: 254
  TB(3) = 7D --> Block Waiting Integer: 7 - Character Waiting Integer: 13
+ Historical bytes: 00 6B 02 0C 01 82 01 11 01 43 4E 53 10 31 80
  Category indicator byte: 00 (compact TLV data object)
    Tag: 6, len: B (pre-issuing data)
      Data: 02 0C 01 82 01 11 01 43 4E 53
    Mandatory status indicator (3 last bytes)
      LCS (life card cycle): 10 (Proprietary)
      SW: 3180 (Error not defined by ISO 7816)
+ TCK = FC (correct checksum)

Possibly identified card (using /usr/share/pcsc/smartcard_list.txt):
3B DF 18 00 81 31 FE 7D 00 6B 02 0C 01 82 01 11 01 43 4E 53 10 31 80 FC
        Italian healtcare card (TS) National Service Card (CNS) (HealthCare)

**Comment by rmhrisk** [comment]
Thank you for this bug.

Can you provide the path in which we might be able to find the PKCS#11 libraries for this card?

We need the following:

```
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
```

**Comment by licarigianluca** [comment]
I'm using Debian Linux and the module is in this path: '/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so'

**Comment by rmhrisk** [comment]
@microshine I have updated the JSON based on the provided detail in the bug above, please publish a new card.json when you have the time.

**Comment by licarigianluca** [comment]
Thanks. Can you paste the modified part of the card.json so I try on my machine meanwhile microshine publishing your patch?

Thank you again

**Comment by rmhrisk** [comment]
It is possible to do that, I forget where in the install it is located but you can just add that definition and it should work.

@microshine can clarify on location when he is free.

**Comment by licarigianluca** [comment]
can you paste the definition please?

**Comment by licarigianluca** [comment]
I added this code to the card.json file and now the message "card unsupported" vanished. But when I try to use this card after I enter the pin something strange happened.

![image](https://user-images.githubusercontent.com/5665411/52353703-5cc8be00-2a2f-11e9-8998-389acfe3f617.png)

the browser hangs this are the logs

{"message":"Application started at Wed Feb 06 2019 16:47:17 GMT+0100 (CET)","level":"info"}
{"message":"OS linux x64 ","level":"info"}
{"message":"Fortify v1.0.17","level":"info"}
{"message":"System locale is 'en-US'","level":"info"}
{"message":"Locale: Set language to 'en'","level":"info"}
{"message":"Update: Check for new update","level":"info"}
{"message":"Update: New version wasn't found","level":"info"}
{"message":"SSL certificate is loaded","level":"info"}
{"message":"Comparing current version of card.json file with remote","level":"info"}
{"message":"card.json has the latest version","level":"info"}
{"message":"PCSCWatcher: New reader detected ACS ACR38U-CCID 00 00","level":"info"}
{"message":"PCSCWatcher:Insert reader:'ACS ACR38U-CCID 00 00' ATR:3bdf18008131fe7d006b020c0182011101434e53103180fc","level":"info"}
{"message":"Server: Started at 127.0.0.1:31337","level":"info"}
{"message":"WebCryptoLocalError: Provider:Open Cannot find pvpkcs11 by path /opt/fortify/resources/app.asar/pvpkcs11.so\n    at new WebCryptoLocalError (/opt/fortify/resources/app.asar/node_modules/webcrypto-local/dist/webcrypto-local.js:83:23)\n    at LocalProvider.open (/opt/fortify/resources/app.asar/node_modules/webcrypto-local/dist/webcrypto-local.js:2503:36)\n    at ProviderService.open (/opt/fortify/resources/app.asar/node_modules/webcrypto-local/dist/webcrypto-local.js:3702:21)\n    at Server.server.on (/opt/fortify/resources/app.asar/node_modules/webcrypto-local/dist/webcrypto-local.js:3801:27)\n    at emitOne (events.js:115:13)\n    at Server.emit (events.js:210:7)\n    at Server.emit (/opt/fortify/resources/app.asar/node_modules/webcrypto-local/dist/webcrypto-local.js:637:22)\n    at /opt/fortify/resources/app.asar/node_modules/webcrypto-local/dist/webcrypto-local.js:671:22\n    at <anonymous>","level":"error"}
{"message":"Provider: Add crypto 'NSS Certificate DB' 8bbae6f98340d7a92006c21da65c1acd345ba946","level":"info"}
{"message":"Provider:AddCrypto PKCS#11 '/usr/lib/x86_64-linux-gnu/nss/libsoftokn3.so' '/usr/lib/x86_64-linux-gnu/nss/libsoftokn3.so'","level":"info"}
{"message":"Provider:Opened","level":"info"}
{"message":"PCSCWatcher: New reader detected ACS ACR38U-CCID 00 00","level":"info"}
{"message":"PCSCWatcher:Insert reader:'ACS ACR38U-CCID 00 00' ATR:3bdf18008131fe7d006b020c0182011101434e53103180fc","level":"info"}
{"message":"Provider:Token:Insert reader:'ACS ACR38U-CCID 00 00' name:'Italian healtcare card' atr:3bdf18008131fe7d006b020c0182011101434e53103180fc","level":"info"}
{"message":"Provider:Token:Insert Looking for ACS ACR38U-CCID 00 00 into 1 slot(s)","level":"info"}
{"message":"Provider: Add crypto 'GIANLUCA LICARI (PIN CNS0)' 53636e676f13c8b9288597ab090fa12e2a3e5fb6493a71f83934ac5da30a1563","level":"info"}
{"message":"Provider:AddCrypto PKCS#11 '/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so' 'Italian healtcare card'","level":"info"}
{"message":"Provider:Token Amount of tokens was changed (+1/-0)","level":"info"}
{"message":"Server: New session connect 127.0.0.1","level":"info"}
{"message":"Server: Push session to stack","level":"info"}
{"message":"Cannot parse MessageSignedProtocol","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 server/isLoggedIn","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 provider/action/info","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 provider/action/getCrypto","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 crypto/isLoggedIn","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 provider/action/getCrypto","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 crypto/isLoggedIn","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 provider/action/getCrypto","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 crypto/isLoggedIn","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 crypto/keyStorage/keys","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 crypto/certificateStorage/keys","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 crypto/certificateStorage/getItem","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 crypto/certificateStorage/export","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 provider/action/getCrypto","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 crypto/isLoggedIn","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 crypto/login","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 provider/action/getCrypto","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 crypto/isLoggedIn","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 crypto/keyStorage/keys","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 crypto/certificateStorage/keys","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 crypto/certificateStorage/getItem","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 crypto/certificateStorage/export","level":"info"}
{"message":"Server: New session connect 127.0.0.1","level":"info"}
{"message":"Server: Push session to stack","level":"info"}
{"message":"Cannot parse MessageSignedProtocol","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 server/isLoggedIn","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 provider/action/info","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 provider/action/getCrypto","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 crypto/isLoggedIn","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 provider/action/getCrypto","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 crypto/isLoggedIn","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 provider/action/getCrypto","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 crypto/isLoggedIn","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 crypto/keyStorage/keys","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 crypto/certificateStorage/keys","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 crypto/certificateStorage/getItem","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 crypto/certificateStorage/export","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 provider/action/getCrypto","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 crypto/isLoggedIn","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 crypto/keyStorage/keys","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 crypto/certificateStorage/keys","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 crypto/certificateStorage/getItem","level":"info"}
{"message":"Server: session:00e7c0c41c1d11133cd26ff109d82ea216aebe9e7f384e7b6c9175d0c7eebd09 crypto/certificateStorage/export","level":"info"}

**Comment by rmhrisk** [comment]
For the purpose of your test update the linux path for the driver "993988460d8f49a2ac519a2935f11533" to point at "/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so"

**Comment by licarigianluca** [comment]
I have done before I wrote back

**Comment by rmhrisk** [comment]
Does this smart card have certificates on it? If so how have you verified that?

**Comment by microshine** [comment]
@licarigianluca try https://peculiarventures.github.io/fortify-examples/example4.html this page
it must show all certificates and keys for you token

**Comment by microshine** [comment]
@licarigianluca I sent updated `card.json` to your email from github account. Can you try it and confirm that it works for you?

I checked Fortify code, looks like it doesn't support multi paths for `card.json` file. We need to fix it in the next release
https://github.com/PeculiarVentures/webcrypto-local/issues/217

**Comment by licarigianluca** [comment]
This is what i got in that page

![image](https://user-images.githubusercontent.com/5665411/52399709-4bc68e00-2abd-11e9-924b-77e2cffb2f69.png)

**Comment by rmhrisk** [comment]
It seems we are able to see the certificate on your card with the test page, with that same configuration do you see the certificate when you visit https://tools.fortifyapp.com/ and select that smart card?

**Comment by licarigianluca** [comment]
No the page hangs and cpu go to 100%(one core of course)

**Comment by rmhrisk** [comment]
Hmmm.... I think were going to need to find a local reproduction to figure this one out. @microshine  Any ideas?

**Comment by microshine** [comment]
@licarigianluca Is your fortify.log the same which you sent before?

**Comment by licarigianluca** [comment]
this
[fortify.log](https://github.com/PeculiarVentures/fortify/files/2839981/fortify.log)

**Comment by microshine** [comment]
Looks like Fortify app returns 1 certificate to *tools.fortifyapp.com*
Maybe this is Web page error

It can be error on certificate showing
- Can you check your browser console log?
- Can you share your certificate?

**Comment by licarigianluca** [comment]
- yes I can
- Yes but I don't know how to export

**Comment by microshine** [comment]
You can export by using https://peculiarventures.github.io/fortify-examples/example4.html from console

![image](https://user-images.githubusercontent.com/7333669/52401832-ba164b00-2ad3-11e9-999c-9a18c50a60d0.png)

```js
// Get crypto
var macCrypto = await ws.getCrypto("01506f36c6ffe4062ed8d12e3acea5ef568cfcca")
// Get cert
var cert = await macCrypto.certStorage.getItem("x509-00c9cd0100600000-6a48d923a1982058202a2e516106cb35d9ca1936", {name:"RSASSA-PKCS1-v1_5", hash: "SHa-256"}, ["verify"])
// Export cert
await macCrypto.certStorage.exportCert("pem", cert);
```

**Comment by licarigianluca** [comment]
"-----BEGIN CERTIFICATE-----
MIIFqzCCBJOgAwIBAgIDOW7OMA0GCSqGSIb3DQEBBQUAMHMxCzAJBgNVBAYTAklU
MRcwFQYDVQQKEw5BY3RhbGlzIFMucC5BLjEiMCAGA1UECxMZU2Vydml6aSBkaSBD
ZXJ0aWZpY2F6aW9uZTEnMCUGA1UEAxMeUmVnaW9uZSBUb3NjYW5hIC0gQ0EgQ2l0
dGFkaW5pMB4XDTE2MDcyOTE1MDYxMVoXDTIyMDcyOTE1MDU0OVowga0xCzAJBgNV
BAYTAklUMRcwFQYDVQQKEw5BY3RhbGlzIFMucC5BLjEYMBYGA1UECxMPUkVHSU9O
RSBUT1NDQU5BMUcwRQYDVQQDEz5MQ1JHTEM4MlAyOUU5NzRLLzYwOTAwMTA5NTQ5
ODcwMDEuSEZEMkwzQ3JWVGoyYkFQcFlJWU5HS1J5Zm1VPTERMA8GA1UEKhMIR0lB
TkxVQ0ExDzANBgNVBAQTBkxJQ0FSSTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkC
gYEAw1TpGScf5Npcapiz+IvfTMJfamm69pKova8rNTT+eYSbL3WKZOwZhoRCBGUS
1CkHDRghtnkPl/7EBvzPKmryOC9Lso/XYK8uIjmtZ/gou5zOkbdpCdR9waOrReRH
8vEU3r0hQttjikA+7qvTgUnBvNah//AMZxSBu0TX6uUIAVsCAwEAAaOCAo8wggKL
MA4GA1UdDwEB/wQEAwIHgDCB+QYDVR0gBIHxMIHuMIGsBgUrTBACATCBojCBnwYI
KwYBBQUHAgIwgZIagY9JZGVudGlmaWVzIFguNTA5IGF1dGhlbnRpY2F0aW9uIGNl
cnRpZmljYXRlcyBpc3N1ZWQgZm9yIHRoZSBpdGFsaWFuIE5hdGlvbmFsIFNlcnZp
Y2UgQ2FyZCAoQ05TKSBwcm9qZWN0IGluIGFjY29yZGluZyB0byB0aGUgaXRhbGlh
biByZWd1bGF0aW9uLjA9BgYrgR8GBQEwMzAxBggrBgEFBQcCARYlaHR0cHM6Ly9w
b3J0YWwuYWN0YWxpcy5pdC9JbmZvL3BvbGljeTAdBgNVHQ4EFgQUb/bRU+jbI9gI
VJqA+LhHPtSfg8MwgeYGA1UdHwSB3jCB2zBJoEegRYZDaHR0cDovL2NybDAyLmFj
dGFsaXMuaXQvUmVwb3NpdG9yeS9DTlNfUlRPL1AvUi9nZXRMYXN0Q1JMP25hbWU9
Q1JMMjCBjaCBiqCBh4aBhGxkYXA6Ly9sZGFwMDIuYWN0YWxpcy5pdC9jbiUzZENS
TDIsb3UlM2RSZWdpb25lJTIwVG9zY2FuYSUyMC0lMjBDQSUyMENpdHRhZGluaSxv
JTNkQWN0YWxpcyUyMFMucC5BLixjJTNkSVQ/Y2VydGlmaWNhdGVSZXZvY2F0aW9u
TGlzdDA/BggrBgEFBQcBAQQzMDEwLwYIKwYBBQUHMAGGI2h0dHA6Ly9vY3NwMDIu
YWN0YWxpcy5pdC9WQS9DTlNfUlRPMBMGA1UdJQQMMAoGCCsGAQUFBwMCMB8GA1Ud
IwQYMBaAFNm30dCQrrvDV5aR0W8H7Tcl/wANMA0GCSqGSIb3DQEBBQUAA4IBAQAW
qRTLOuSNBkyR1iynFOeC4n6J5odnNdBfmv4xjUG7y1bkdzt5tU0rd8TM3PZzn9rS
Bv7MLlyZr5QV+AwpaSXFtjKEH/gXPOv+s2P92vNHsd/lBOZnhdxSS9STWAG8PYhw
Lywx50xpvS2+GaCJZc5D4XIj67HbfepW383kF5rP0DvauAEBFlYk4cwcOVAEZV3u
LCGDD7L04RAnaY03iR9DbUdoYJElX8TGeFDXTyB60WhKMtm77zomF6z1i6GX9zTM
LG3D1RV7gaAwyJdBh+tSoNs2fFlMuqeOfhEBtvWiT8D7K1imECcVjuLqL+mvT5QL
0wy5/18pvFDV56AjYU3v
-----END CERTIFICATE-----

**Comment by microshine** [comment]
Thank you! I need some time for tests

**Comment by licarigianluca** [comment]
can we delete the comment in which i wrote the certificate?

**Comment by microshine** [comment]
@licarigianluca Can you try updated version of https://tools.fortifyapp.com

Thanks to @donskov for finding and fixing UI error

**Comment by licarigianluca** [comment]
I have to start fortify on my pc?

**Comment by microshine** [comment]
yes
And open link I shared. It must show your certificate in list

**Comment by licarigianluca** [comment]
ok Works!

**Comment by microshine** [comment]
I'll add `3BDF18008131FE7D006B020C0182011101434E53103180FC` later. I need to update webcrypto-local implementation and publish new Fortify version to support multi paths for `card.json`

**Comment by microshine** [comment]
You can use https://github.com/PeculiarVentures/fortify-examples for starting and [webcrypto-socket.d.ts](https://github.com/PeculiarVentures/webcrypto-local/blob/master/webcrypto-socket.d.ts) file

**Comment by licarigianluca** [comment]
Can You advice me  when the new version will be available please?

thanks

**Comment by microshine** [comment]
About 4-5 days

**Comment by licarigianluca** [comment]
It's possible to sign PDFs with fortify?

**Comment by rmhrisk** [comment]
It is.

Check out https://hancock.ink it’s integrated Fortify.

**Comment by licarigianluca** [comment]
Sorry but I don't understand. Hancock does sign PDFs because is made upon Fortify?

**Comment by rmhrisk** [comment]
Hancock can sign PDFs and can do so with smart cards because it used Fortify.

**Comment by licarigianluca** [comment]
Is the release ready (with the changes needed for this card to work) ?

**Comment by microshine** [comment]
@licarigianluca I updated `node-webcrypto-p11` library, which is used by Fortify. It took a bit more time. I'm updating Fortify now.

**Comment by microshine** [comment]
@licarigianluca Can you try this new version?

https://github.com/PeculiarVentures/fortify-web/releases/tag/v1.0.18

### card.json example
```json
{
  "id": "993988460d8f49a2ac519a2935f11533",
  "name": "OpenSC driver",
  "file": {
    "osx": "/Library/OpenSC/lib/pkcs11/opensc-pkcs11.so",
    "linux": [
      "/usr/lib/opensc-pkcs11.so",
      "/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so"
    ],
    "windows": "%WINDIR/System32/opensc-pkcs11.dll"
  }
},
```

**Comment by licarigianluca** [comment]
Hi,
   I'm trying to use fortify with another project CAdes.js but how i can use both starting with example file provided with fortify? Where is the correct way to import it for use?

thankyou

**Comment by rmhrisk** [comment]
This is really an issue for CAdES repository; Fortify just looks like a webcrypto implementation. I think your question is how do I use CAdES? If so please file a bug in that repository. We would love to hear about what you're trying to do also, it would help us give more targeted advice.

**Comment by rmhrisk** [comment]
@licarigianluca is this resolved for you?

**Comment by donskov** [comment]
Resolved
