### ISSUE TITLE
Add support for '3b7f96000080318065b0850300ef120ffe829000' token

### ISSUE THREAD

**Issue by OtakuDigitChoc** [PeculiarVentures/fortify#133]
Reader name: Gemalto USB Shell Token V2 (A4CD3948) 00 00
ATR: 3B7F96000080318065B0850300EF120FFE829000

```js
{
   "cards": [{
   	"atr": "3B7F96000080318065B0850300EF120FFE829000",
   	"name": "Token name",
   	"driver": "039071B208C810D7A44D2A90CB7EF8DF07E8762B"
   }],
   "drivers": [{
   	"id": "039071B208C810D7A44D2A90CB7EF8DF07E8762B",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3B7F96000080318065B0850300EF120FFE829000](https://smartcard-atr.appspot.com/parse?ATR=3B7F96000080318065B0850300EF120FFE829000)

**Comment by rmhrisk** [comment]
@OtakuDigitChoc thanks for this. The shell token is the USB reader, do you know what smart card is inside it?

Do you know what PKCS#11 middleware is used with that smart card? In particular we need to know where the PKCS#11 library is installed for this smart card.

**Comment by microshine** [comment]
Duplicate issue https://github.com/PeculiarVentures/fortify/issues/129
