### ISSUE TITLE
Add support for '3bdf18008131fe7d006b020c0182011101434e53103180fc' token

### ISSUE THREAD

**Issue by lmangiacotti** [PeculiarVentures/fortify#137]
Reader name: Alcor Micro AU9520 00 00
ATR: 3BDF18008131FE7D006B020C0182011101434E53103180FC

```js
{
   "cards": [{
   	"atr": "3BDF18008131FE7D006B020C0182011101434E53103180FC",
   	"name": "Token name",
   	"driver": "4028592F0BBBE2F9E32EC0EED18B8AF0C401770D"
   }],
   "drivers": [{
   	"id": "4028592F0BBBE2F9E32EC0EED18B8AF0C401770D",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDF18008131FE7D006B020C0182011101434E53103180FC](https://smartcard-atr.appspot.com/parse?ATR=3BDF18008131FE7D006B020C0182011101434E53103180FC)

**Comment by rmhrisk** [comment]
Can you share details about this card? For example where is the PLCS11 library for it? What is it’s form factor? Etc?

**Comment by microshine** [comment]
Duplicate issue https://github.com/PeculiarVentures/fortify/issues/130
