### ISSUE TITLE
Add support for '3bfd1800008131fe4553434536302d43433038312d46c2' token

### ISSUE THREAD

**Issue by gilluan** [PeculiarVentures/fortify#145]
Reader name: Giesecke & Devrient GmbH StarSign Crypto USB Token (01150822029690) 00 00
ATR: 3BFD1800008131FE4553434536302D43433038312D46C2

```js
{
   "cards": [{
   	"atr": "3BFD1800008131FE4553434536302D43433038312D46C2",
   	"name": "Giesecke & Devrient GmbH StarSign Crypto USB Token",
   	"driver": "049482F4DA6CA9ABCA1E4F09042A237614055CD5"
   }],
   "drivers": [{
   	"id": "049482F4DA6CA9ABCA1E4F09042A237614055CD5",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BFD1800008131FE4553434536302D43433038312D46C2](https://smartcard-atr.appspot.com/parse?ATR=3BFD1800008131FE4553434536302D43433038312D46C2)

**Comment by rmhrisk** [comment]
This appears to be a Giesecke & Devrient StarSign USB Token. What P11 do you use this with? Where is it located on your file system?

**Comment by rmhrisk** [comment]
It looks like the file is called “libaetjcss.dylib” on OSX.

Maybe located in: /Applications/tokenadmin.app/Contents/Frameworks

**Comment by rmhrisk** [comment]
I’m going to guess the Linux file is: ‘/usr/lib/libaetpkss.so’

And the Windows file is:
‘libaetpkss.dll’

**Comment by rmhrisk** [comment]
@gilluan can you confirm?

**Comment by microshine** [comment]
Duplicate issue https://github.com/PeculiarVentures/fortify/issues/145
