### ISSUE TITLE
Add support for '3b7e9400008025d20310010056000000020200' token

### ISSUE THREAD

**Issue by vtucan** [PeculiarVentures/fortify#147]
Reader name: HP USB Smart Card Keyboard 0
ATR: 3B7E9400008025D20310010056000000020200

```js
{
   "cards": [{
   	"atr": "3B7E9400008025D20310010056000000020200",
   	"name": "Official Czech Republic identity card issued since 7/2018 (eID)",
   	"driver": "445912C0D3A36598078024B49C87336F45B16EA9"
   }],
   "drivers": [{
   	"id": "445912C0D3A36598078024B49C87336F45B16EA9",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3B7E9400008025D20310010056000000020200](https://smartcard-atr.appspot.com/parse?ATR=3B7E9400008025D20310010056000000020200)

**Comment by microshine** [comment]
Can you try to update your local ~/.fortify/card.json file and check that token works?

Steps to update card.json

- Open file ~/.fortify/card.json
- Add your card to "cards" array
- Update "driver" field in card
- You can use existing id from "drivers", or add new driver to "drivers"
- Restart Fortify

**Comment by vtucan** [comment]
Yes, after modification, the token works but I have some troubles with the reader. So I have to configure the driver correctly.

**Comment by microshine** [comment]
Please share `card.json` changed data when you finish. I'll publish new version.

**Comment by vtucan** [comment]
Finally, I got it working.

my card.json file:
{
  "$schema": "./card.schema.json",
  "version": "1.0.21",
  "cards": [
    {
      "atr": "3b7e9400008025d20310010056000000020200",
      "name": "National Identity Document: Czech eID (since 7/2018)",
      "driver": "445912C0D3A36598078024B49C87336F45B16EA9"
    }
  ],
  "drivers": [
    {
      "id": "445912C0D3A36598078024B49C87336F45B16EA9",
      "name": "eOP Czech",
      "file": {
        "windows": "%WINDIR/System32/eop2v1czep11.dll"
      }
    }
  ]
}

eop2v1czep11.dll is the driver included in eID management software provided by Czech Identity Authority (https://info.eidentita.cz/eop/SpravceKarty.aspx)
I tried only Win10 x64 version.

**Comment by rmhrisk** [comment]
Thanks.

We will do an update based on that.

We can assume based on the file name that  the 32bit version has same name and that it’s directory is the non 64bit system32.

I did some searches and don’t find Linux or Mac drivers.

@microshine please do the update.

**Comment by microshine** [comment]
### MacOS
https://info.eidentita.cz/download/InstalacniPrirucka_eObcanka_MacOS.pdf

```
/usr/local/lib/eOPCZE/libeopczep11.dylib
/usr/local/lib/eOPCZE/libeop2v1czep11.dylib
```

### Linux
https://info.eidentita.cz/download/InstalacniPrirucka_eObcanka_Linux.pdf

```
/usr/lib/x86_64-linux-gnu/libeopczep11.so
/usr/lib/x86_64-linux-gnu/libeop2v1czep11.so
```

**Comment by rmhrisk** [comment]
Cool

Let’s do it

**Comment by microshine** [comment]
The only problem is how to determine that token was issued before 01.07.2018 or not. And what library we should to use

**Comment by microshine** [comment]
I've published new version of card.json v1.0.22
@vtucan Can you restart Fortify and check that your token works?

**Comment by vtucan** [comment]
Works like a charm. Thanks a lot.

IMHO don't bother with Czech eID before 07/2018. It was different card type and practically useless (not intended for online services) . Also you had to pay for the smart card version (standard was to issue the Id without chip).
