### ISSUE TITLE
Add support for '3b9f958131fe9f006646530501001171df000006000015' token

### ISSUE THREAD

**Issue by abrbhat** [PeculiarVentures/fortify#161]
Reader name: FT ePass2003Auto 0
ATR: 3B9F958131FE9F006646530501001171DF000006000015

```js
{
   "cards": [{
   	"atr": "3B9F958131FE9F006646530501001171DF000006000015",
   	"name": "ePass2003Auto",
   	"driver": "993988460d8f49a2ac519a2935f11533"
   }]
}
```

[Smart card ATR parsing 3B9F958131FE9F006646530501001171DF000006000015](https://smartcard-atr.appspot.com/parse?ATR=3B9F958131FE9F006646530501001171DF000006000015)

**Comment by rmhrisk** [comment]
This looks like a Feitian ePass2003. If so we should be able to point it at the drivers used for other Feitian ePass2003s

**Comment by abrbhat** [comment]
@rmhrisk Thanks. Any pointers on how to go about it?

**Comment by rmhrisk** [comment]
Open file ~/.fortify/card.json
Find ePass2003 copy the GUID for the driver
Add the card object from the JSON in this bug but use that GUID as the driver GUID 

Restart Fortify
In theory, if the above conditions are met the card should work.

**Comment by abrbhat** [comment]
@rmhrisk I tried doing what you suggested. I am getting the error:

```
Oh no, that did not work!
The inserted smart card is supported by Fortify but we were unable to find middleware for the card. Make sure (C:\Windows\System32\opensc-pkcs11.dll) exists, if not install the smart cards middleware and try again.
```

How to install opensc-pkcs11.dll?

**Comment by rmhrisk** [comment]
You can get OpenSC here: https://github.com/OpenSC/OpenSC/wiki/OpenSC-Windows-installer

But I am curious if you do not currently have the OpenSC middleware installed are you using this token for anything currently?

If so do you know if you are using it via a CSP/KSP, or a PKCS#11 library?

If so which one?

**Comment by rmhrisk** [comment]
@microshine We may want to add support for masks on matching to reduce the number of entries needed. Of course, the tricky part is figuring out what those masks should be :)

![image](https://user-images.githubusercontent.com/1619279/56948700-d4872000-6b28-11e9-90b1-c12b930d57af.png)

**Comment by microshine** [comment]
Duplicate issue https://github.com/PeculiarVentures/fortify/issues/146
