### ISSUE TITLE
Add support for '3bfd1800008131fe4553434536302d43433038312d46c2' token

### ISSUE THREAD

**Issue by gilluan** [PeculiarVentures/fortify#164]
Reader name: Giesecke & Devrient GmbH StarSign CUT 0
ATR: 3BFD1800008131FE4553434536302D43433038312D46C2

```js
{
   "cards": [{
   	"atr": "3BFD1800008131FE4553434536302D43433038312D46C2",
   	"name": "Giesecke & Devrient StarSign USB Token,
   	"driver": "3BF3149E2431685373AF46CE8F37AEFB73E0355D"
   }],
   "drivers": [{
   	"id": "3BF3149E2431685373AF46CE8F37AEFB73E0355D",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BFD1800008131FE4553434536302D43433038312D46C2](https://smartcard-atr.appspot.com/parse?ATR=3BFD1800008131FE4553434536302D43433038312D46C2)

**Comment by rmhrisk** [comment]
Can your you share some details about this token?

What form factor is it? Is it a card or token?

What model is it?

What PKCS11 library do you use with it?

What is the path to that PKCS11 library?

**Comment by donskov** [comment]
Related with https://github.com/PeculiarVentures/fortify/issues/134
