### ISSUE TITLE
Add support for '3bdc18ff8091fe1fc38073c8211366010b0352000539' token

### ISSUE THREAD

**Issue by MFTopografiacr** [PeculiarVentures/fortify#183]
Reader name: miniLector Pocket V2 0
ATR: 3BDC18FF8091FE1FC38073C8211366010B0352000539

```js
{
   "cards": [{
   	"atr": "3BDC18FF8091FE1FC38073C8211366010B0352000539",
   	"name": "Token name",
   	"driver": "51FE79BF3B4F1BF5D681E109A449419B73EB9E63"
   }],
   "drivers": [{
   	"id": "51FE79BF3B4F1BF5D681E109A449419B73EB9E63",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDC18FF8091FE1FC38073C8211366010B0352000539](https://smartcard-atr.appspot.com/parse?ATR=3BDC18FF8091FE1FC38073C8211366010B0352000539)

**Comment by rmhrisk** [comment]
This looks like it is “Digital Signature Costa Rica (eID)” do you have the path to the PKCS11 library for this token?

**Comment by rmhrisk** [comment]
Closing as a dupe if: https://github.com/PeculiarVentures/fortify/issues/173

Please help with the additional information.
