### ISSUE TITLE
Add support for '3bdc18ff8091fe1fc38073c8211366010b0352000539' token

### ISSUE THREAD

**Issue by EnriqueInge** [PeculiarVentures/fortify#228]
Reader name: OMNIKEY CardMan 3x21 0
ATR: 3BDC18FF8091FE1FC38073C8211366010B0352000539

```js
{
   "cards": [{
   	"atr": "3BDC18FF8091FE1FC38073C8211366010B0352000539",
   	"name": "Token name",
   	"driver": "E5D61F630A5834B68733C5565D6F8A582D668ED1"
   }],
   "drivers": [{
   	"id": "E5D61F630A5834B68733C5565D6F8A582D668ED1",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDC18FF8091FE1FC38073C8211366010B0352000539](https://smartcard-atr.appspot.com/parse?ATR=3BDC18FF8091FE1FC38073C8211366010B0352000539)

**Comment by rmhrisk** [comment]
We have just released a new update that should add support for this card.

**Comment by rmhrisk** [comment]
#173
