### ISSUE TITLE
Add support for '3b7d96000080318065b0830201f383009000' token

### ISSUE THREAD

**Issue by dpccrt87** [PeculiarVentures/fortify#239]
Reader name: Gemalto USB Key Smart Card Reader 0
ATR: 3B7D96000080318065B0830201F383009000

```js
{
   "cards": [{
   	"atr": "3B7D96000080318065B0830201F383009000",
   	"name": "Token name",
   	"driver": "D5C8E6D01475954359EF7DBA3B41D26E0DD90695"
   }],
   "drivers": [{
   	"id": "D5C8E6D01475954359EF7DBA3B41D26E0DD90695",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3B7D96000080318065B0830201F383009000](https://smartcard-atr.appspot.com/parse?ATR=3B7D96000080318065B0830201F383009000)

**Comment by microshine** [comment]
Please try to add your smart card via `~/.fortify/config.json`editing.

Add this option to your config.json file
```json
{
  "cards": [
    {
      "atr": "3B7D96000080318065B0830201F383009000",
      "libraries": [
        "/Library/OpenSC/lib/pkcs11/opensc-pkcs11.so"
      ],
      "name": "OpenSC",
    }
  ]
}
```

Please change `libraries` path to your PKCS#11 library path.
You need to restart Fortify to apply new config.

**Comment by dpccrt87** [comment]
Hi microshine,
Thank you for reply.
I want to know what are the steps to follow to implement fortify with my JS code [?](https://stackoverflow.com/questions/57394585/how-to-get-x-509-certificate-from-hardware-in-javascript) So that I can, in the end, generate my certificate from my code js

**Comment by rmhrisk** [comment]
There is information on the FortifyApp.com page, in particular a link to the documentation: https://peculiarventures.github.io/webcrypto-local/docs/

There are also examples here: https://github.com/PeculiarVentures/fortify-examples

**Comment by microshine** [comment]
Also, you can install `@webcrypto-local/client` npm module. It includes `build/webcrypto-local.d.ts` file with TypeScript definitions

**Comment by dpccrt87** [comment]
Hi, 
I saw the examples, and now i want to know, how can i sign pdf file using the generated certificate from fortify in JS ?

**Comment by rmhrisk** [comment]
Looks like your not including the protobuf package?

Have you seen Hancock.ink? It uses Fortify to do smart card based signing.

**Comment by dpccrt87** [comment]
Hi rmhrisk,
How can i include it ? 
And i have another question relating to **Fortify** is possible to install it on remote server ?
Yes, i see Hancock just now, can i have more explanations about its use ?

**Comment by rmhrisk** [comment]
You can see how to do includes for Fortify here:
https://github.com/PeculiarVentures/fortify-examples/blob/gh-pages/example1.html#L14-L23

Fortify is a client application, it enables a browser to use local certificates and smart cards. I am not sure what the server scenario would be?

Hancock is an application designed to help you sign PDFs in a browser, you can use it to view PDFs (see https://verify.ink), and to sign them (see https://hancock.ink).

**Comment by dpccrt87** [comment]
Hi rmhrisk,
My current need is to generate X509 certificate found in my USB Token, using my JS code. After that i will use it to sign pdf document using JS library.

**Comment by rmhrisk** [comment]
That is possible, we use fortify and PKIjs for the X509 and token interaction.

We created our own PDF library which is not public to allow for reliable PDF signing for all kinds of PDFs.

We have a sample of basic PDF signing in PKIJs that will work on simple documents.

**Comment by YuryStrozhevsky** [comment]
@rmhrisk In fact in Pkijs example we have pdf verification only.

**Comment by dpccrt87** [comment]
@rmhrisk, so how can i proceed to generate X509 Certificate from my USB token using JS code only?
and how can i sign Pdf file using the generated X509 Certificate ?

**Comment by rmhrisk** [comment]
I see; mistake on my part re:signing.

Re: how to create cert using fortify see the samples: https://peculiarventures.github.io/fortify-examples/example3.html

**Comment by dpccrt87** [comment]
Hi @rmhrisk,
Can you give me some examples (documentation) or tracks, so that I can sign my pdf file using the hancock tool with fortify ?

**Comment by rmhrisk** [comment]
Email me at ryan@peculiarventures.com and I’ll explain.

**Comment by dpccrt87** [comment]
its done.

**Comment by dpccrt87** [comment]
Hi @rmhrisk,
Is there any news ?

**Comment by dpccrt87** [comment]
I'm still stuck, thank you for helping me solve my issue.

**Comment by donskov** [comment]
@microshine Can we add changes to card.json?

**Comment by microshine** [comment]
That ATR is in `card.json`
