### ISSUE TITLE
Add support for '3b7d18000000487970734944205333079000' token

### ISSUE THREAD

**Issue by JoaHou** [PeculiarVentures/fortify#248]
Reader name: ActivIdentity Activkey_Sim [CCID Bulk Interface] 00 00
ATR: 3B7D18000000487970734944205333079000

```js
{
   "cards": [{
   	"atr": "3B7D18000000487970734944205333079000",
   	"name": "Token name",
   	"driver": "9B08C70825B5E5F5234E4319B876EA77C44E61F4"
   }],
   "drivers": [{
   	"id": "9B08C70825B5E5F5234E4319B876EA77C44E61F4",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3B7D18000000487970734944205333079000](https://smartcard-atr.appspot.com/parse?ATR=3B7D18000000487970734944205333079000)

**Comment by rmhrisk** [comment]
This appears to be a “ Schlumberger Multiflex 3k” can you provide anymore information about the card?

Does it have a PKCS11 library? If so what is the library name and where does it commonly get installed?

Does it support certificates? If so are you able to access those certificates via another application? If so which one?

**Comment by JoaHou** [comment]
Hi,
It's ActivKey SIM and my OS is Ubuntu 18.04
![activid-usb-token_1_1](https://user-images.githubusercontent.com/56514918/66732801-945cf500-ee5d-11e9-8626-90d0c8401302.png)
I installed opensc 0.19.0 and pcsc
In firefox I add security device pkcs11 with "opensc‑pkcs11-onepin.so" and I try too with "libaetpkss.so " but nothing.
The key green light while 5s and return to red light.

The key work very well into Windows 10 with "Morpho Middleware ypsID".

**Comment by rmhrisk** [comment]
Do you have the path to the Morpho Middleware on your system? It is possible there is a PKCS11 library with that package, alternatively it may be a mini driver and no path will be necessary if use is limited to Windows.

**Comment by JoaHou** [comment]
On Windows 10, in Firefox, it's c:\windows\system32\CnfPkcs11v220.dll
![capture](https://user-images.githubusercontent.com/56514918/66737514-7d71cf00-ee6c-11e9-9a9b-e5f8a868245c.jpg)

**Comment by rmhrisk** [comment]
With this it should be possible to test this by editing card.json

**Comment by JoaHou** [comment]
card.json into Ubuntu 18.04 (~/.fortify/card.json)

 {
  "$schema": "./card.schema.json",
  "version": "1.0.23",
  "cards": [
    {
      "atr": "3b9813400aa503010101ad1311",
      "name": "National Identity Document: Belgian eID",
      "driver": "89648ea52ed24a799aff9f9ff363eef4"
    },
    {
      "atr": "3B7F960000006A444E4965200101550410039000",
      "name": "National Identity Document: Spanish eID ",
      "readOnly": true,
      "driver": "993988460d8f49a2ac519a2935f11533"
    },
    {
      "atr": "3B7D94000080318065B0831100C883009000",
      "name": "National Identity Document: Republic of Lithuania eID",
      "readOnly": true,
      "driver": "71789068c5ff4891aeeaf7fb9608a22f"
    },
    {
      "atr": "3BDF18008131FE580031B964050E010073B401D300000022",
      "name": "National Identity Document: Slovak eID",
      "readOnly": true,
      "driver": "39798896FC5DD6E2A96989718F694334275E0EAC"
    },
    {
      "atr": "3BF81300008131FE454A434F5076323431B7",
      "name": "National Identity Document: Nigerian eID",
      "readOnly": true,
      "driver": "c4e60449442848c48af7b3fcf6a6f4a1"
    },
    {
      "atr": "3BF9180000C00A31FE4553462D3443432D303181",
      "name": "National Identity Document: Estonian eID",
      "readOnly": true,
      "driver": "c4e60449442848c48af7b3fcf6a6f4a1"
    },
    {
      "atr": "3BF81300008131FE454A434F5076323431B7",
      "name": "National Identity Document: Nigerian eID",
      "readOnly": true,
      "driver": "c4e60449442848c48af7b3fcf6a6f4a1"
    },
    {
      "atr": "3BFE9400FF80B1FA451F0345737445494420",
      "name": "National Identity Document: Broken Estonian eID 1.1 warm",
      "readOnly": true,
      "driver": "c4e60449442848c48af7b3fcf6a6f4a1"
    },
    {
      "atr": "3BFE9400FF80B1FA451F034573744549442076657220312E3043",
      "name": "National Identity Document: Estonian eID 1.0 cold",
      "readOnly": true,
      "driver": "c4e60449442848c48af7b3fcf6a6f4a1"
    },
    {
      "atr": "3B6E00FF4573744549442076657220312E30",
      "name": "National Identity Document: Estonian eID 1.0 cold",
      "readOnly": true,
      "driver": "c4e60449442848c48af7b3fcf6a6f4a1"
    },
    {
      "atr": "3BDE18FFC080B1FE451F034573744549442076657220312E302B",
      "name": "National Identity Document: Estonian eID 1.0 cold 2006",
      "readOnly": true,
      "driver": "c4e60449442848c48af7b3fcf6a6f4a1"
    },
    {
      "atr": "3B5E11FF4573744549442076657220312E30",
      "name": "National Identity Document: Estonian eID 1.0 warm 2006",
      "readOnly": true,
      "driver": "c4e60449442848c48af7b3fcf6a6f4a1"
    },
    {
      "atr": "3b6e00004573744549442076657220312e30",
      "name": "National Identity Document: Estonian eID 1.1 cold",
      "readOnly": true,
      "driver": "c4e60449442848c48af7b3fcf6a6f4a1"
    },
    {
      "atr": "3BFE1800008031FE454573744549442076657220312E30A8",
      "name": "National Identity Document: Estonian eID 3.0 (dev1) cold",
      "readOnly": true,
      "driver": "c4e60449442848c48af7b3fcf6a6f4a1"
    },
    {
      "atr": "3BFE1800008031FE45803180664090A4561B168301900086",
      "name": "National Identity Document: Estonian eID 3.0 (dev1) warm",
      "readOnly": true,
      "driver": "c4e60449442848c48af7b3fcf6a6f4a1"
    },
    {
      "atr": "3BFE1800008031FE45803180664090A4162A0083019000E1",
      "name": "National Identity Document: Estonian eID 3.0 (dev2) warm",
      "readOnly": true,
      "driver": "c4e60449442848c48af7b3fcf6a6f4a1"
    },
    {
      "atr": "3BFE1800008031FE45803180664090A4162A00830F9000EF",
      "name": "National Identity Document: Estonian eID 3.0 (18.01.2011) warm",
      "readOnly": true,
      "driver": "c4e60449442848c48af7b3fcf6a6f4a1"
    },
    {
      "atr": "3BFA1800008031FE45FE654944202F20504B4903",
      "name": "National Identity Document: Estonian eID 3.5 cold",
      "readOnly": true,
      "driver": "c4e60449442848c48af7b3fcf6a6f4a1"
    },
    {
      "atr": "3BDF960081B1FE451F838073CC91CBF9A0000003080000100079",
      "name": "USG:Executive Office of the President",
      "readOnly": true,
      "driver": "993988460d8f49a2ac519a2935f11533"
    },
    {
      "atr": "3BDB9600801F030031C064B0F310000F900088",
      "name": "USG:Department of Veterans Affairs",
      "readOnly": true,
      "driver": "993988460d8f49a2ac519a2935f11533"
    },
    {
      "atr": "3BDF960081B1FE451F838073CC91CBF9A0000003080000100079",
      "name": "USG:State Department",
      "readOnly": true,
      "driver": "993988460d8f49a2ac519a2935f11533"
    },
    {
      "atr": "3BFE1800008131FE458031815448534D31738021408107FA",
      "name": "Nitrokey Nitrokey HSM",
      "driver": "993988460d8f49a2ac519a2935f11533"
    },
    {
      "atr": "3B7D18000000487970734944205333079000",
      "name": "Safran Morpho YpsID S3",
      "driver": "fea007cafe404e4fb56a8be39f60dc8f"
    },
    {
      "atr": "3B7A18000000487970734944205333",
      "name": "Safran Morpho YpsID S3 - French Customs",
      "driver": "fea007cafe404e4fb56a8be39f60dc8f"
    },
    {
      "atr": "3B941881B1807D1F0319C80050DC",
      "name": "GoldKey Security PIV Token",
      "driver": "993988460d8f49a2ac519a2935f00533"
    },
    {
      "atr": "3bff0000008131004380318065b000000000120ffe82900000",
      "name": "Gemalto IDPrime v2+ .NET",
      "driver": "39b3d7a3662c4b48bb120d008dd18648"
    },
    {
      "atr": "3B8980014A434F5032343252324A",
      "name": "NXP JCOP J3D",
      "driver": "993988460d8f49a2ac519a2935f11533"
    },
    {
      "atr": "3BD518008131FE7D8073C82110F4",
      "name": "SafeNet eToken 5100",
      "driver": "39b3d7a3662c4b48bb120d008dd18648"
    },
    {
      "atr": "3BD5180081313A7D8073C8211030",
      "name": "SafeNet eToken 5110",
      "driver": "39b3d7a3662c4b48bb120d008dd18648"
    },
    {
      "atr": "3bff1100008131fe4d8025a00000005657444b3333300600d0",
      "name": "Datakey 32K PKI Smart Card Model 330",
      "driver": "39b3d7a3662c4b48bb120d008dd18648"
    },
    {
      "atr": "3BFC1300008131FE15597562696B65794E454F7233E1",
      "name": "Yubico Yubikey NEO OTP+U2F+CCID",
      "readOnly": true,
      "driver": "993988460d8f49a2ac519a2935f00533"
    },
    {
      "atr": "3BFD1300008131FE158073C021C057597562694B657940",
      "name": "Yubico Yubikey 4 OTP+U2F+CCID",
      "readOnly": true,
      "driver": "993988460d8f49a2ac519a2935f00533"
    },
    {
      "atr": "3BF81300008131FE15597562696B657934D4",
      "name": "Yubico Yubikey 4 OTP+U2F+CCID",
      "readOnly": true,
      "driver": "993988460d8f49a2ac519a2935f00533"
    },
    {
      "atr": "3BF81800008031FE45FE415A452044495433",
      "name": "AzeDIT 3.5 cold",
      "readOnly": true,
      "driver": "c4e60449442848c48af7b3fcf6a6f4a1"
    },
    {
      "atr": "3b8b015275746f6b656e20445320c1",
      "name": "Rutoken ECP (DS)",
      "driver": "7d3a38d2d8294234a53d5845d6d116c4"
    },
    {
      "atr": "3b9f958131fe9f006646530501001171df000003900080",
      "name": "FT ePass2003Auto",
      "driver": "993988460d8f49a2ac519a2935f11533"
    },
    {
      "atr": "3BFC180000813180459067464A00642D70C172FEE0FE",
      "name": "PivKey T800",
      "readOnly": true,
      "driver": "993988460d8f49a2ac519a2935f11533"
    },
    {
      "atr": "3B9F958131FE9F006646530510001171DF000000000002",
      "name": "PivKey T600",
      "readOnly": true,
      "driver": "993988460d8f49a2ac519a2935f11533"
    },
    {
      "atr": "3bf99600008131fe45535049564b4559373028",
      "name": "PIVKey SLE78 (28)",
      "readOnly": true,
      "driver": "993988460d8f49a2ac519a2935f11533"
    },
    {
      "atr": "3BDA11FF81B1FE551F0300318473800180009000E4",
      "name": "Gnuk OpenPGP Token (PKI)",
      "driver": "993988460d8f49a2ac519a2935f11533"
    },
    {
      "atr": "3BF81800FF8131FE454A434F507632343143",
      "name": "AET Smartcard",
      "driver": "3bcf3e1d4952cfa3e486934887f45a0f"
    },
    {
      "atr": "3B7F96000080318065B084413DF6120FFE829000",
      "name": "Gemalto IDPrime MD",
      "driver": "0ca280b5af17d6aa91af084f2d39d2a3"
    },
    {
      "atr": "3B7F96000080318065B0850300EF120FFE829000",
      "name": "Gemalto IDPrime MD 840 (PKI)",
      "driver": "0ca280b5af17d6aa91af084f2d39d2a3"
    },
    {
      "atr": "3BD21802C10A31FE58C80D51",
      "name": "Siemens Card CardOS M4.4",
      "driver": "25fb0440047947539fd871831ac8477c",
      "readOnly": true
    },
    {
      "atr": "3BF21800FFC10A31FE55C8068A",
      "name": "Aladdin Knowledge Systems eToken Pro 64k (4.2)",
      "driver": "11A4BEA85E4C5D7EC6CDE452A70448A73EBE191B"
    },
    {
      "atr": "3BDC18FF8191FE1FC38073C8211366010B0352000538",
      "name": "Athena IDProtect Smart Card Logon Card",
      "driver": "29a2bd60c4b841c686be68d2874c0c02"
    },
    {
      "atr": "3BDC18FF8091FE1FC38073C8211366010B0352000539",
      "name": "Digital Signature Costa Rica (eID)",
      "driver": "29a2bd60c4b841c686be68d2874c0c02"
    },
    {
      "atr": "3BD595FF8091FE1FC38073C8211385",
      "name": "Athena IDProtect - Cryptographic Java Card",
      "driver": "29a2bd60c4b841c686be68d2874c0c02"
    },
    {
      "atr": "3BDF18008131FE7D006B020C0182011101434E53103180FC",
      "name": "Italian healtcare card (TS) National Service Card (CNS) (HealthCare)",
      "driver": "993988460d8f49a2ac519a2935f11533"
    },
    {
      "atr": "3B7D96000080318065B0A31101F383009000",
      "name": "Telia EID IP5a (eID)",
      "driver": "993988460d8f49a2ac519a2935f11533"
    },
    {
      "atr": "3b7e9400008025d20310010056000000020200",
      "name": "National Identity Document: Czech eID (since 7/2018)",
      "driver": "445912C0D3A36598078024B49C87336F45B16EA9"
    }
  ],
  "drivers": [
    {
      "id": "29a2bd60c4b841c686be68d2874c0c02",
      "name": "Athena IDProtect",
      "file": {
        "linux": {
          "x86": "/usr/lib/x86-athena/libASEP11.so",
          "x64": "/usr/lib/x64-athena/libASEP11.so"
        },
        "osx": "/Library/Application Support/Athena/libASEP11.dylib",
        "windows": "%WINDIR/System32/asepkcs.dll"
      }
    },
    {
      "id": "11A4BEA85E4C5D7EC6CDE452A70448A73EBE191B",
      "name": "Siemens CardOS M 4.2 (SLE66CX642P)",
      "file": {
        "windows": "%WINDIR/System32/eTPKCS11.dll",
        "linux": "/usr/lib/libeTPkcs11.so",
        "osx": "/usr/local/lib/libeTPkcs11.dylib"
      }
    },
    {
      "id": "39798896FC5DD6E2A96989718F694334275E0EAC",
      "name": "National Identity Document: Slovenian eID",
      "file": {
        "windows": {
          "x86": "%PROGRAMFILES(X86)/eID klient/pkcs11_x64.dll",
          "x64": "%PROGRAMFILES(X86)/eID klient/pkcs11_x86.dll"
        },
        "linux": {
          "x86": "/usr/lib/eidklient/libpkcs11_sig_x64.so",
          "x64": "/usr/lib/eidklient/libpkcs11_sig_x86.so"
        },
        "osx": "/Applications/eIDklient.app/Contents/Pkcs11/libPkcs11.dylib"
      }
    },
    {
      "id": "25fb0440047947539fd871831ac8477c",
      "name": "Siemens Card CardOS M4.4",
      "file": {
        "osx": "/usr/local/lib/libcardos11.dylib",
        "windows": {
          "x86": "%WINDIR/System32/cardos11.dll",
          "x64": "%WINDIR/System32/cardos11_64.dll"
        }
      }
    },
    {
      "id": "fea007cafe404e4fb56a8be39f60dc8f",
      "name": "Safran Morpho",
      "file": {
        "windows": "%WINDIR/SysWOW64/CnfPkcs11v220.dll",
        "osx": "/usr/local/lib/libCnfPkcs11.dylib "
      }
    },
    {
      "id": "39b3d7a3662c4b48bb120d008dd18648",
      "name": "SafeNet Authentication Client",
      "file": {
        "windows": "%WINDIR/System32/eTPKCS11.dll",
        "osx": "/usr/local/lib/libeTPkcs11.dylib",
        "linux": "/usr/lib/libeTPkcs11.so"
      }
    },
    {
      "id": "3e3d68d231b442d381f856cc80d57f18",
      "name": "SafeNet eToken",
      "file": {
        "windows": "%WINDIR/System32/eToken.dll"
      }
    },
    {
      "id": "c4e60449442848c48af7b3fcf6a6f4a1",
      "name": "Estonian eID Middleware",
      "file": {
        "windows": "%WINDIR/System32/onepin-opensc-pkcs11.dll",
        "osx": "/Library/EstonianIDCard/lib/esteid-pkcs11-onepin.so"
      }
    },
    {
      "id": "993988460d8f49a2ac519a2935f00533",
      "name": "YubiKey",
      "file": {
        "osx": "/usr/local/lib/libykcs11.dylib",
        "linux": "/usr/local/lib/libykcs11.so",
        "windows": "%WINDIR/System32/libykcs11-1.dll"
      }
    },
    {
      "id": "7d3a38d2d8294234a53d5845d6d116c4",
      "name": "Aktiv Rutoken ECP",
      "file": {
        "windows": "%WINDIR/System32/rtPKCS11ECP.dll",
        "osx": "/usr/local/lib/librtpkcs11ecp.dylib",
        "linux": "/usr/local/lib/librtpkcs11ecp.so"
      }
    },
    {
      "id": "993988460d8f49a2ac519a2935f11533",
      "name": "OpenSC driver",
      "file": {
        "osx": "/Library/OpenSC/lib/pkcs11/opensc-pkcs11.so",
        "linux": [
          "/usr/lib/opensc-pkcs11.so",
          "/usr/lib/x86_64-linux-gnu/opensc-pkcs11.so"
        ],
        "windows": "%WINDIR/System32/opensc-pkcs11.dll"
      }
    },
    {
      "id": "89648ea52ed24a799aff9f9ff363eef4",
      "name": "Belgian eID Middleware",
      "file": {
        "osx": "/usr/local/lib/beid-pkcs11.bundle/Contents/MacOS/libbeidpkcs11.dylib",
        "linux": "/usr/lib/libbeidpkcs11.so",
        "windows": "libbeidpkcs11.dll"
      }
    },
    {
      "id": "0ca280b5af17d6aa91af084f2d39d2a3",
      "name": "Gemalto IDPrime MD",
      "file": {
        "osx": "/usr/local/lib/libidprimepkcs11.0.dylib",
        "windows": {
          "x86": "%WINDIR/System32/eTPKCS11.dll",
          "x64": "%WINDIR/SysWOW64/eTPKCS11.dll"
        }
      }
    },
    {
      "id": "3bcf3e1d4952cfa3e486934887f45a0f",
      "name": "AET",
      "file": {
        "windows": "%WINDIR/System32/aetpkss1.dll"
      }
    },
    {
      "id": "71789068c5ff4891aeeaf7fb9608a22f",
      "name": "Gemalto Classic",
      "file": {
        "windows": {
          "x86": "%PROGRAMFILES(X86)/Gemalto/Classic Client/BIN/gclib.dll",
          "x64": "%PROGRAMFILES/Gemalto/Classic Client/BIN/gclib.dll"
        }
      }
    },
    {
      "id": "445912C0D3A36598078024B49C87336F45B16EA9",
      "name": "eOP Czech",
      "file": {
        "osx": "/usr/local/lib/eOPCZE/libeop2v1czep11.dylib",
        "linux": "/usr/lib/x86_64-linux-gnu/libeop2v1czep11.so",
        "windows": {
          "x86": "%WINDIR/System32/eop2v1czep11.dll",
          "x64": "%WINDIR/SysWOW64/eop2v1czep11.dll"
        }
      }
    }
  ]

**Comment by rmhrisk** [comment]
It seems that this card.json would work for you, specifically because:
```json
{
	"cards": [{
		"atr": "3B7D18000000487970734944205333079000",
		"name": "Safran Morpho YpsID S3",
		"driver": "fea007cafe404e4fb56a8be39f60dc8f"
	}],
	"drivers": [{
		"id": "fea007cafe404e4fb56a8be39f60dc8f",
		"name": "Safran Morpho",
		"file": {
			"windows": "%WINDIR/SysWOW64/CnfPkcs11v220.dll",
			"osx": "/usr/local/lib/libCnfPkcs11.dylib "
		}
	}]
}
```

Does it work for you?

**Comment by rmhrisk** [comment]
Actually, it seems we need the non 64-bit package for you:



It seems it should be:

```json
{
	"cards": [{
		"atr": "3B7D18000000487970734944205333079000",
		"name": "Safran Morpho YpsID S3",
		"driver": "fea007cafe404e4fb56a8be39f60dc8f"
	}],
	"drivers": [{
		"id": "fea007cafe404e4fb56a8be39f60dc8f",
		"name": "Safran Morpho",
		"file": {
			"windows": {
				"x86": "%WINDIR\system32\CnfPkcs11v220.dll",
				"x64": "%WINDIR/SysWOW64/CnfPkcs11v220.dll"
			},
			"osx": "/usr/local/lib/libCnfPkcs11.dylib "
		}
	}]
}
```
@microshine please update card.json

**Comment by microshine** [comment]
Fixed in `cards.json@1.0.30` 

Please restart Fortify application to update `cards.json`
