### ISSUE TITLE
Add support for '3bff1800ff8131fe55006b0209030301010144534410318090' token

### ISSUE THREAD

**Issue by jenkin90** [PeculiarVentures/fortify#251]
Reader name: ACS CCID USB Reader 0
ATR: 3BFF1800FF8131FE55006B0209030301010144534410318090

```js
{
   "cards": [{
   	"atr": "3BFF1800FF8131FE55006B0209030301010144534410318090",
   	"name": "Token name",
   	"driver": "709F7FAFA0BF267C91C832E29AAED0D06AB22D92"
   }],
   "drivers": [{
   	"id": "709F7FAFA0BF267C91C832E29AAED0D06AB22D92",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BFF1800FF8131FE55006B0209030301010144534410318090](https://smartcard-atr.appspot.com/parse?ATR=3BFF1800FF8131FE55006B0209030301010144534410318090)

**Comment by microshine** [comment]
I published a new version of the card.json with `Bit4ID`. Please check it.
- Restart your Fortify to get the latest cards.json version
- Check `~/.fortify/card.json`. It must be v1.0.24
