### ISSUE TITLE
Firefox doesnot allow connections to localhost

### ISSUE THREAD

**Issue by farazdeveloper** [PeculiarVentures/fortify#255]
I want digital signature access for login in mozilla firefox, but getting error "Unfortunately, your browser doesn't allow connections to locahost. Please try a different browser.
![mozilla-error](https://user-images.githubusercontent.com/36696877/68468486-229a8000-023e-11ea-89f9-12f2f55695b0.PNG)
"

**Comment by rmhrisk** [comment]
Fortify does work on Firefox.

It is likely there is an issue with your install somehow not trusting the SSL certificate that Fortify installs.

When it was installed it asked for you to approve installation of a trusted root, dis you accept?

**Comment by rmhrisk** [comment]
Please attach your fortify log.

**Comment by donskov** [comment]
Resolved
