### ISSUE TITLE
Add support for '3bff9600008131804380318065b0850300ef120ffe82900066' token

### ISSUE THREAD

**Issue by KLAM-Sympli** [PeculiarVentures/fortify#257]
Reader name: AKS ifdh 0
ATR: 3BFF9600008131804380318065B0850300EF120FFE82900066

```js
{
   "cards": [{
   	"atr": "3BFF9600008131804380318065B0850300EF120FFE82900066",
   	"name": "Token name",
   	"driver": "84FDB48C372B5038BE014E83E83F6C99FDE25985"
   }],
   "drivers": [{
   	"id": "84FDB48C372B5038BE014E83E83F6C99FDE25985",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BFF9600008131804380318065B0850300EF120FFE82900066](https://smartcard-atr.appspot.com/parse?ATR=3BFF9600008131804380318065B0850300EF120FFE82900066)

**Comment by rmhrisk** [comment]
Can you share information about this card?

What is the manufacturer?
What is the model?
What is the issuer?
What PKCS11 library do you use with it?
Where on the file system do you find this PKCS11 linrary?

**Comment by KLAM-Sympli** [comment]
Hi @rmhrisk ,

I have found the existing thread for this issue.
Please refer to https://github.com/PeculiarVentures/fortify/issues/140
Thanks
