### ISSUE TITLE
Problems building for Windows

### ISSUE THREAD

**Issue by jorgebaroncacv** [PeculiarVentures/fortify#258]
First of All, thanks for your help.

I have already built the app in a debian distro, and it worked perfecly. I had to install some node modules before to do it, but finally i built it.

However, I tried to do the same in windows, but i could not get the result i expected. i acomplished to built the app, i could install it without problem, but when run it, the server that should be listening in 127.0.0.1:31337,it is not working, so it did not detect the certificates.

I had to change the version of electron to 4.0.1, becasue with the version 5.0.6, i got the error of NODE_MODULES mistmach. Beacuse i built with the version 70, and the windows-electron-x64 binaries of your release are in NODE_MODULES version 69. I think that this is the problem beacuse it do not works fine.  

It is possible that i could generate the windows-electron-x64 too?

Any suggestion to help me to build this app?

Thanks.

**Comment by rmhrisk** [comment]
You will need to check if the installer successfully installed the root certificate created at install time.

You will need to see if you can manually connect to that ip and port successfully in each browser.

You will needs to provide a fortify of.

**Comment by donskov** [comment]
Created the [separate](https://github.com/PeculiarVentures/fortify-setup/tree/macos-package) private repo for build installers
