### ISSUE TITLE
An error occurred. You do not appear to have any cryptographic providers registered. This is probably a problem with your installation.

### ISSUE THREAD

**Issue by thiago-molive** [PeculiarVentures/fortify#263]
I run npm install then npm start on desktop app and web, but i received the message "An error occurred. You do not appear to have any cryptographic providers registered. This is probably a problem with your installation."

How can i to solve it?

**Comment by microshine** [comment]
Please download Fortify from website https://fortifyapp.com/

**Comment by thiago-molive** [comment]
> Please download Fortify from website https://fortifyapp.com/


can i sign xml with a3 certificates via web browser with this app?

**Comment by microshine** [comment]
yes, you can

use [xmldsigjs](https://github.com/PeculiarVentures/xmldsigjs) and [xadesjs](https://github.com/PeculiarVentures/xadesjs) modules

**Comment by thiago-molive** [comment]
> yes, you can
> 
> use [xmldsigjs](https://github.com/PeculiarVentures/xmldsigjs) and [xadesjs](https://github.com/PeculiarVentures/xadesjs) modules

Thank's.

If i download app from site,  it would work when run npm start?

Where i find the documentation?

**Comment by microshine** [comment]
Fortify is a service. You don't need to use `npm start`. It starts on System start.

See
https://peculiarventures.github.io/fortify-examples/
https://github.com/PeculiarVentures/fortify-examples
https://xadesjs.com/
https://github.com/PeculiarVentures/xadesjs/tree/gh-pages
https://github.com/PeculiarVentures/xadesjs/tree/gh-pages

**Comment by thiago-molive** [comment]
I really can't understand how these features work.
and spent hours trying to understand, reading and adapting examples, but couldn't make it work.

example5 shows how to sign a text, but wanted to adapt to sign an xml as it is done in xades, but without the prefix ds:

I also wanted to change the port that is used in the desktop app and the link to the site, but I can't put the app to work.

**Comment by rmhrisk** [comment]
- Did you install fortify from its website?
- We’re you able to generate a CSR or self signed certificate with Fortify?
- If so we can say with confidence that part is working.
- Did you download the xmldsigjs project and get the sample on the readme to work in browser? .
- if so we can say with confidence xmldsif signing is working. 
- Did you look at the fortify example for signing? Does it work for you on the examples page?
- if so we can saw with confidence fortify is working.
- Have you gotten that example to work locally?
- if so we can say with confidence fortify is working.
- Have you tried changing the XMLDSIG example to use a fortify webcryoto object?
- did that work? Did it give an error?

**Comment by thiago-molive** [comment]
I installed app from the official website and it worked perfectly.

I didn't even try to generate a self-signed certificate, I was trying to use a real digital certificate generated by a certificate authority.

I can't use xmldsig.js. I don't know node well, I never worked with it, so I have difficulty run samples 
the way I need.

fortify generated a signature that I don't know how to use, I'm used to generating the signature with C # features that I can't use on website.

I'm just asking for help to understand how it works, because I still don't understand the relationship between the fortify, xades and xmldsigjs projects to work with it

**Comment by rmhrisk** [comment]
Fortify is just a WEBCRYPTO implementation.

Start by getting the xmldsig sample to work once you do that just switch the webcrypto implementation.

**Comment by thiago-molive** [comment]
I give up, i spent a lot of time just having parse errors.

**Comment by rmhrisk** [comment]
You essentially gave us no data beyond I can’t get it to work. You didn’t follow the supplied instructions that would have led you to success. I give up.
