### ISSUE TITLE
Add support for '3bda13ff8131fb468012392f31c173c601c03b' token

### ISSUE THREAD

**Issue by MasakiMinamide** [PeculiarVentures/fortify#264]
Reader name: Alcor Micro AU9560
ATR: 3BDA13FF8131FB468012392F31C173C601C03B

```js
{
   "cards": [{
   	"atr": "3BDA13FF8131FB468012392F31C173C601C03B",
   	"name": "Individual Number Card ",
   	"driver": "E3C260286EC0AD8C12407F0D56A0C65A61E48884"
   }],
   "drivers": [{
   	"id": "E3C260286EC0AD8C12407F0D56A0C65A61E48884",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDA13FF8131FB468012392F31C173C601C03B](https://smartcard-atr.appspot.com/parse?ATR=3BDA13FF8131FB468012392F31C173C601C03B)

This card is issued by Japan Agency for Local Authority Information Systems.

**Comment by MasakiMinamide** [comment]
The driver is already implemented in OpenSC.
https://github.com/OpenSC/OpenSC/pull/801

**Comment by rmhrisk** [comment]
Can you tell us the make/model of this card?

Is it a read only card?

**Comment by MasakiMinamide** [comment]
MacOS 版の場合：
name=JPKI_Appli-01
path=/usr/local/lib/JPKIPKCS11.dylib
pathSign=/usr/local/lib/JPKIPKCS11Sign.dylib
pathAuth=/usr/local/lib/JPKIPKCS11Auth.dylib

I added the path to card.json as 
`
  card : {
      "atr": "3BDA13FF8131FB468012392F31C173C601C03B",
      "name": "National Identity Document: Japanese eID",
      "readOnly": false,
      "driver": "E3C260286EC0AD8C12407F0D56A0C65A61E48884"
    },
 driver: {
      "id": "E3C260286EC0AD8C12407F0D56A0C65A61E48884",
      "name": "National Identity Document: Japanese eID",
      "file": {
        "osx": "/usr/local/lib/JPKIPKCS11.dylib"
      }
    }
`

Restart get me this error: 

`{"message":"Provider:Token:Insert: reader:'Alcor Micro AU9560' name:'National Identity Document: Japanese eID' atr:3bda13ff8131fb468012392f31c173c601c03b","level":"info"}
{"message":"Provider:Token:Insert: Loading PKCS#11 library from /usr/local/lib/JPKIPKCS11.dylib","level":"info"}
{"message":"Provider:Token:Insert: Looking for Alcor Micro AU9560 into 1 slot(s)","level":"info"}
{"message":"Error: CKR_FUNCTION_FAILED:6\n    at Error (native) C_GetTokenInfo:243\n    at Token.getInfo (/Applications/Fortify.app/Contents/Resources/app/node_modules/graphene-pk11/build/token.js:33:31)\n    at new Token (/Applications/Fortify.app/Contents/Resources/app/node_modules/graphene-pk11/build/token.js:30:14)\n    at Slot.getToken (/Applications/Fortify.app/Contents/Resources/app/node_modules/graphene-pk11/build/slot.js:21:16)\n    at new Crypto (/Applications/Fortify.app/Contents/Resources/app/node_modules/node-webcrypto-p11/build/crypto.js:38:32)\n    at new Pkcs11Crypto (/Applications/Fortify.app/Contents/Resources/app/node_modules/@webcrypto-local/server/build/index.js:1790:9)\n    at /Applications/Fortify.app/Contents/Resources/app/node_modules/@webcrypto-local/server/build/index.js:2113:40\n    at Array.forEach (<anonymous>)\n    at LocalProvider.onTokenInsert (/Applications/Fortify.app/Contents/Resources/app/node_modules/@webcrypto-local/server/build/index.js:2111:29)\n    at CardWatcher.emit (events.js:194:13)\n    at PCSCWatcher.<anonymous> (/Applications/Fortify.app/Contents/Resources/app/node_modules/@webcrypto-local/server/build/index.js:868:26)","level":"error"}
{"message":"Provider:Token Amount of tokens was changed (+0/-0)","level":"info"}
`

**Comment by MasakiMinamide** [comment]
@rmhrisk 

Instead I tried opensc-pkcs11.so, and fortify stopped complaining.
```
    {
      "id": "E3C260286EC0AD8C12407F0D56A0C65A61E48884",
      "name": "JPKI_Appli-01",
      "file": {
        "osx": "/usr/local/lib/opensc-pkcs11.so"
      }
    }
```

I tested with fortify example4, which successfully showed full item list in the smartcard!
But with example5, I get cryptoServerError. I suspect this is because the driver is not right...
How can I fix this?

```
webcrypto-socket.js:3320 Uncaught (in promise) CryptoServerError: Unrecognized name
    at Client.onMessage (https://peculiarventures.github.io/fortify-examples/src/webcrypto-socket.js:3530:25)
```

**Comment by rmhrisk** [comment]
Did you get this working?

**Comment by MasakiMinamide** [comment]
OpenSC worked.

```
 "file": {
        "osx": "/usr/local/lib/opensc-pkcs11.so"
      }

```

**Comment by rmhrisk** [comment]
We will add this to the prod config file

**Comment by microshine** [comment]
Added to `cards.json` v1.0.26
