### ISSUE TITLE
Add support for '3bfd1800008031fe45736674652d63643038302d6e66dc' token

### ISSUE THREAD

**Issue by thiago-molive** [PeculiarVentures/fortify#268]
Reader name: CASTLES EZ100PU 0
ATR: 3BFD1800008031FE45736674652D63643038302D6E66DC

```js
{
   "cards": [{
   	"atr": "3BFD1800008031FE45736674652D63643038302D6E66DC",
   	"name": "Token name",
   	"driver": "973920FCAD87B1EBE7DDE5F6E3C383FB9487C76C"
   }],
   "drivers": [{
   	"id": "973920FCAD87B1EBE7DDE5F6E3C383FB9487C76C",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BFD1800008031FE45736674652D63643038302D6E66DC](https://smartcard-atr.appspot.com/parse?ATR=3BFD1800008031FE45736674652D63643038302D6E66DC)

**Comment by rmhrisk** [comment]
@thiago-molive what PKCS11 library do you use with this device?

What is the make and model?

**Comment by thiago-molive** [comment]
> @thiago-molive what PKCS11 library do you use with this device?
> What is the make and model?


about PKCS11 library, where can I find this information?

The make is Nonus and model smarthnonus.

**Comment by rmhrisk** [comment]
Do you use this token with other applications? For example with Firefox, Edge, acrobat, outlook, etc.

**Comment by thiago-molive** [comment]
we use this for signing pdf's in pdf xchange and other desktop aplications.

**Comment by rmhrisk** [comment]
Which applications? That will hopefully tell me what I can ask from you so it will work with Fortify.

**Comment by rmhrisk** [comment]
Is this related to your card: https://www.tjrs.jus.br/site/certificacao_digital/requisitos_sistema.html

**Comment by rmhrisk** [comment]
Do you have aetpkss1.dll on your computer?

**Comment by thiago-molive** [comment]
> Which applications? That will hopefully tell me what I can ask from you so it will work with Fortify.

It is nothing related to installed desktop applications.
I am using fortity to sign some xml's on the site. I can sign perfectly with A1 certificate. but with this smartcard message appears that is not supported or the other token I have here i'm generate a invalid signature.

**Comment by thiago-molive** [comment]
> Do you have aetpkss1.dll on your computer?

yes a found in System32 and SysWOW64

**Comment by rmhrisk** [comment]
I believe this will make your card work:

```
{
	"cards": [{
		"atr": "3BFD1800008031FE45736674652D63643038302D6E66DC",
		"name": "Nonus SmartNonus [BR]",
		"driver": "3bcf3e1d4952cfa3e486934887f45a0f"
	}]
}
```

Please add this to your card.json file:

~/.fortify/card.json

And try again, if it works for you we will add it to a future release.

**Comment by thiago-molive** [comment]
> ~/.fortify/card.jso



> I believe this will make your card work:
> 
> ```
> {
> 	"cards": [{
> 		"atr": "3BFD1800008031FE45736674652D63643038302D6E66DC",
> 		"name": "Nonus SmartNonus [BR]",
> 		"driver": "3bcf3e1d4952cfa3e486934887f45a0f"
> 	}]
> }
> ```
> 
> Please add this to your card.json file:
> 
> ~/.fortify/card.json
> 
> And try again, if it works for you we will add it to a future release.

Yes, it work great. Thank you very much!!!

**Comment by thiago-molive** [comment]
How do you did that? because if I need new cards I can add a new code to json and reply here.

**Comment by rmhrisk** [comment]
I guessed from the information you provided, I used those guesses, and the ATR you provided to search.

@microshine please add this to card.json

**Comment by microshine** [comment]
Fixed in `cards.json@1.0.30` 

Please restart Fortify application to update `cards.json`
