### ISSUE TITLE
How to deal with an expired certificate for 127.0.0.1:31337 ?

### ISSUE THREAD

**Issue by JanSlabon** [PeculiarVentures/fortify#270]
It's that easy, the certificate expired on 2020-01-07 on my computer and I'm locked out of Fortify. Do I need to manually reinstall Fortify or is there a way to update this by the program itself?

Thanks!
Jan

**Comment by microshine** [comment]
It must renew a certificate.
I'll check it.

You can remove `cert` and `key` files from `~/.fortify` folder and restart Fortify. It'll create a new cert on start

**Comment by JanSlabon** [comment]
Update: I just did an update of Fortify and the cert was not renewed.

**Comment by microshine** [comment]
I've created a new ticket https://github.com/PeculiarVentures/fortify/issues/272 to fix this issue
