### ISSUE TITLE
Add support for '3b1696417374726964' token

### ISSUE THREAD

**Issue by craftbyte** [PeculiarVentures/fortify#274]
Reader name: Gemalto USB Key Smart Card Reader 0
ATR: 3B1696417374726964

```js
{
   "cards": [{
   	"atr": "3B1696417374726964",
   	"name": "Token name",
   	"driver": "4FD5273D8C65CCA37ACCED4B7258F1BF78ACEBBD"
   }],
   "drivers": [{
   	"id": "4FD5273D8C65CCA37ACCED4B7258F1BF78ACEBBD",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3B1696417374726964](https://smartcard-atr.apdu.fr/parse?ATR=3B1696417374726964)

**Comment by craftbyte** [comment]
It is a Gemalto .NET card (similar to MD).

**Comment by rmhrisk** [comment]
Can you share the path and file name to where the PKCS11 is on your system?

**Comment by craftbyte** [comment]
here is a working config:
```json
    {
      "atr": "3B1696417374726964",
      "libraries": [
        "C:/Program Files (x86)/Gemalto/IDGo 800 PKCS#11/IDPrimePKCS1164.dll"
      ],
      "name": "Gemalto IDPrime .NET",
      "readOnly": false
    }
```

**Comment by microshine** [comment]
I found other paths for this library
- Linux
  - x86
    - /usr/lib/libIDPrimePKCS11.so
  - x64
    - /usr/lib64/libIDPrimePKCS11.so
- OS X
  - /usr/local/lib/libidprimepkcs11.0.dylib
- Windows
  - x86
    - C:\Program Files (x86)\Gemalto\IDGo 800 PKCS#11\IDPrimePKCS11.dll
  - x64
    - C:\Program Files (x86)\Gemalto\IDGo 800 PKCS#11\IDPrimePKCS1164.dll

@craftbyte Do you have a possibility to check those libraries?

**Comment by rmhrisk** [comment]
Looks like this is the JSON to try?

```js
{
	"cards": [{
		"atr": "3B1696417374726964",
		"name": "Gemalto IDPrime .NET"",
		"driver": "fb52636e98f44ebe837db93c46721463"
	}],
	"drivers": [{
		"id": "fb52636e98f44ebe837db93c46721463",
		"name": "Gemalto ID Prime",
		"file": {
			"windows": {
				"x86": "C:/Program Files (x86)/Gemalto/IDGo 800 PKCS#11/IDPrimePKCS11.dll",
				"x64": "C:/Program Files (x86)/Gemalto/IDGo 800 PKCS#11/IDPrimePKCS1164.dll"
			},
			"linux": {
				"x86": "/usr/lib/libIDPrimePKCS11.so",
				"x64": "/usr/lib64/libIDPrimePKCS11.so"
			},
			"osx": "/usr/local/lib/libidprimepkcs11.0.dylib"
		}
	}]
}
```

**Comment by craftbyte** [comment]
Since I see you guys are using %PROGRAMFILES I would just replace that on windows, otherwise looks ok.

**Comment by rmhrisk** [comment]
@microshine please add to cards.json

**Comment by microshine** [comment]
Fixed in `cards.json@1.0.30` 

Please restart Fortify application to update `cards.json`
