### ISSUE TITLE
Add support for '3b7d96000080318065b0830201f383009000' token

### ISSUE THREAD

**Issue by craftbyte** [PeculiarVentures/fortify#275]
Reader name: OMNIKEY CardMan 3821 0
ATR: 3B7D96000080318065B0830201F383009000

```js
{
   "cards": [{
   	"atr": "3B7D96000080318065B0830201F383009000",
   	"name": "Token name",
   	"driver": "244EAB624FE437DFDD4E3A2C0E01B7AA21191D69"
   }],
   "drivers": [{
   	"id": "244EAB624FE437DFDD4E3A2C0E01B7AA21191D69",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3B7D96000080318065B0830201F383009000](https://smartcard-atr.apdu.fr/parse?ATR=3B7D96000080318065B0830201F383009000)

**Comment by craftbyte** [comment]
It is a Nexus Smart Card from HALCOM CA (Slovenia).

Link to Mac and Windows Installer:

https://nexus.halcom.com/Nexus/download/Personal_x64.msi
https://nexus.halcom.com/Nexus/download/Personal.dmg

**Comment by rmhrisk** [comment]
Can you share the path and file name to where the PKCS11 for this device is on your system?

**Comment by microshine** [comment]
Please update your `~/.fortify/config.json` file and restart Fortify

Let me know if it works. I'll update and publish `cards.json`

```cjson
{
  // other configurations
  "cards": [
    {
      "atr": "3B7D96000080318065B0830201F383009000",
      "libraries": [
        "C:\Program Files\TrustEdgeID\netsetpkcs11_x64.dll"
      ],
      "name": "Gemalto IDClassic 340",
      "readOnly": false
    }
  ]
}
```

**Comment by craftbyte** [comment]
@microshine I don't have TrustEdgeID installed. I tried installing and no success.

Correct path is: C:\Program Files (x86)\Personal\bin64\personal64.dll for 64 bit and C:\Program Files (x86)\Personal\bin\personal.dll for 32 bit.

**Comment by craftbyte** [comment]
here is a working config:
```json
{
      "atr": "3B7D96000080318065B0830201F383009000",
      "libraries": [
        "C:/Program Files (x86)/Personal/bin64/personal64.dll"
      ],
      "name": "Gemalto IDClassic 340",
      "readOnly": false
    }
```

**Comment by rmhrisk** [comment]
It looks like the correct configuration file is:

```js
{
	"cards": [{
		"atr": "3B7D96000080318065B0830201F383009000",
		"name": "Gemalto IDClassic 340",
		"driver": "3B7D96000080318065B0830201F383009000"
	}],
	"drivers": [{
		"id": "244EAB624FE437DFDD4E3A2C0E01B7AA21191D69",
		"name": "Nexus Persona",
		"file": {
			"windows": {
				"x86": "C:/Program Files (x86)/Personal/bin/personal.dll",
				"x64": "C:/Program Files (x86)/Personal/bin64/personal64.dll"
			}
		}
	}]
}
```

@craftbyte can you verify this works for you?

As an aside, it seems this same token is being used with pkcs11js: https://github.com/PeculiarVentures/pkcs11js/issues/57

**Comment by craftbyte** [comment]
Yes, a Slovenian CA (HALCOM) is issuing their certs on these cards. Looking at that issue it seems like me and Matej both have the same CA.

There is a typo in Personal.

I can confirm for Windows, but will also check on Mac once I get back into the office.

**Comment by rmhrisk** [comment]
@microshine please add to cards.json

**Comment by microshine** [comment]
Fixed in `cards.json@1.0.30` 

Please restart Fortify application to update `cards.json`
