### ISSUE TITLE
Add support for '3b7d96000080318065b0830201f383009000' token

### ISSUE THREAD

**Issue by ferikeem** [PeculiarVentures/fortify#276]
Reader name: BIT4ID miniLector EVO 0
ATR: 3B7D96000080318065B0830201F383009000

```js
{
   "cards": [{
   	"atr": "3B7D96000080318065B0830201F383009000",
   	"name": "Token name",
   	"driver": "F374E90132CD0C7F1370575B001745B5464550EA"
   }],
   "drivers": [{
   	"id": "F374E90132CD0C7F1370575B001745B5464550EA",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3B7D96000080318065B0830201F383009000](https://smartcard-atr.apdu.fr/parse?ATR=3B7D96000080318065B0830201F383009000)

**Comment by rmhrisk** [comment]
Can you share the path and file name to where the PKCS11 for this device is on your system?

What is the make and model of this device?

**Comment by ferikeem** [comment]
Hello @rmhrisk,

the path is probably this: `%PROGRAMFILES(X86)/Gemalto/Classic Client/BIN/gclib.dll`.
The card's processor is a Gemalto IDClassic 340, reader is a Bit4Id miniLector Evo 0.
I tried to add the following to card.json:
`	{
		"atr": "3B7D96000080318065B0830201F383009000",
		"name": "Classic TPC",
      	        "readOnly": true,
		"driver": "71789068c5ff4891aeeaf7fb9608a22f"
	},`
but Fortify complains about the middleware not being installed properly.
Here is the relevant part of the log:
`{"message":"PCSCWatcher: New reader detected BIT4ID miniLector EVO 0","level":"info"}
{"message":"PCSCWatcher: New reader detected BIT4ID miniLector EVO 0","level":"info"}
{"message":"PCSCWatcher:Insert reader:'BIT4ID miniLector EVO 0' ATR:3b7d96000080318065b0830201f383009000","level":"info"}
{"message":"PCSCWatcher:Insert reader:'BIT4ID miniLector EVO 0' ATR:3b7d96000080318065b0830201f383009000","level":"info"}
{"message":"Provider:Token:Insert: reader:'BIT4ID miniLector EVO 0' name:'Gemalto IDClassic 340' atr:3b7d96000080318065b0830201f383009000","level":"info"}
{"message":"Provider:Token:Insert: Loading PKCS#11 library from C:/Program Files (x86)/Gemalto/Classic Client/BIN/gclib.dll","level":"info"}
{"message":"Error: Win32 error 193\n    at Error (native) PKCS11::Load:136\n    at Function.load (C:\\Program Files\\Fortify\\resources\\app.asar\\node_modules\\graphene-pk11\\build\\module.js:15:13)\n    at LocalProvider.onTokenInsert (C:\\Program Files\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:2177:43)\n    at CardWatcher.emit (events.js:194:13)\n    at PCSCWatcher.<anonymous> (C:\\Program Files\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:867:26)\n    at PCSCWatcher.emit (events.js:194:13)\n    at Timeout._onTimeout (C:\\Program Files\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:797:38)\n    at listOnTimeout (internal/timers.js:535:17)\n    at processTimers (internal/timers.js:479:7)","level":"error"}
{"message":"WebCryptoLocalError: C:/Program Files (x86)/Gemalto/Classic Client/BIN/gclib.dll\n    at new WebCryptoLocalError (C:\\Program Files\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:340:23)\n    at LocalProvider.onTokenInsert (C:\\Program Files\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:2181:33)\n    at CardWatcher.emit (events.js:194:13)\n    at PCSCWatcher.<anonymous> (C:\\Program Files\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:867:26)\n    at PCSCWatcher.emit (events.js:194:13)\n    at Timeout._onTimeout (C:\\Program Files\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:797:38)\n    at listOnTimeout (internal/timers.js:535:17)\n    at processTimers (internal/timers.js:479:7)","level":"error"}
{"message":"Fortify: Create window message","level":"info"}`

Any help would be appreciated. Thanks you.

**Comment by ferikeem** [comment]
It works now, here's what I did (maybe this helps others):
I uninstalled the card's driver, then installed it again. [This](https://data-protection-updates.gemalto.com/wp-includes/ms-files.php?file=2015/05/007-012974-001_SafeNet_Authentication_Client_Minidriver-9-0_CRN_Revision-.pdf) pdf helped me resolve the driver issue.

Windows (Device manager) and Fortify both see the card fine (signing is yet to be checked).

What I added to `cards.json` is:
```json
    {
      "atr": "3b7d96000080318065b0830201f383009000",
      "name": "Gemalto IDClassic 340",
      "driver": "71789068c5ff4891aeeaf7fb9608a22f"
    },
```
One small note:
Fortify still logs some errors, maybe this will help devs resolve some issues.

> {"message":"Provider:Token:Insert: reader:'BIT4ID miniLector EVO 0' name:'Gemalto IDClassic 340' atr:3b7d96000080318065b0830201f383009000","level":"info"}
{"message":"Provider:Token:Insert: Loading PKCS#11 library from C:/Program Files (x86)/Gemalto/Classic Client/BIN/gclib.dll","level":"info"}
{"message":"Error: Win32 error 193\n    at Error (native) PKCS11::Load:136\n    at Function.load (C:\\Program Files\\Fortify\\resources\\app.asar\\node_modules\\graphene-pk11\\build\\module.js:15:13)\n    at LocalProvider.onTokenInsert (C:\\Program Files\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:2177:43)\n    at CardWatcher.emit (events.js:194:13)\n    at PCSCWatcher.<anonymous> (C:\\Program Files\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:867:26)\n    at PCSCWatcher.emit (events.js:194:13)\n    at Timeout._onTimeout (C:\\Program Files\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:797:38)\n    at listOnTimeout (internal/timers.js:535:17)\n    at processTimers (internal/timers.js:479:7)","level":"error"}
{"message":"Provider:Token:Insert: Loading PKCS#11 library from C:\\Program Files (x86)\\Gemalto\\Classic Client\\BIN\\gclib.dll","level":"info"}
{"message":"Error: Win32 error 193\n    at Error (native) PKCS11::Load:136\n    at Function.load (C:\\Program Files\\Fortify\\resources\\app.asar\\node_modules\\graphene-pk11\\build\\module.js:15:13)\n    at LocalProvider.onTokenInsert (C:\\Program Files\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:2177:43)\n    at CardWatcher.emit (events.js:194:13)\n    at PCSCWatcher.<anonymous> (C:\\Program Files\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:867:26)\n    at PCSCWatcher.emit (events.js:194:13)\n    at Timeout._onTimeout (C:\\Program Files\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:797:38)\n    at listOnTimeout (internal/timers.js:535:17)\n    at processTimers (internal/timers.js:479:7)","level":"error"}
{"message":"Provider:Token:Insert: Loading PKCS#11 library from C:\\Program Files\\Gemalto\\Classic Client\\BIN\\gclib.dll","level":"info"}
{"message":"Provider:Token:Insert: Looking for BIT4ID miniLector EVO 0 into 1 slot(s)","level":"info"}

**Comment by microshine** [comment]
@ferikeem I updated `cards.json` to v1.0.29. It includes your ATR.

About error in a log file. As you can see from `cards.json` a driver can have a list of libraries. In this case, Fortify tries to load libraries one by one and if PKCS#11 library throws an exception on load Fortify logs it.
This is why you can see error log for x86 library
