### ISSUE TITLE
Add support for '3bd518008131fe7d8073c82110f4' token

### ISSUE THREAD

**Issue by Janerson** [PeculiarVentures/fortify#287]
Reader name: AKS ifdh 0
ATR: 3BD518008131FE7D8073C82110F4

```js
{
   "cards": [{
   	"atr": "3BD518008131FE7D8073C82110F4",
   	"name": "SafeNet eToken (Aladdin) 5100 (Java Card)",
   	"driver": "39b3d7a3662c4b48bb120d008dd18648"
   }]
}
```

[Smart card ATR parsing 3BD518008131FE7D8073C82110F4](https://smartcard-atr.apdu.fr/parse?ATR=3BD518008131FE7D8073C82110F4)

**Comment by rmhrisk** [comment]
This appears to be a SafeNet eToken 5100 Javacard, if so the SAC client should work.

@microshine please add this to the ATR map.

**Comment by rmhrisk** [comment]
Strange, it seems this is already in the ATR map:
![image](https://user-images.githubusercontent.com/1619279/73290088-ac5d4800-41b2-11ea-9482-d9ed1b7add08.png)

@Janerson does the card work for you to create CSRs using Fortify?

**Comment by microshine** [comment]
@Janerson Please enable logging and share a log file
