### ISSUE TITLE
Add support for tokens

### ISSUE THREAD

**Issue by FlorianKnibbe** [PeculiarVentures/fortify#288]
Hi,

Is-it possible to add support for tokens :

Reader name: Neowave Weneo Reader 0
ATR: 3BF91800008031FE4580574E454F574156457D

```js
{
   "cards": [{
   	"atr": "3BF91800008031FE4580574E454F574156457D",
   	"name": "Charismathics",
   	"driver": "B967CCBF2E20B2EF3EDF0275206E706D517657F5"
   }],
   "drivers": [{
   	"id": "B967CCBF2E20B2EF3EDF0275206E706D517657F5",
   	"name": "NeoWave",
   	"file": {
   		"windows": "C:\windows\system32\cmp1164.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BF91800008031FE4580574E454F574156457D](https://smartcard-atr.appspot.com/parse?ATR=3BF91800008031FE4580574E454F574156457D)

Reader name: Gemalto USB SmartCard Reader 0
ATR: 3B7F96000080318065B0855956FB120FFE829000

```js
{
   "cards": [{
   	"atr": "3B7F96000080318065B0855956FB120FFE829000",
   	"name": "MD840",
   	"driver": "D36C91748EDD873A3E45F9B910C0B165160DC975"
   }],
   "drivers": [{
   	"id": "D36C91748EDD873A3E45F9B910C0B165160DC975",
   	"name": "Gemalto",
   	"file": {
   		"windows": "C:\Program Files (x86)\Gemalto\IDGo 800 PKCS#11\IDPrimePKCS1164.dll", 
   		"osx": "/usr/local/lib/pkcs11/libidprimepkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3B7F96000080318065B0855956FB120FFE829000](https://smartcard-atr.appspot.com/parse?ATR=3B7F96000080318065B0855956FB120FFE829000)

**Comment by rmhrisk** [comment]
@microshine pleaae clean up JSON and add.

**Comment by microshine** [comment]
Added to `cards.json@1.0.31`

**Comment by FlorianKnibbe** [comment]
Hi,

Thanks for your rapidity.
Unfortunately my card.json seem to be not updated. I've restarted, i've also tested to modify localy my card.json but I don't have my provider in the list.

I try your exemple : https://peculiarventures.github.io/fortify-examples/example1.html
I just have "Windows Crypto API" and Firefox NSS but not NeoWave and/or Gemalto.

Have you any idea for force to read/write my tokens ?

Best regards.
