### ISSUE TITLE
Truncated index

### ISSUE THREAD

**Issue by FlorianKnibbe** [PeculiarVentures/fortify#289]
Hi,

When I create Certificat request generation (your example1) on Charismatics providerr (ATR 3bf91800008031fe4580574e454f574156457d) I obtain truncate index for public key.

Private key : private-15000000-36383837393734332d643861382d346637652d393963352d376332656234333563643933

Public key : public-16000000-

This result is return by 
```js
const requestIndex = await crypto.certStorage.setItem(req);
```
Have you an idea where is problem ?

Thanks a lot
Best regards

**Comment by rmhrisk** [comment]
I am not sure how this is happening and we do not have a Charismathics device here or access to the middleware.

We could potentially try to execute the same code path with a certificate alone or software private key but I don't know this path by heart.

Can you start by sharing a Fortify log?

**Comment by microshine** [comment]
It's possible if PKCS#11 returns empty buffer for public key `CKA_ID` attribute

**Comment by rmhrisk** [comment]
Can you contact the Cryptomathics and ask them if the device supports CKA_ID?

**Comment by FlorianKnibbe** [comment]
Hi,

Ok, I will inform for CKA_ID. Where is Fortify log ?

Thank you for your help.

**Comment by microshine** [comment]
Fortify log is in `~/.fortify` folder. If you don't have log enable logging

![image](https://user-images.githubusercontent.com/7333669/73430935-427aa500-4350-11ea-887d-55b0efafb18d.png)

**Comment by FlorianKnibbe** [comment]
Hi,

Log On Web page (Chrome console) :
SocketProvider:connect
webcrypto-socket.min.js:15 SocketProvider:on error
webcrypto-socket.min.js:15 SocketProvider:on listening
example1.html:128 -----BEGIN CERTIFICATE REQUEST-----
MIICcTCCAVsCAQAwMDELMAkGA1UEBhMCRU4xITAfBgNVBAMeGABUAGUAcwB0ACAA
cgBlAHEAdQBlAHMAdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOex
Uu8ubFLzU4kkzA8891dFycD8eq/hlIUUjW6q4xFBat0gCsU5dp93vTQWFkSxs7Hp
a8Vt6RFkzEG+hR/C3n4YC3NGQnCm/ClQKQiQ3ni7fPiEffeUVEtMZIezaP4/MGac
GcgzJkZM46sFbsLdDH+ohoYu/s3zkK3lm7M4vRId/51pICkvsG1teHIcHxDUEO9L
TNwOAIZg/ev1GS9oUc3iJKVUgLhlprqvyKYYywlGeWjA1REj2b0F2ZuBHiamXhC6
9f10ZQEifZpjkJNt6lBJ1XvQe+qVP0eqTLHde9VAm7X9ATx/Mt5h9YN7C9V9VRfW
kIaD0wGkzLmKutRiQaUCAwEAATALBgkqhkiG9w0BAQsDggEBAMBSSYhHY05E8X1n
xx3rPdcMeuALeetFnF+LUlTcAEczfYEfPtUhO3Jvd39iRzTCvZmCuaFj/EVhLFVF
BIKK5OhC/K+rV2zO0KO0ZJ7B5c6cw5WI7dXaGV6ro22R5VhH3ZceJwuxMzEP/DY3
v+DApPAIiii4ymP5pHD/jJDhQ/3+qvs+N6/G7FbWzSTiexecrvxJSU60mAtw7kDt
Vxb71xV33LSoDFxPlK+RqC9uZTgVC3D1burLejeftVBmZ7upZcG2ulh9W7ALJSDv
3z22aen1WE/cyZhiGKysnnCHF9pLGFCmprTuAQbalzmP43gFDoGRnGhYVcH/lqhh
HnLtJyw=
-----END CERTIFICATE REQUEST-----
example1.html:139 Request was generated successfully.
Index of the request is request-1b000000-

Fortify log :
[fortify.log](https://github.com/PeculiarVentures/fortify/files/4132843/fortify.log)

Thanks

**Comment by microshine** [comment]
### Information
Fortify uses `CKA_ID` attribute for index creation
https://github.com/PeculiarVentures/node-webcrypto-p11/blob/master/src/key.ts#L38
```js
`${type}-${hex(handle)}-${hex(key.id)}`
```

Each time when you are creating or importing keys to your device Fortify creates and sets `CKA_ID` attribute `sha1(spki(key))`
https://github.com/PeculiarVentures/node-webcrypto-p11/blob/master/src/subtle.ts#L77
https://github.com/PeculiarVentures/node-webcrypto-p11/blob/master/src/subtle.ts#L59

As I can see from your logs it occurs for `public` keys only. I guess the problem is in PKCS#11 library implementation

**Comment by microshine** [comment]
@FlorianKnibbe Is it possible to make some tests with your token?

I can share some NodeJS scripts to test it

**Comment by FlorianKnibbe** [comment]
@microshine Yes it's possible. Say me what I can do :-)

**Comment by microshine** [comment]
I'll prepare some scripts and share it soon

What is your OS?
Do you have NodeJS on your system?
Do you have tools for NodeJS native plugin compilation?

**Comment by FlorianKnibbe** [comment]
I'm on Windows 10. I've nodeJS on my system and no I don't think I've tools for NodeJS native plugin compilation.

**Comment by microshine** [comment]
Please install NodeJS LTS v12. It must include C tools for native modules compilation

I'm going to use `pkcs11js` NPM module for tests. It requires C tools

**Comment by FlorianKnibbe** [comment]
OK I do

**Comment by microshine** [comment]
- extract files
- install deps
```
npm install
```
- update config variables in `test/index.ts`
```ts
const lib = "/usr/local/lib/softhsm/libsofthsm2.so";
const slotIndex = 0;
let pin: string | null = null;

pin = "12345"; // comment it if token doesn't use login
```
- run test
```
npm test
```

[fortify-issues-289.zip.txt](https://github.com/PeculiarVentures/fortify/files/4133100/fortify-issues-289.zip.txt)

**Comment by FlorianKnibbe** [comment]
I'm going to try.
If it's usefull, when I read  token content few minutes after  I see correct index :
![indexErr2](https://user-images.githubusercontent.com/43298554/73436384-b914a400-434a-11ea-89c7-effa9af91903.PNG)

**Comment by microshine** [comment]
It looks very strange. I'm more and more convinced that issue is in device library implementation

**Comment by FlorianKnibbe** [comment]
When running test I've errors, i think i don't set it up right :
![err](https://user-images.githubusercontent.com/43298554/73439360-c5e7c680-434f-11ea-8561-e9b69f409e8f.PNG)

Config :
const lib = "C:/Windows/System32/cmp1164.dll";
const slotIndex = 0;
let pin: string | null = null;

pin = "[myPIN]"; // comment it if token doesn't use login

**Comment by microshine** [comment]
Update you `package.json`

```json
"mocha": {
  "require": "ts-node/register",
  "spec": "test/**/*.ts",
  "timeout": 10000
}
```

**Comment by FlorianKnibbe** [comment]
Same result

**Comment by microshine** [comment]
Just test `example1` script. It returns correct indexes for added `public`, `private`, `request` objects
![image](https://user-images.githubusercontent.com/7333669/73442173-5a105880-4365-11ea-9719-e1a0f5031b04.png)

And `crypto.keyStorage.keys` returns a correct result too
![image](https://user-images.githubusercontent.com/7333669/73442446-e884da00-4365-11ea-89cb-0485df248454.png)

**Comment by FlorianKnibbe** [comment]
For me :
![Capture](https://user-images.githubusercontent.com/43298554/73445315-b752dc80-435a-11ea-9169-de305a317092.PNG)

**Comment by microshine** [comment]
Please one more test

- Add index.ts to test project
```ts
import * as graphene from "graphene-pk11";
import * as assert from "assert";

const lib = "/usr/local/lib/softhsm/libsofthsm2.so";
const slotIndex = 0;
let pin: string | null = null;

pin = "12345"; // comment it if token doesn't use login

async function main() {

  const token = graphene.Module.load(lib);
  try {
    token.initialize();
    const slot = token.getSlots(slotIndex);
    const session = slot.open(graphene.SessionFlag.RW_SESSION | graphene.SessionFlag.SERIAL_SESSION);

    if (pin) {
      session.login(pin);
    }

    const modulus = "vqpvdxuyZ6rKYnWTj/ZzDBFZAAAlpe5hpoiYHqa2j5kK7v8U5EaPY2bLib9m4B40j+n3FV9xUCGiplWdqMJJKT+4PjGO5E3S4N9kjFhu57noYT7z7302J0sJXeoFbXxlgE+4G55Oxlm52ID2/RJesP5nzcGTriQwoRbrJP5OEt0=";
    const exponent = "AQAB";

    var key = session.create({
      // object params
      keyType: graphene.KeyType.RSA,
      class: graphene.ObjectClass.PUBLIC_KEY,
      token: false,

      // key params
      modulus: Buffer.from(modulus, "base64"),
      publicExponent: Buffer.from(exponent, "base64"),

      // usages
      verify: true,

      // attrs
      id: Buffer.from("1234567890"),
      label: "Test key"
    }).toType<graphene.PublicKey>();

    assert.equal("1234567890", key.id.toString());

    console.log("Success");
  }
  finally {
    token.finalize();
  }
}

main().then(e =>console.error(e));
```
- Add script to `package.json`
```json
"scripts": {
  "test": "mocha",
  "start": "ts-node ."
}
```
- Run script
```
npm start
```

**Comment by microshine** [comment]
I'm trying to check that you PKCS#11 library allows to set and get `CKA_ID` for public key object

**Comment by FlorianKnibbe** [comment]
My package.json : 
```js
{
  "name": "fortify-issues-289",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
	  "test": "mocha",
	  "start": "ts-node ."
},
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@types/mocha": "^7.0.1",
    "@types/node": "^13.5.2",
    "graphene-pk11": "^2.1.3",
    "mocha": "^7.0.1",
    "ts-node": "^8.6.2",
    "typescript": "^3.7.5"
  },
  "mocha": {
    "require": "ts-node/register",
    "spec": "test/**/*.ts",
	"timeout": 10000
  }
  
}
```
Launch result : 
```
> fortify-issues-289@1.0.0 start C:\Users\knibbe\Downloads\fortify-issues-289
> ts-node .

Error: Cannot find module 'C:\Users\knibbe\Downloads\fortify-issues-289\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:297:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:528:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:27)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at main (C:\Users\knibbe\Downloads\fortify-issues-289\node_modules\ts-node\src\bin.ts:226:14)
    at Object.<anonymous> (C:\Users\knibbe\Downloads\fortify-issues-289\node_modules\ts-node\src\bin.ts:485:3)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fortify-issues-289@1.0.0 start: `ts-node .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fortify-issues-289@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\knibbe\AppData\Roaming\npm-cache\_logs\2020-01-30T11_48_09_637Z-debug.log
```

**Comment by FlorianKnibbe** [comment]
If help you, token is that : http://neowave.fr/FR/gamme_weneo_2.html
