### ISSUE TITLE
Add support for '3bdb960080b1fe451f830031c164084022300f90000a' token

### ISSUE THREAD

**Issue by thibaultgobier** [PeculiarVentures/fortify#291]
Reader name: Gemalto USB SmartCard Reader 0
ATR: 3BDB960080B1FE451F830031C164084022300F90000A

```js
{
   "cards": [{
   	"atr": "3BDB960080B1FE451F830031C164084022300F90000A",
   	"name": "Gemalto Idopte",
   	"driver": "4FB7EC5520E08886A7091F9B839CD791CE401D33"
   }],
   "drivers": [{
   	"id": "4FB7EC5520E08886A7091F9B839CD791CE401D33",
   	"name": "Idopte",
   	"file": {
   		"windows": "C:\Program Files\Idopte\Smart Card Middleware\bin\idoPKCS.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BDB960080B1FE451F830031C164084022300F90000A](https://smartcard-atr.appspot.com/parse?ATR=3BDB960080B1FE451F830031C164084022300F90000A)

**Comment by rmhrisk** [comment]
@thibaultgobier we can add support for this if the configuration you have proposed above works. Let us know.
