### ISSUE TITLE
Add support for '3bff1800008131fe55006b02090403010101434e5310318065' token

### ISSUE THREAD

**Issue by lucamartellucci** [PeculiarVentures/fortify#293]
Reader name: Broadcom Corp Contacted SmartCard 0
ATR: 3BFF1800008131FE55006B02090403010101434E5310318065

```js
{
   "cards": [{
   	"atr": "3BFF1800008131FE55006B02090403010101434E5310318065",
   	"name": "Token name",
   	"driver": "6DA711493B15DB5441A9ADA11D3D59644EC5C09E"
   }],
   "drivers": [{
   	"id": "6DA711493B15DB5441A9ADA11D3D59644EC5C09E",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BFF1800008131FE55006B02090403010101434E5310318065](https://smartcard-atr.apdu.fr/parse?ATR=3BFF1800008131FE55006B02090403010101434E5310318065)

**Comment by rmhrisk** [comment]
This appears to be “ Italian Chambers of Commerce CNS (PKI)” is that correct?

What is the fully qualified file name of the PKCS11 you use with this card?

**Comment by rmhrisk** [comment]
@defacto64 do you have access to verify this Token with Fortify?

**Comment by lucamartellucci** [comment]
Hi @rmhrisk,
I'm sorry! I accidentally posted this request. You can ignore it! 
Have a great day! 
Luca

**Comment by rmhrisk** [comment]
Luca, would love to support this just need a little info to do so.

**Comment by defacto64** [comment]
Hi Ryan,
Luca works in my team and we are aligned on this matter.
This "Add support" is useless since it relates to the same ATR reported in issue #294, and this latter - which you already took charge of - contains all the necessary details (supposedly).
You can safely ignore this issue.
Thank you.
