### ISSUE TITLE
Ronald Mesén CFIA

### ISSUE THREAD

**Issue by RonaldMesen** [PeculiarVentures/fortify#299]

**Comment by rmhrisk** [comment]
@RonaldMesen How can we help you?

**Comment by rmhrisk** [comment]
I suspect this was created in an accident, I am closing. Please open a new issue if help is needed.

**Comment by RonaldMesen** [comment]
May I answer in Spanish 

Ronald Mesén

**Comment by rmhrisk** [comment]
Sí, eso está bien.
