### ISSUE TITLE
Question about smart card compatibility

### ISSUE THREAD

**Issue by DBarthe** [PeculiarVentures/fortify#307]
Hello, thanks for this interesting project,

I have one question regarding smart card compatibility. It might not be the right place to ask such a question but I haven't found a mailing-list or so.

In the FAQ, it's written that all PKCS11-enabled smart cards should be OK. But then there is a table of supported smart cards.
If my smart card is absent of this table and I got a proper pkcs11 dll module provided by the card vendor, what does it take to make this card recognized by Fortify ?

Thanks in advance ! :)

**Comment by rmhrisk** [comment]
The project maintains a ATR to P11 mapping; if your device is not in that list currently we just need a little bit of information to add it.

For example:
* What is it's ATR
* What P11 library does it use?
* Where is that P11 library located in Windows/OSX/Linux
* What is the make and model of the card

Ryan

**Comment by DBarthe** [comment]
Then you will update https://fortifyapp.com/packages/card.jws, right?

In my case, I want to deploy fortify on computers with no internet access. Can I provide a custom cards.json locally, or from an URL of my choice ? or do I need to rebuild fortify from source with a few modifications?

Thank you so much!

**Comment by rmhrisk** [comment]
Yes we update this file.

it is possible to update card.json locally with that said if a card is supported we would like to make sure the JSON correctly reflects that.

The package should work fine without the internet; it contains a static "bootstrap" copy of the json.

**Comment by DBarthe** [comment]
Okay, thank you. I will try to manually update the bootstrap copy of the json and report any new functioning smart cards.
