### ISSUE TITLE
Add support for '3bff1800ff8131fe55006b02090200011101434e531131808e' token

### ISSUE THREAD

**Issue by lpinca** [PeculiarVentures/fortify#314]
Reader name: BIT4ID miniLector EVO 0
ATR: 3BFF1800FF8131FE55006B02090200011101434E531131808E

```js
{
   "cards": [{
   	"atr": "3BFF1800FF8131FE55006B02090200011101434E531131808E",
   	"name": "Token name",
   	"driver": "54C614B093FBD1E0FF39A69DAA95C4795854CA40"
   }],
   "drivers": [{
   	"id": "54C614B093FBD1E0FF39A69DAA95C4795854CA40",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3BFF1800FF8131FE55006B02090200011101434E531131808E](https://smartcard-atr.apdu.fr/parse?ATR=3BFF1800FF8131FE55006B02090200011101434E531131808E)

**Comment by lpinca** [comment]
This is a very old card so it is not very important to add support for it. Feel free to close.

**Comment by rmhrisk** [comment]
To add it would require more information about it.

It seems this may be “Infocamere CNS”, is that right?

What P11 do you use with it?

**Comment by lpinca** [comment]
Yes, it's possible.

![1](https://user-images.githubusercontent.com/1443911/80500755-db7c8480-896e-11ea-8402-b12e5e276bfb.png)
![2](https://user-images.githubusercontent.com/1443911/80500741-d6b7d080-896e-11ea-88cc-1475ac4d37a8.png)

**Comment by rmhrisk** [comment]
If you add this to your card.json I think it will work:

```
    {
      "atr": "3BFF1800FF8131FE55006B02090200011101434E531131808E",
      "name": "Infocamere CNS",
      "driver": "709F7FAFA0BF267C91C832E29AAED0D06AB22D92"
    },
```

Let us know if it does and we can update the official card.json

**Comment by lpinca** [comment]
Unfortunately it does not seem to work but again it is not a problem. Feel free to close.

![screenshot](https://user-images.githubusercontent.com/1443911/80570271-c8af9180-89fa-11ea-8c3b-4366a5723ce9.png)

```
{"message":"Provider:Token:Insert: reader:'BIT4ID miniLector EVO 0' name:'Infocamere CNS' atr:3bff1800ff8131fe55006b02090200011101434e531131808e","level":"info"}
{"message":"Provider:Token:Insert: Loading PKCS#11 library from C:\\WINDOWS\\System32\\bit4ipki.dll","level":"info"}
{"message":"Provider:Token:Insert: File C:\\WINDOWS\\System32\\bit4ipki.dll does not exist","level":"error"}
{"message":"Provider:Token:Insert: Loading PKCS#11 library from C:\\WINDOWS\\SysWOW64\\bit4ipki.dll","level":"info"}
{"message":"Error: Win32 error 193\n    at Error (native) PKCS11::Load:136\n    at Function.load (C:\\Program Files\\Fortify\\resources\\app.asar\\node_modules\\graphene-pk11\\build\\module.js:15:13)\n    at LocalProvider.onTokenInsert (C:\\Program Files\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:2177:43)\n    at CardWatcher.emit (events.js:194:13)\n    at PCSCWatcher.<anonymous> (C:\\Program Files\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:867:26)\n    at PCSCWatcher.emit (events.js:194:13)\n    at Timeout._onTimeout (C:\\Program Files\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:797:38)\n    at listOnTimeout (internal/timers.js:535:17)\n    at processTimers (internal/timers.js:479:7)","level":"error"}
{"message":"WebCryptoLocalError: C:\\WINDOWS\\SysWOW64\\bit4ipki.dll\n    at new WebCryptoLocalError (C:\\Program Files\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:340:23)\n    at LocalProvider.onTokenInsert (C:\\Program Files\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:2181:33)\n    at CardWatcher.emit (events.js:194:13)\n    at PCSCWatcher.<anonymous> (C:\\Program Files\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:867:26)\n    at PCSCWatcher.emit (events.js:194:13)\n    at Timeout._onTimeout (C:\\Program Files\\Fortify\\resources\\app.asar\\node_modules\\@webcrypto-local\\server\\build\\index.js:797:38)\n    at listOnTimeout (internal/timers.js:535:17)\n    at processTimers (internal/timers.js:479:7)","level":"error"}
```

**Comment by rmhrisk** [comment]
@microshine

**Comment by microshine** [comment]
`Win32 error 193` I saw such type of error today.
https://github.com/PeculiarVentures/fortify/issues/312#issuecomment-621198372

@lpinca do you have this error each time on Fortify start?

**Comment by lpinca** [comment]
@microshine yes.

**Comment by microshine** [comment]
@lpinca Please try to connect to your token using `graphene-pk11` module

```js
var graphene = require("graphene-pk11")

function main() {
  const lib = "C:\\WINDOWS\\SysWOW64\\bit4ipki.dll";

  const reader = graphene.Module.load(lib);

  reader.initialize();

  const slot = reader.getSlots(0);
  console.log(slot.getMechanisms().items_);
}

try {
  main();
  process.exit(0);
} catch (e) {
  console.error(e);
  process.exit(1);
}
```

**Comment by lpinca** [comment]
Will do it tomorrow as I have it in the office.

**Comment by lpinca** [comment]
@microshine I get the same error:

```
$ node index.js
Error: Win32 error 193
    at Error (native) PKCS11::Load:136
    at Function.load (C:\Users\luigi\Desktop\314\node_modules\graphene-pk11\build\module.js:15:13)
    at main (C:\Users\luigi\Desktop\314\index.js:8:34)
    at Object.<anonymous> (C:\Users\luigi\Desktop\314\index.js:17:3)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by microshine** [comment]
3BFF1800008131FE45006B04050100012101434E5310318059 uses the same lib. Am I right?
Does it work for that token?

**Comment by microshine** [comment]
@lpinca have you tried `%WINDIR/System32/bit4opki.dll` library?

**Comment by lpinca** [comment]
> 3BFF1800008131FE45006B04050100012101434E5310318059 uses the same lib. Am I right?

No, that one uses `bit4opki.dll`. This one uses `bit4ipki.dll`. As far as I can tell `o` stays for Oberthur and `i` for Incard.

If I try to use the `bit4id_opki` driver (the one that installs `bit4opki.dll`) the token is not even recognized.

**Comment by microshine** [comment]
please make one more test
 Use https://www.dependencywalker.com/ application to open your PKCS#11 library. Is it right PKCS#11 library?

![image](https://user-images.githubusercontent.com/7333669/80687600-36c78780-8ad3-11ea-8cde-1e2560b64248.png)

**Comment by lpinca** [comment]
I think so but I get some errors, perhaps it doesn't work on Windows 10?

![screenshot](https://user-images.githubusercontent.com/1443911/80690977-db47ca80-8acf-11ea-8bf4-8ffa1dd84102.png)

**Comment by microshine** [comment]
Maybe
```
ERROR_BAD_EXE_FORMAT

193 (0xC1)

%1 is not a valid Win32 application.
```

**Comment by lpinca** [comment]
Ok, I've managed to make it work by installing an updated version of the lib (1.3.5.0).

```js
graphene.Module.load('C:\\WINDOWS\\SysWOW64\\bit4ipki.dll');
```

still throws but

```js
graphene.Module.load('C:\\WINDOWS\\System32\\bit4ipki.dll');
```

works. Also tested in Fortify by adding an entry in `card.json` as described in https://github.com/PeculiarVentures/fortify/issues/314#issuecomment-620736157.

Thanks for the great support.

**Comment by microshine** [comment]
Thank you for your tests. I'll add this ATR to `cards.json` today

**Comment by microshine** [comment]
I updated cards.json and published it. Please restart Fortify application to get the latest version

Please let me know if it works

**Comment by lpinca** [comment]
Yes, it does.
