### ISSUE TITLE
Add support for '3bff1800008131fe45006b04050100012101434e5310318059' token

### ISSUE THREAD

**Issue by lpinca** [PeculiarVentures/fortify#317]
Reader name: BIT4ID miniLector EVO 0
ATR: 3BFF1800008131FE45006B04050100012101434E5310318059

```json
{
   "cards": [{
      "atr": "3BFF1800008131FE45006B04050100012101434E5310318059",
      "name": "National Service Card (CNS)",
      "driver": "F4460DEC1A2DB75426614475E0C814C3CA849857"
    }],
   "drivers": [{
      "id": "F4460DEC1A2DB75426614475E0C814C3CA849857",
      "name": "Bit4id Universal Middleware",
      "file": {
         "windows": {
            "x86": "%WINDIR/System32/bit4opki.dll",
            "x64": "%WINDIR/SysWOW64/bit4opki.dll"
         }
      }
   }]
}
```

[Smart card ATR parsing 3BFF1800008131FE45006B04050100012101434E5310318059](https://smartcard-atr.apdu.fr/parse?ATR=3BFF1800008131FE45006B04050100012101434E5310318059)

![1](https://user-images.githubusercontent.com/1443911/80580790-6bbcd700-8a0c-11ea-9c3e-aaae53fe49c4.png)
![2](https://user-images.githubusercontent.com/1443911/80580805-6f505e00-8a0c-11ea-9024-a408cdc40502.png)

Tested by adding the above snippet to `card.json`.

**Comment by microshine** [comment]
I updated the `card.json` file and published it. A new version of JSON file is 1.0.33.

Please restart your Fortify application to update your local file

**Comment by lpinca** [comment]
Thank you.
