### ISSUE TITLE
Error build - no such file or directory, open '/packages/fortify.pkgproj'

### ISSUE THREAD

**Issue by robsonalvz** [PeculiarVentures/fortify#321]
I have problems with the building of the app.
When i launch "npm run build", i get the following error:

Remove TMP directory build
Error: ENOENT: no such file or directory, open '/Users/robsonalvz/packages/fortify.pkgproj'
    at Object.openSync (fs.js:461:3)
    at Object.readFileSync (fs.js:363:35)

What is fortify.pkgproj?

Thaks so much.

**Comment by devilmightcry** [comment]
I am also encountering the same issue. 

<img width="581" alt="image" src="https://user-images.githubusercontent.com/50701776/82761236-e237d380-9e16-11ea-9a28-93f5f63c569e.png">

It seems osx.ts might require the change ?

**Comment by rmhrisk** [comment]
We’re working on a new release and intend to make the build process clearer as part of that. With that said, if your looking at forking I would Love to understand why and try to address that feedback.

The projects more impactful if we build an ecosystem around it vs many islands.

With that said @microshine will look at this issue Monday.

**Comment by donskov** [comment]
The Fortify packager moved to the private repo. Now command `npm run build` runs only compile the project to `.js`
