### ISSUE TITLE
Add support for '3b7f96000080318065b084565110120ffe829000' token

### ISSUE THREAD

**Issue by ramigabai** [PeculiarVentures/fortify#322]
Reader name: Gemalto PC Twin Reader
ATR: 3B7F96000080318065B084565110120FFE829000

```js
{
   "cards": [{
   	"atr": "3B7F96000080318065B084565110120FFE829000",
   	"name": "Token name",
   	"driver": "7E8A1238E28459E78E9F0C9E9D8DFC6E71C504BE"
   }],
   "drivers": [{
   	"id": "7E8A1238E28459E78E9F0C9E9D8DFC6E71C504BE",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
   }]
}
```

[Smart card ATR parsing 3B7F96000080318065B084565110120FFE829000](https://smartcard-atr.apdu.fr/parse?ATR=3B7F96000080318065B084565110120FFE829000)

**Comment by ramigabai** [comment]
Token name: Card #1B201C6106F96E94          
Token category: Hardware
Reader name: Gemalto PC Twin Reader
Serial number (PKCS#11): 1B201C6106F96E94
Free space (minimum estimated): 26963
Hardware version: 0.0
Firmware version: N/A
Card ID (GUID): 0x4600006500652A774600006500652A77
Product name: IDPrime MD 830-FIPS Rev B
Model: N/A
Card type: ID Prime MD
Applet Version: IDPrime Java Applet 4.3.5.D
Mask version: G286
Color: N/A
Supported key size: 2048 bits
Token Password: Present
Token Password retries remaining: 7
Maximum Token Password retries: 7
Administrator Password: Present
Administrator Password retries remaining: 5
Maximum administrator Password retries: 5
FIPS: FIPS 140-2 L2 initialized
Common Criteria (CC): CC EAL6+ certified on chip level
Sign padding on-board: Yes
RSM: N/A
ECC: Supported

**Comment by rmhrisk** [comment]
Closing as duple
