### ISSUE TITLE
Signing demo doesn't work.

### ISSUE THREAD

**Issue by ferikeem** [PeculiarVentures/fortify#331]
I was checking out [this signing demo](https://fortifyapp.com/developers/examples/signing), but it appears, it has a bug on this line:
`await signedData.sign(privateKey, 0, "sha-256");`
[fortifyapp.com-1593099546033.log](https://github.com/PeculiarVentures/fortify/files/4832384/fortifyapp.com-1593099546033.log)
Looks like algorithm isn't properly imported.

[Related SO question](https://stackoverflow.com/questions/62472562/sign-pdf-in-a-modern-browser-natively), if you have time, please check it out, as there seems to be a problem - for me at least - to 'convert' Fortify implementation of cerificates, etc. to a pkijs CMS signature.
Thank you.

**Comment by donskov** [comment]
Hello @ferikeem. Thank you for the issue!

We released the new Fortify app version today https://github.com/PeculiarVentures/fortify-web/releases/tag/v1.3.4. Please try to use it.

**Comment by ferikeem** [comment]
Hello @donskov,

Demo works fine with the updated app.

Thank you.

Also: loving the dark theme.

**Comment by donskov** [comment]
@ferikeem Ohh, thank you!
We have plans to add a switch for dark/light theme to app settings.
Stay tuned for more!
