### ISSUE TITLE
Token name in password/pin dialog

### ISSUE THREAD

**Issue by JanSlabon** [PeculiarVentures/fortify#333]
There's no token name in the password/pin dialog which makes it hard to guess for which token the password is requested.

![grafik](https://user-images.githubusercontent.com/12390057/85847892-87442400-b7a8-11ea-9803-be82878d2756.png)
This dialog is shown e.g. twice without any info for what token the password is requested.

Maybe #246 should be done before this one ;-)

**Comment by donskov** [comment]
As a solution, we can use a token label like a title:

![image](https://user-images.githubusercontent.com/9417251/85874711-bd4ecb80-b7db-11ea-8677-b301e1cc3aad.png)

@rmhrisk What do you think?

**Comment by JanSlabon** [comment]
Looks good :-) Is it the provider name or the token label (see #246 for some more details)?

**Comment by rmhrisk** [comment]
I believe and serial.

**Comment by donskov** [comment]
Resolved
