### ISSUE TITLE
Update/Installation issue 1.3.4 (Windows 10 Pro/x64)

### ISSUE THREAD

**Issue by JanSlabon** [PeculiarVentures/fortify#336]
We had following issue/strange behaviour when updating to the latest version (1.3.4):

1. The installation dialog ends with "Launch Fortify". We checked the checkbox and clicked "Finish".
2. Fortify didn't start.
3. We tried to start Fortify through the Windows Startmenu - we couldn't find Fortify at all.
4. We checked "C:\Program Files\Fortify" and didn't found any executable (fortify.exe was missing)
5. We re-started the installation (I'm not sure if it ends with the same "Launch Fortify" question?)
6. The file "C:\Program Files\Fortify\fortify.exe" was there and we were able to start Fortify.

**Comment by donskov** [comment]
@JanSlabon Could you try to use the new version from https://fortifyapp.com/#download_app?

**Comment by JanSlabon** [comment]
Last update went well, thanks!
