### ISSUE TITLE
Installation in linux is broken

### ISSUE THREAD

**Issue by pkarakal** [PeculiarVentures/fortify#339]
Installing fortify for development reasons in a linux machine isn't possible since [65579c1cce321f8e84ab5dd7ef3ae4cf05d4707c](https://github.com/PeculiarVentures/fortify/commit/65579c1cce321f8e84ab5dd7ef3ae4cf05d4707c). 

Is it something you're working on?

**Comment by rmhrisk** [comment]
@microshine I have had several reports of this any insights you can offer?

**Comment by microshine** [comment]
Sorry. It's my fail. I updated the script for Linux. It must work now

@pkarakal Please test it

**Comment by pkarakal** [comment]
I can confirm that the issue is resolved. The post install script completes successfully.
