### ISSUE TITLE
Add support for '3bdf18ff8191fe1fc30031b8640c01ecc173940180829000b3' token

### ISSUE THREAD

**Issue by YenderCV** [PeculiarVentures/fortify#359]
<img width="667" alt="Captura de Pantalla 2020-09-16 a la(s) 19 36 37" src="https://user-images.githubusercontent.com/70548256/93409508-4a8e4300-f854-11ea-8b67-aa941a1aab99.png">
Reader name: Bit4id miniLector-s
ATR: 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3

```js
{
   "cards": [{
   	"atr": "3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3",
   	"name": "Token name",
   	"driver": "EB1E2F85F2EE237953B971EA35C778085E5AE8C4"
   }],
   "drivers": [{
   	"id": "EB1E2F85F2EE237953B971EA35C778085E5AE8C4",
   	"name": "Driver name",
   	"file": {
   		"windows": "path/to/pkcs11.dll",
   		"osx": "path/to/pkcs11.dylib"
   	}
<img width="1651" alt="Captura de Pantalla 2020-09-16 a la(s) 19 38 28" src="https://user-images.githubusercontent.com/70548256/93409535-57129b80-f854-11ea-9aff-76a924e77c05.png">

   }]
}
```

[Smart card ATR parsing 3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3](https://smartcard-atr.apdu.fr/parse?ATR=3BDF18FF8191FE1FC30031B8640C01ECC173940180829000B3)

**Comment by YenderCV** [comment]
Hola, Fortify no reconoce mi certificado, por lo que no puedo ingresar a la siguiente plataforma https://sso.cfia.or.cr/sso/?IdSystem=1
AYUDA por favor

**Comment by rmhrisk** [comment]
¿Puede activar el registro, intentar iniciar sesión y luego enviarnos el registro?

Can you turn on logging, try to login, and then send us the log?

**Comment by YenderCV** [comment]
Hola, no entiendo mucho de esto, a que se refiere con activar registro?

**Comment by donskov** [comment]
Closing as a dupe of https://github.com/PeculiarVentures/fortify/issues/372
