### ISSUE TITLE
How to build installers?

### ISSUE THREAD

**Issue by bserrang** [PeculiarVentures/fortify#362]
Hi. 
I would like to generate the installables of the application but I do not see in the documentation how to do it. 
Can you help me?
Thanks in advance!

Hola. 
Me gustaría generar los instalables de la aplicación pero no veo en la documentación como hacerlo. 
¿Me podéis ayudar?
!Gracias de antemano!

**Comment by donskov** [comment]
Hello @bserrang. 

You should build the applications using the command `npm run build` and pack it using https://github.com/electron/electron-packager (or use another solution for creating installer).

We will prepare documentation of how to do it.

Thanks!

**Comment by rmhrisk** [comment]
@bserrang is there some missing functionality or something we can help within our distribution that would remove the need to build your own version?

**Comment by bserrang** [comment]
Thanks for answering so quickly!
I would need to make some changes. The most difficult is to make the component aware of the modifications made to the certificates from outside the application.
Could you help me?
Thanks again!

Gracias por contestar tan rápido! 
Necesitaría realizar algunos cambios. El más difícil consiste en hacer que el componente se de cuenta de las modificaciones realizadas en los certificados desde fuera de la aplicación.
¿Podríais ayudarme?
¡Gracias de nuevo!

**Comment by rmhrisk** [comment]
Can you describe in more detail what you are looking to do?

**Comment by bserrang** [comment]
Hi.

For example:
-Start Fortify and see the list with your certificates from the web component.
-Now, without using Fortify, look for one of those certificates on your computer and delete it.
-The deleted certificate is still on the Fortify certificate list and I wish it had been updated.

I don't know if it would be possible to correct this problem, if there is an event when there are changes in the certificates from outside the application.

Thanks in advance.

hola.

Por ejemplo:
-Arrancas Fortify y ves la lista con tus certificados desde el componente web.
-Ahora, sin usar Fortify, buscas en tu equipo uno de esos certificados y lo eliminas.
-El certificado eliminado sigue estando en la lista de certificados de Fortify y me gustaría que se hubiera actualizado.

No se si sería posible corregir este problema, si existe algún evento cuando haya cambios en los certificados desde fuera de la aplicación.

Gracias de antemano.

**Comment by rmhrisk** [comment]
This would require the web components to do a periodic poll. This is doable. Why don’t you create a feature request bug with that description and we will look into adding it to the roadmap.

**Comment by bserrang** [comment]
Hello again.

I have generated the executable but when I try to see my certificates the following message appears and it does not show them.
![image](https://user-images.githubusercontent.com/69515486/95983964-c1eace80-0e22-11eb-8ab1-ae0af31f68a8.png)

Do you know why this happens?

Thanks in advance!


Hola de nuevo.

He generado el ejecutable pero cuando intento ver mis certificados me aparece el siguiente mensaje y no los muestra.

¿Sabéis por que ocurre esto?

¡Gracias de antemano!

**Comment by rmhrisk** [comment]
Does it happen with the official distribution?

Can you file an issue about this instead of re-using this one?

Can you include the log associated with when you insert the card?

**Comment by donskov** [comment]
Hello @bserrang,

Please provide more information:
1. What Fortify version you use?
2. What web example you use?
3. Could you provide Fortify logs (like @rmhrisk said)?

Thanks.

**Comment by bserrang** [comment]
hello @donskov,

1. I use de last version

1.

**Comment by bserrang** [comment]
Hello @donskov 

I have simply generated an executable from the master branch of the project. Then, any example component that you have on the web returns the message that I have indicated. However, with the downloaded desktop application it does not happen.

What could be due to?

Thanks in advance!

**Comment by donskov** [comment]
@bserrang Executable version from the master or downloaded version must work the same. Could you share Fortify logs?

**Comment by bserrang** [comment]
@donskov Sorry for my inexperience in this regard. 

How do I get the log of the application generated by me if what I am using is the executable?

**Comment by donskov** [comment]
@bserrang 
1. Go to Fortify `Settings`.
2. Got to the `Logging` section.
![image](https://user-images.githubusercontent.com/9417251/96111515-f4133380-0ee9-11eb-9fc6-f89387bc2f23.png)
3. Enable logs if disabled.
4. Run a web example with the error.
5. Go to `Settings` and click `View logs`.
6. Copy and send me a text (better to use my email dmitriy.donskov@peculiarventures.com).

Thanks.

**Comment by kmb64** [comment]
Hi guys,

I'm trying to build an installation of fortify via https://github.com/electron/electron-packager as mentioned above but running into some issues.

I have been trying to build a windows version of the appliation by running `electron-packager .` within the fortify root directory after running `npm run build`.  This produces the following output:

![windows-output](https://user-images.githubusercontent.com/1438484/98193286-ea24a380-1f70-11eb-9e44-54a4372c5d5b.jpg)

But when running I see this error: 

![windows-error](https://user-images.githubusercontent.com/1438484/98193299-f6a8fc00-1f70-11eb-9e0c-880ab1decd47.jpg)

I got past this by manually copy and pasting the `pvpkcs11.dll` file over from the fortify source code directory but I'm not sure this is the ideal thing to do. The application will run but it is different to what I would expect and what I see when when running in development mode `npm run start`/`electron .`

Are you able to provide more specific instructions about how to package fortify correctly?

Thank you
