### ISSUE TITLE
Problem installing on macOS Big Sur 11.0.1

### ISSUE THREAD

**Issue by silvaartur** [PeculiarVentures/fortify#376]
Hello!

Installer doesn't recognize the correct version on macOS Big Sur Version 11.0.1 Beta.

<img width="759" alt="Captura de Tela 2020-11-02 às 06 02 41" src="https://user-images.githubusercontent.com/12688324/97850052-428a4580-1cd2-11eb-831c-4843fa6b5b15.png">

<img width="203" alt="Captura de Tela 2020-11-02 às 06 03 08" src="https://user-images.githubusercontent.com/12688324/97850064-45853600-1cd2-11eb-804f-1e43f4ddbdde.png">

**Comment by donskov** [comment]
Hello @silvaartur . Thank you for the response.

Could you run `sw_vers` command on your terminal?

My response is:
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2
```

**Comment by donskov** [comment]
@silvaartur Could you try to install [new](https://github.com/PeculiarVentures/fortify/releases/tag/1.5.0-alpha) version?

**Comment by donskov** [comment]
Works for me on `11.0.1`

![image](https://user-images.githubusercontent.com/9417251/101164835-5103ae00-363e-11eb-973b-1d85f5f8dbec.png)
