### ISSUE TITLE
Disabling alert message about availability of updates

### ISSUE THREAD

**Issue by defacto64** [PeculiarVentures/fortify#391]
Hi,

in corporate environments, where the distribution and installation of software packages is often times centrally managed (e.g. by Microsoft SCCM or similar systems), it is essentially useless and annoying for end users to receive those alerts, shown by the Fortify app, about the availability of updates. In such environments, where users cannot install anything by themselves, it would be good to be able to inhibit/disable those alerts. Is this possible, in some way or another?

**Comment by rmhrisk** [comment]
We will investigate this; its a tough issue in that security updates need to be deployed; we may want to come up with a model to enable a direct relationship with those types of customers to ensure they are made aware of security issues.

**Comment by microshine** [comment]
@defacto64 The current version doesn't allow to disable that dialog using UI. I think we will publish the patch in a week

It's possible to do it manually using `~/.fortify/dialog.json` file. Create that file (if it doesn't exist) or add 'question.update.new'

### dialog.json
```js
[
  "question.update.new"
]
```

### fortify.log
```
info: [update]  Check for new update
info: [update]  New version was found
info: [windows]  Don't show dialog It's disabled {"id":"question.update.new"}
```

**Comment by defacto64** [comment]
Thank you, we'll try this metod.

Another issue stems from the fact that Fortify 1.7.0 initially prompts user for enabling analytics. Also this is unwanted in a corporate environment where the behavior of software packages installed on user PCs must be strictly under control of the department that centrally manages SW distribution. In general, in such environments, it's unwanted that software packages installed on user PCs show any kind of pop-ups to end users, except those that are part of the normal usage flows, if that behaviour cannot be disabled centrally, someway or another. So it would be good if also the "enable analytics" dialog could be disabled. Can this be done, Stepan, via the same dialog.json file?

**Comment by microshine** [comment]
> Can this be done, Stepan, via the same dialog.json file?

It's possible. Use `question.telemetry.enable` identier

**Comment by defacto64** [comment]
So for disabling both pop-ups the dialog.json should be like this?
```
[
  "question.update.new",
  "question.telemetry.enable"
]
```

**Comment by microshine** [comment]
that's right

**Comment by defacto64** [comment]
Thank you Stepan.

**Comment by donskov** [comment]
Enhancement moved to https://github.com/PeculiarVentures/fortify/issues/392
