### ISSUE TITLE
Questions about API

### ISSUE THREAD

**Issue by rossinicolas** [PeculiarVentures/fortify#418]
Hello, i'm traying to made a React App using Nextjs that has a Provider Select List, a Certificates Select List and a Textbox to Sign that info, similar to example5.html but using react component and Fortify API. Could you tell me how can i do it?
Thanks in advance.

**Comment by rmhrisk** [comment]
Have you seen https://fortifyapp.com/examples/signing ?

**Comment by donskov** [comment]
Hello @rossinicolas,

You can try to use the Fortify [web-component ](https://fortifyapp.com/docs/installation/web-component) or get the code from `example5.html` and move it to the React.

**Comment by rossinicolas** [comment]
> Have you seen https://fortifyapp.com/examples/signing ?

Yes, but the exaple in the site is using html like example5.html, not React.

**Comment by rmhrisk** [comment]
You will have to ask a more concrete question. We can’t write the code for you.
