### ISSUE TITLE
Error on landing page r.where(...).get is not a function

### ISSUE THREAD

**Issue by Matx99** [PeculiarVentures/fortify#430]
After installing Fortify and going on landing page, I get this error:
![image](https://user-images.githubusercontent.com/44765946/131864690-c593f245-899b-4246-bdb9-e57e2055bd18.png)

Log file in .fortify/fortify.log is empty

I'm on Ubuntu 20.04, should I get a specific dependency?

**Comment by donskov** [comment]
Hello @pkix. Thank you for the bug report.

Could you please attach the screenshot from the browser console? This will help to investigate what is happened.

**Comment by Matx99** [comment]
![image](https://user-images.githubusercontent.com/44765946/132017523-92cefad9-8a6a-46e7-9c2c-03d4c9639c35.png)
![image](https://user-images.githubusercontent.com/44765946/132017571-72590ac4-5c58-44c6-aa57-5470b22b6409.png)

**Comment by donskov** [comment]
Thank you. I made some changes and shipped it to https://tools.fortifyapp.com/. 

Could you try again please?

**Comment by Matx99** [comment]
I still have the same error

**Comment by donskov** [comment]
Thank you. Please share your console again and expand `PROVIDER:SET_LIST` object to show more details.

Best regards.

**Comment by Matx99** [comment]
![image](https://user-images.githubusercontent.com/44765946/132182268-79a2910f-c9f1-4e0f-8eca-13994301fec6.png)

**Comment by donskov** [comment]
@Matx99 Hello. Sorry for my not-clear request. I want to see a `list` data structure.

For example my list:
![image](https://user-images.githubusercontent.com/9417251/132195973-9987a4a1-bbf5-4357-983e-75db939f5e1b.png)

Thanks!

**Comment by Matx99** [comment]
![image](https://user-images.githubusercontent.com/44765946/132228040-2cfed2da-22e6-463b-911b-4afa1864516e.png)

**Comment by donskov** [comment]
@Matx99 I think the bug was found and resolved. Please try to use it again.

The problem is related to Fortify. Now, Fortify can work only with a single NSS provider. So, we use the first provider from your `.fortfiy/config.json` file.

**Comment by Matx99** [comment]
It works, thank you!
