### ISSUE TITLE
Unable to use custom driver

### ISSUE THREAD

**Issue by Ottunger** [PeculiarVentures/fortify#439]
Hi,

I have a smart card with a custom non-complete PKCS11 driver for it.
I have added its configuration to the card.json file:
```
{
		"id": "3B9D188131FC358031C0694D54434F5373020505D3",
		"name": "MCARD",
		"file": {
			"windows": "C:/Program Files/ONECI/mcard/mcard-pkcs11.dll"
		}
	}
```

If I use the same driver for pkcs11-tool, it works flawlessly:
```
"C:\Program Files\OpenSC Project\OpenSC\tools\pkcs11-tool.exe" -M --module="C:\Program Files\ONECI\mcard\mcard-pkcs11.dll"
Using slot 0 with a present token (0x0)
Supported mechanisms:
  ECDSA, keySize={256,384}, hw, sign
  ECDSA-SHA256, keySize={256,256}, hw, sign
  ECDSA-SHA384, keySize={384,384}, hw, sign
```

But when I access tools.fortifyapp.com, I can see the token, but no certificate on it. This is happening on a windows 10 x64.
On a windows 8.1 x64, the tools.fortifyapp.com prompts for the PIN of the card and then can display certificates.

Is there anything I could investigate to understand why card is not unlocked?
The fortify.log remains empty.

Side note: I created https://github.com/PeculiarVentures/x509/issues/11 about the certificates which are on this card. I will finally be able to test the signature after I can access the private keys.

Thanks,

**Comment by Ottunger** [comment]
Intesrting lines are here on win10:

```
{"source":"pcsc","reader":"OMNIKEY AG Smart Card Reader USB 0","atr":"3b9d188131fc358031c0694d54434f5373020505d3","level":"info","message":"New token was added to the reader","timestamp":"2021-10-14T15:06:20.450Z"}
{"source":"pcsc","reader":"OMNIKEY AG Smart Card Reader USB 0","atr":"3b9d188131fc358031c0694d54434f5373020505d3","level":"info","message":"New token was added to the reader","timestamp":"2021-10-14T15:06:20.453Z"}
{"source":"server-api","atr":"3b9d188131fc358031c0694d54434f5373020505d3","reader":"OMNIKEY AG Smart Card Reader USB 0","level":"info","message":"cardReader/insert","timestamp":"2021-10-14T15:06:21.456Z"}
{"source":"card-watcher","reader":{"name":"OMNIKEY AG Smart Card Reader USB 0","connected":false,"_events":{},"_eventsCount":4,"state":1114530},"atr":"3b9d188131fc358031c0694d54434f5373020505d3","level":"info","message":"Cannot get Card config. Use pvpkcs11 SmartCard slot","timestamp":"2021-10-14T15:06:21.471Z"}
{"source":"provider","reader":"OMNIKEY AG Smart Card Reader USB 0","name":"SCard Windows API","atr":"3b9d188131fc358031c0694d54434f5373020505d3","level":"info","message":"Token was added to the reader","timestamp":"2021-10-14T15:06:21.474Z"}
{"source":"provider","library":"C:\\Program Files\\Fortify\\pvpkcs11.dll","level":"info","message":"Loading PKCS#11 library","timestamp":"2021-10-14T15:06:21.477Z"}
{"source":"provider","slots":2,"level":"info","message":"Looking for slot","timestamp":"2021-10-14T15:06:22.509Z"}
{"source":"provider","level":"info","message":"Use default TemplateBuilder","timestamp":"2021-10-14T15:06:22.681Z"}
{"source":"provider","library":"C:\\Program Files\\Fortify\\pvpkcs11.dll","manufacturerId":"Module","cryptokiVersion":{"major":2,"minor":30},"libraryVersion":{"major":1,"minor":1},"firmwareVersion":{"major":0,"minor":1},"level":"info","message":"PKCS#11 library information","timestamp":"2021-10-14T15:06:22.684Z"}
{"source":"provider","id":"cecf410cc329cb5e9f88892cb86349cbba9ab55ff86fd7d9b11fb96851afbd4f","library":"C:\\Program Files\\Fortify\\pvpkcs11.dll","name":"SCard Windows API","reader":"OMNIKEY AG Smart Card Reader USB 0","level":"info","message":"Crypto provider was added to the list","timestamp":"2021-10-14T15:06:22.687Z"}
{"source":"provider-service","added":1,"removed":0,"level":"info","message":"Amount of tokens was changed","timestamp":"2021-10-14T15:06:22.689Z"}
```

Is the correct library referenced in card.json loaded? What do you think?

**Comment by microshine** [comment]
Please add your PKCS#11 module to `~/.fortify/config.json`

```json
{
  "cards": [
    {
      name: "OMNIKEY AG Smart Card",
      atr: "3b9d188131fc358031c0694d54434f5373020505d3",
      readOnly: false,
      libraries: [
        "C:/Program Files/ONECI/mcard/mcard-pkcs11.dll"
      ]
    }
  ]
}
```

**Comment by microshine** [comment]
`card.json` must work. I'm wondering why it doesn't. Could you share `card.json` changes you did?

I added `cards` option to `config.json` file to simplify the process of trying and adding new cards and providers to Fortify. The main problem of `card.json` usage is that when you've got a new update for `card.json` it rewrites the file and you lose your custom cards.

I think we need to improve our UI and allow Users to add cards or HSMs to `config.json` (maybe something like Mozilla does  in Firefox)

**Comment by Ottunger** [comment]
Hi @microshine @rmhrisk 
Do you know if there is a standard way to add the configuration changes automatically after installation?
Or can I ask you to officially support this ATR?

Thanks

**Comment by microshine** [comment]
Does https://github.com/PeculiarVentures/fortify/issues/439#issuecomment-944030958 work?

Does lib exist for Linux and MacOS?

I could add it to `craed.json` file and include it in the next Fortify build.

> Do you know if there is a standard way to add the configuration changes automatically after installation?

It's the file generated by Fortify application. You may create your own script for JSON file opening and editing.

**Comment by Ottunger** [comment]
Yes, editing the file works perfectly.

So, I should rewrap your MSI installer with a small script after installation? I guess the zip version cannot work that way, can it?

**Comment by microshine** [comment]
> So, I should rewrap your MSI installer with a small script after installation? I guess the zip version cannot work that way, can it?

I think it's impossible.

**Comment by rmhrisk** [comment]
File a bug to support your card and provide all the associated details.

**Comment by microshine** [comment]
@Ottunger We published the new version of Fortify today `v1.8.3`. Also we published the new version of `card.json`.

Please restart the Fortify app to update your `card.json`. It includes MCARD config

**Comment by Ottunger** [comment]
Thank you so much, I will update and try.
By the way, the inno setup packaging was a temporarily working solution

**Comment by Ottunger** [comment]
Hi guys,

I just tested and nice job, no more need to change custom config for me!
So you know, we do not support mac/linux, but we do have both x32 and x64 drivers.

x64: "%PROGRAMFILES/ONECI/mcard/mcard-pkcs11.dll" (correct)
x32: "%PROGRAMFILES(x86)/ONECI/mcard/mcard-pkcs11.dll" (should be)

**Comment by rmhrisk** [comment]
@microshine please confirm card.json contains both.

@Ottunger do you have a link for the card details I can look at?

**Comment by Ottunger** [comment]
I checked card.json contains only one.

What do you call card details? But in any case, I'm afraid not.

**Comment by rmhrisk** [comment]
@Ottunger I am curious what the capabilities of the card are, what product you are using it with, etc.

**Comment by microshine** [comment]
In process. Adding x86 path to `card.json` and publishing module

**Comment by Ottunger** [comment]
Happy to have a chat but I don't have much info myself, and was told not to disclose too much on Github publicly.
Feel free to reach out to me by email greg.mathonet@gmail.com for some intel.

**Comment by microshine** [comment]
@donskov I fixed and published `@webcrypto-local/cards`. Could you sign and publish it?

**Comment by donskov** [comment]
@Ottunger `cards.json` updated. You need only restart your Fortify.
