### ISSUE TITLE
Unclear Instructions on how to see token's certificate

### ISSUE THREAD

**Issue by blauer4** [PeculiarVentures/fortify#442]
Hello, 
I'm trying to use this library to sign PDF's Through setasign-signer library. The problem is that it is very unclear how to get certificates from usb tokens. 
What do I need to do? Because when I insert the usb Token into my computer I don't see any certificate pop-up into fortify. Do I need to poll the device in order to search for the certificate? Or is the token not supported? 

The token is an [Aruba key](https://www.pec.it/cns-token.aspx)(site is in Italian), and usually you use it with it's own proprietary software. 

Could you explain how you read the certificate's from tokens in general? Because I cannot find any reference online about fortify and reading certificate from usb tokens.

Thanks for the reply,
Lollixzc

**Comment by rmhrisk** [comment]
Please attach fortify  logs including when you inserted the token and tried to view the certificate with the included tools app.
