### ISSUE TITLE
Clear PIN cache

### ISSUE THREAD

**Issue by Ottunger** [PeculiarVentures/fortify#443]
Hello,
I have a requirement to clear the PIN cache been any two signature sessions.
Is there any standard way to clear the cache from the JavaScript components?
I'm looking for a provider.certStorage.clearCache() and provider.keyStorage.clearCache() or something alike.

**Comment by microshine** [comment]
Try `crypto.logout()`. It must close PKCS#11 session

**Comment by Ottunger** [comment]
I will try and let you know.
What you call `crypto` is `provider` right in your signing examples? (/examples/signing)

**Comment by microshine** [comment]
`crypto` is `provider` in your example.

It's an instance of `CryptoProvider`

**Comment by Ottunger** [comment]
I confirm it works for this purpose.
