### ISSUE TITLE
PIN entered not shown until window moves

### ISSUE THREAD

**Issue by Ottunger** [PeculiarVentures/fortify#453]
Maybe hard to see on attached video: while entering card PIN, the input does not show "dots" for each number types, only after window is moved do we see the dots. This may be confusing for user who may think nothing is being entered.

https://user-images.githubusercontent.com/3816312/140700985-356d450a-0f6a-4028-8075-d0ef8a2c7c80.mp4

**Comment by donskov** [comment]
@Ottunger Thanks for the report. You are right and we managed to reproduce it on our own.

We will try to fix it as soon as possible.

**Comment by donskov** [comment]
@Ottunger Could you share your machine information (memory, CPU, etc.)?

We reproduced this bug only on machines with low resources. When we increase resources - the bug disappears.

**Comment by Ottunger** [comment]
Sometimes I see it too myself, usually when I just started Fortify.
The application does not seem to leak too much memory though.

I cannot investigate more than this unfortunately.

**Comment by donskov** [comment]
@Ottunger Please try to use the [updated](https://github.com/PeculiarVentures/fortify/releases/tag/refs%2Fheads%2Fcanary) version.

**Comment by Ottunger** [comment]
Hi @donskov , I confirm it seems fixed to me :)

**Comment by donskov** [comment]
Thanks, @Ottunger. I will update the `1.8.3` release with this fix.
