### ISSUE TITLE
Error: listen EACCES permission denied 

### ISSUE THREAD

**Issue by Lollixzc** [PeculiarVentures/fortify#458]
All of a sudden fortify stopped working. It's not version dependant because I get this error on 1.8.2 and 1.8.3. The image describing the error is down below.

![image](https://user-images.githubusercontent.com/56732985/144669008-5ac6d41d-899d-409d-b9cb-7ad65bc2714a.png)

It seems that there is some kind of permission denied that I don't know how to grant.
Thanks in advance for the response

**Comment by microshine** [comment]
Could you check if there is no one more instance of Fortify application in processes?

**Comment by Lollixzc** [comment]
I have four instances on launching the app. This error appears on startup, and I'm sure there aren't any other instances running

![image](https://user-images.githubusercontent.com/56732985/144672225-6c70466f-1a8c-491e-8d44-b74593d254f2.png)

**Comment by rmhrisk** [comment]
If you reboot does the problem persist?

**Comment by Lollixzc** [comment]
> If you reboot does the problem persist?

The problem doesn't persist if I reboo. 😆 Classic IT crowd fix. Usually that problem means that there is another program that is blocking the localhost port? If I find this bug Again should I try to see what program is conflicting with it?
Thanks for the reply, I close the issue as it seems that the problem is gone.
