### ISSUE TITLE
Fortify Crashing on macOS version 12.3.1

### ISSUE THREAD

**Issue by Tallesecs** [PeculiarVentures/fortify#489]
Hi folks,

Im opening fortify on a client's mac but it keeps crashing quickly.
I can't get the logs because it keeps closing so fast.
Already uninstalled and installed latest fortify version, but it keeps closing.

What can we do to solve that problem?

**Comment by microshine** [comment]
Hi

please update open and edit your `~/.fortify/config.json` file

Set `"logging": true` option

**Comment by alvesluc** [comment]
[fortify.log](https://github.com/PeculiarVentures/fortify/files/8710744/fortify.log)

**Comment by Tallesecs** [comment]
@microshine  We tried changing logging to true, but it is still closing 
theres a new log info about this:

# [fortify.log](https://github.com/PeculiarVentures/fortify/files/8710754/fortify.log)

**Comment by microshine** [comment]
Are you using SafeNET token?

**Comment by microshine** [comment]
What is your `SafeNET Autontication Client` app version?

I've got 10.8.29. It works fine. My prev version of SafeNET client crashed Fortify on RSA key generation

**Comment by microshine** [comment]
@Tallesecs Have you tried to install the latest version of `SafeNET Autontication Client`?

**Comment by Tallesecs** [comment]
We will try to do it today. We will feedback you ASAP

**Comment by Tallesecs** [comment]
Hello folks

@microshine @rmhrisk  we did install A1 Certificate now, and we´re not using SafeNET anymore.

Now fortify isnt detecting the certificate. AC Certisign RFB GS

What do you guys think it might be?

# [fortify.log](https://github.com/PeculiarVentures/fortify/files/8862191/fortify.log)

**Comment by Tallesecs** [comment]
@donskov mentioning you on this topic also, <3 thanks for helping

**Comment by donskov** [comment]
Hello, @Tallesecs. Do you use Fortify web-components?

**Comment by Tallesecs** [comment]
I think not we do use this code:

<script type="module" src="https://unpkg.com/@peculiar/fortify-webcomponents@2/dist/peculiar/peculiar.esm.js"></script>
<script nomodule src="https://unpkg.com/@peculiar/fortify-webcomponents@2/dist/peculiar/peculiar.js"></script>
<link rel="stylesheet" href="https://unpkg.com/@peculiar/fortify-webcomponents@2/dist/peculiar/peculiar.css">

**Comment by Tallesecs** [comment]
Yes, but not especifically through HTML
We do create by javascript follow this example: 
https://fortifyapp.com/examples/signing

We do not use the  part

**Comment by Tallesecs** [comment]
Hello folks, any updates on this matter?

**Comment by donskov** [comment]
@Tallesecs Signing example uses the `onlyWithPrivateKey` filter. Maybe your certificate doesn't have a private key and the component hides it. Please try https://codepen.io/donskov/pen/RwWMPjG.

**Comment by Tallesecs** [comment]
@donskov Hi, we dont use this filter. Did you check the logs?

# [fortify (2).log](https://github.com/PeculiarVentures/fortify/files/8892114/fortify.2.log)

**Comment by donskov** [comment]
@Tallesecs Based on your logs I see that Fortify didn't detect `AC Certisign RFB G5` certificate. Are you sure you have it on your token?

**Comment by Tallesecs** [comment]
Yes, print follows:

![44A66BF7-3208-4B37-90BC-833FF80D3367](https://user-images.githubusercontent.com/48157227/173565637-e990c5ed-55cc-47b8-b1c0-d3fd4454b21c.jpeg)

**Comment by microshine** [comment]
It's very interesting. Is it possible to test this token via Remote Desktop?

I'd like to run NodeJS script with graphene-pk11 module to list all available objects on token. It must help to understand why certificate is not showing

**Comment by Tallesecs** [comment]
@microshine Can you give me access to this script?Since it is on a client mac, i need schedule a meeting with him to run. It would be faster to give you a feedback

**Comment by microshine** [comment]
I'll prepare script and instruction how to run it

**Comment by microshine** [comment]
Steps to run NodeJS script

package.json
```json
{
  "name": "fortify-issue-489",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "type": "module",
  "dependencies": {
    "@peculiar/x509": "^1.7.0",
    "graphene-pk11": "^2.3.0"
  },
  "devDependencies": {
    "@types/node": "^17.0.43"
  }
}
```

index.js
```js
import * as graphene from "graphene-pk11";
import * as x509 from "@peculiar/x509";

// !NOTE Update lib and pin variables for your token
const lib = "/usr/local/lib/softhsm/libsofthsm2.so";
const pin = "12345";

function logProp(name, value, pad = 0) {
  console.log(`${"".padEnd(2 * pad, " ")}${`${name}:`.padEnd(14, " ")} ${value}`);
}

async function main() {
  const token = graphene.Module.load(lib);

  token.initialize();

  try {

    const slots = token.getSlots(true);
    for (const slot of slots) {
      logProp("slot", slot.slotDescription);
      const session = slot.open(graphene.SessionFlag.SERIAL_SESSION);

      session.login(pin, graphene.UserType.USER);

      const list = session.find();
      for (const item of list) {
        logProp("class", graphene.ObjectClass[item.class], 1);
        const itemType = item.toType();
        try {
          if (itemType instanceof graphene.Certificate) {
            logProp("type", graphene.CertificateType[itemType.type], 2);
            logProp("category", graphene.CertificateCategory[itemType.category], 2);
            if (itemType instanceof graphene.X509Certificate) {
              logProp("id", itemType.id.toString("hex"), 3);
              
              // Parse x509 certificate
              const x509Cert = new x509.X509Certificate(itemType.value);
              logProp("serial", x509Cert.serialNumber, 3);
              logProp("subject", x509Cert.subject, 3);
              logProp("issuer", x509Cert.issuer, 3);
              logProp("notAfter", x509Cert.notAfter.toISOString(), 3);
            }
          } else if (itemType instanceof graphene.Data) {
            logProp("application", itemType.application, 2);
            logProp("object id", itemType.objectId.toString("hex"), 2);
          } else if (itemType instanceof graphene.PrivateKey) {
            logProp("id", itemType.id.toString("hex"), 2);
            logProp("type", graphene.KeyType[itemType.type], 2);
          } else if (itemType instanceof graphene.PublicKey) {
            logProp("id", itemType.id.toString("hex"), 2);
            logProp("type", graphene.KeyType[itemType.type], 2);
          }
        } catch (e) {
          console.error(`Error: Cannot read object. ${e.message}`)
        }
      }
    }
  } catch (e) {
    console.error(`Error: ${e.message}`);
  }

  token.close();
}

main().catch(e => {
  console.error(e);
  process.exit(1);
})
```

### Install required env

Download and install NodeJS LTS version from https://nodejs.org

### Create an empty folder and copy index.js and package.json into it

Update `index.js` file. You need to change `lib` and `pin` constants for your token.

### Run terminal

Open folder with script files
```sh
> cd /folder/with/script/files
```

Install NPM modules
```sh
> npm install
```

Run script
```sh
> node index.js
```

### Output example
```
slot:          SoftHSM slot ID 0x62777142
  class:         PUBLIC_KEY
    id:            ad9ab91a58980b80022447b2f15ed473
    type:          EC
  class:         PRIVATE_KEY
    id:            ad9ab91a58980b80022447b2f15ed473
    type:          EC
  class:         CERTIFICATE
    type:          X_509
    category:      Unspecified
      id:            ad9ab91a58980b80022447b2f15ed473
      serial:        01
      subject:       CN=Test cert
      issuer:        CN=Test cert
      notAfter:      2023-06-15T08:54:53.000Z
```

**Comment by Tallesecs** [comment]
@microshine what is lib and pin for my token?

"// !NOTE Update lib and pin variables for your token"

**Comment by microshine** [comment]
From the log you've shared I see that Fortify uses 3 PKCS#11 libraries
- `libpvpkcs11.dylib` internal module for `MacOS Crypto`
- `libsoftokn3.dylib` internal module for `NSS`
- `libeTPkcs11.dylib` external lib for SafeNET tokens

You screenshot with the certificate `AC Certisign RFB G5` shows that it's in KeyChain. Is it User KeyChain or Smart Card KeyChain?
Fortify uses libpvpkcs11.dylib lib to get certificates from KeyChain and it uses User KeyChain only. And if your `AC Certisign RFB G5` is in another KeyChain it could be a reason why you don't see it in Fortify app.

> what is lib and pin for my token?

The same PIN which you used for `softhsm2-util --init-token` command on softhsm installation
