### ISSUE TITLE
Fortify  not signed or whitelisted Windows

### ISSUE THREAD

**Issue by Tallesecs** [PeculiarVentures/fortify#491]
Windows Defender Smart Screen, keeps protecting fortify-win23-x86

Any updates on Fortify Authenticode signed or be whitelisted in the Windows Enviroment ?

Thanks in advance!

![image](https://user-images.githubusercontent.com/48157227/168281563-c1163cc4-a519-4cb4-afe7-551965597f3c.png)

**Comment by rmhrisk** [comment]
New release is signed

**Comment by Tallesecs** [comment]
Hello, we did try to install 1.8.4 version and windows still protecting

![image](https://user-images.githubusercontent.com/48157227/176183596-0f4fcaa7-e4b6-45ea-b1e4-9fd142c3faeb.png)

**Comment by rmhrisk** [comment]
Will resign with EV, might help. That said you can still whitelist within your enterprise.

**Comment by microshine** [comment]
@Tallesecs The latest version of Fortify@1.8.4 is signed. Please check it out

**Comment by Tallesecs** [comment]
Hello guys!

How are you?

Seems like the problem persists

What are we doing wrong?

![IMG_8599](https://user-images.githubusercontent.com/48157227/186904928-1ab1a596-e387-4b6e-aa41-d247fff62af0.jpg)

**Comment by rmhrisk** [comment]
Please download the package again.

**Comment by Tallesecs** [comment]
Ok. Just did it, still not working.

![image](https://user-images.githubusercontent.com/48157227/187028203-9eead603-0a8e-4172-aaac-5da0670bf219.png)

**Comment by Tallesecs** [comment]
Hello! Am i doing something wrong?

Thanks

**Comment by rmhrisk** [comment]
It is signed, if you look at the signature on the file it is signed with an EV certificate. 

As has been stated before you can allow list the package within enterprise. We can’t control the safe browsing behavior beyond EV signing, which we have done.
