### ISSUE TITLE
Fortify does not call callback events

### ISSUE THREAD

**Issue by cmjunior** [PeculiarVentures/fortify#500]
After a while working fine, fortify stopped call the registered callback functions. I'm already tried on [examples](https://fortifyapp.com/examples/signing) provided, so nothing happens when I click on "Cancel" or "Continue" buttons.

It's a windows environment.
Nothing on browser's console either.

The error I'd noticed on logs was:
`{"source":"server","error":"CKR_USER_TYPE_INVALID","level":"error","message":"Server event error","timestamp":"2022-06-06T14:38:54.103Z"}`

One thing I've noticed is that the token's passwords is called a few times, when the fortify component is mounted, about three times, sometimes two.

**Comment by donskov** [comment]
Hello @cmjunior. Do you mean callbacks from `peculiar-fortify-certificates` web-component?

**Comment by cmjunior** [comment]
@donskov that was it! I was using the old ones. Thanks a lot!
