### ISSUE TITLE
Getting full certificate

### ISSUE THREAD

**Issue by Danbeac** [PeculiarVentures/fortify#502]
Hi devs
Someone can help me or indicates if it exists some way using Fortify I can extract certificate or PEM with the certificate and private Key all together?

I already extract the certificate but when I create the object X509Certificate2 in my backend this indicates doesn't have the private key.
I would appreciate the help.

Thanks

**Comment by rmhrisk** [comment]
Fortify does not enable private key export. You can use PKI.js with Webcrypto to generate in browser exportable private keys. There is a PKCS12 example
there specifically for this scenario.
