### ISSUE TITLE
ID Prime 940 cards detected as MD 840

### ISSUE THREAD

**Issue by AEtherC0r3** [PeculiarVentures/fortify#523]
The ATR of ID Prime 940 cards is 3B7F96000080318065B0855956FB120FFE829000 but the "name" in [cards.json](https://github.com/PeculiarVentures/webcrypto-local/blob/ba805429b7d5f9641cbf130945f9d54a4d11f6ec/packages/cards/lib/card.json#L347-L349) for this ATR is MD 840

**Comment by microshine** [comment]
`card.json` has been updated. Please restart your Fortify application to get the latest version of `card.json`. The latest version is v1.1.10.
