### ISSUE TITLE
Published component 'fortify-web-components@3.1.0' not well transformed

### ISSUE THREAD

**Issue by therubiksman** [PeculiarVentures/fortify#528]
Hi,

My builder based on webpack cant't finalize due to fortify-web-components@3.1.0.

I've found that in dist cjs file "certification_request-22b576d6.js", there are many semicolon ";" next to each other, which breaks the Terser plugin of Webpack.

You can see :
![image](https://user-images.githubusercontent.com/109626024/207905663-776c9331-73cd-4dba-904b-2f4be8c647c8.png)

In many other dist files, these semi colon are not present.

**Comment by donskov** [comment]
Hello @therubiksman. 

Thank you for your request. Try the updated version `3.1.1`. I hope that there will be no problems with it.

**Comment by therubiksman** [comment]
Thank you very much !
I confirm it works with version 3.1.1.
