### ISSUE TITLE
Git repository for "fortify-webcomponents"

### ISSUE THREAD

**Issue by therubiksman** [PeculiarVentures/fortify#531]
Hi,

Just a question, why the git repository "https://github.com/PeculiarVentures/fortify-webcomponents.git" declared in the package.json is not accessible ?

Only the git repository for "pv-certificate-viewer" is reachable.

Thank you.

**Comment by donskov** [comment]
Hi @therubiksman,

Yes, unfortunately, we can't make it public yet. We have plans for the development and use of this component. If you need additional changes or the addition of new functionality, please write to info@peculiarventures.com.

Best regards.
