### ISSUE TITLE
Unable to install on macOS Ventura 13.1 (22C65)

### ISSUE THREAD

**Issue by tommed** [PeculiarVentures/fortify#535]
![image](https://user-images.githubusercontent.com/13066/218985016-e3942cdd-9e50-4d3d-9de0-47a5d737d460.png)

**Comment by tommed** [comment]
Anyone?

**Comment by donskov** [comment]
Hello @tommed. Unfortunately, Fortify isn't a registered app by Apple yet. You can use [this](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac) instruction to install the app.
