### ISSUE TITLE
New Safenet Tokens are Read Only in Fortify

### ISSUE THREAD

**Issue by PeterGS123** [PeculiarVentures/fortify#541]
Thales has recently started shipping Safenet 5110 (940 B) tokens to address a shortage of supply in the chips they normally use. Notice the "B" at the end of the model. These tokens work with the latest set of drivers and software: Safenet Authentication Client 10.8 R8. The problem is that Fortify registers this as a read only device with the title of "Scard Windows API."

I have a copy of the latest software from Thales if you need it. This is what I see in fortify when I try to view the token:
![image](https://user-images.githubusercontent.com/127818051/225004173-33f9b53f-288e-436b-b57c-24cdb975aba2.png)

Fortify is able to read the token and display the certificates that are installed on there. Fortify does not ask for the token password.  Here are some of the logs that I copied from fortify:

{"atr":"3bff9600008131fe4380318065b0855956fb12017882900088","level":"info","message":"cardReader/insert","reader":"SafeNet Token JC 0","source":"server-api","timestamp":"2023-03-13T20:13:40.542Z"}
{"atr":"3b8d0180fba000000397425446590401cf","level":"info","message":"cardReader/insert","reader":"Microsoft Virtual Smart Card 0","source":"server-api","timestamp":"2023-03-13T20:13:40.546Z"}
{"atr":"3b8d0180fba000000397425446590401cf","level":"info","message":"Card is not in card.json, but supported by opensc","reader":"Microsoft Virtual Smart Card 0","source":"card-watcher","timestamp":"2023-03-13T20:13:42.097Z"}
{"atr":"3b8d0180fba000000397425446590401cf","level":"info","message":"Token was added to the reader","name":"GIDS card (UserPIN)","reader":"Microsoft Virtual Smart Card 0","source":"provider","timestamp":"2023-03-13T20:13:43.202Z"}
{"level":"info","library":"C:\\Program Files\\Fortify\\opensc-pkcs11.dll","message":"Loading PKCS#11 library","source":"provider","timestamp":"2023-03-13T20:13:43.203Z"}
{"atr":"3bff9600008131fe4380318065b0855956fb12017882900088","level":"info","message":"Cannot get Card config. Use pvpkcs11 SmartCard slot","reader":{"_events":{},"_eventsCount":4,"connected":false,"name":"SafeNet Token JC 0","state":65826},"source":"card-watcher","timestamp":"2023-03-13T20:13:44.300Z"}
{"atr":"3bff9600008131fe4380318065b0855956fb12017882900088","level":"info","message":"Token was added to the reader","name":"SCard Windows API","reader":"SafeNet Token JC 0","source":"provider","timestamp":"2023-03-13T20:13:44.301Z"}
{"level":"info","library":"C:\\Program Files\\Fortify\\pvpkcs11.dll","message":"Loading PKCS#11 library","source":"provider","timestamp":"2023-03-13T20:13:44.301Z"}
{"level":"info","message":"Looking for slot","slots":1,"source":"provider","timestamp":"2023-03-13T20:13:45.017Z"}
{"level":"info","message":"Use default TemplateBuilder","source":"provider","timestamp":"2023-03-13T20:13:47.513Z"}
{"cryptokiVersion":{"major":2,"minor":20},"firmwareVersion":{"major":0,"minor":0},"level":"info","library":"C:\\Program Files\\Fortify\\opensc-pkcs11.dll","libraryVersion":{"major":0,"minor":20},"manufacturerId":"OpenSC Project","message":"PKCS#11 library information","source":"provider","timestamp":"2023-03-13T20:13:47.516Z"}
{"id":"ad69036e042dc347b3177df6c1265953fd81a424fd879173552243cb9bda9908","level":"info","library":"C:\\Program Files\\Fortify\\opensc-pkcs11.dll","message":"Crypto provider was added to the list","name":"GIDS card (UserPIN)","reader":"Microsoft Virtual Smart Card 0","source":"provider","timestamp":"2023-03-13T20:13:47.517Z"}
{"added":1,"level":"info","message":"Amount of tokens was changed","removed":0,"source":"provider-service","timestamp":"2023-03-13T20:13:47.517Z"}
{"action":"crypto/certificateStorage/getItem","level":"info","message":"Run action","provider":"5f720fe330e297a3a3525a69bd450758728ba87c","session":"b7a6810e649558fb1a2289dc7645b27a5deee0e463e032966183a761afb863d9","source":"server","timestamp":"2023-03-13T20:13:47.524Z"}
{"crypto":"Windows CryptoAPI","index":"x509-d0db196f-808bd30a74af2e9e947dd8ce748195bf5f1a208d","level":"info","message":"certStorage/getItem","source":"server-api","timestamp":"2023-03-13T20:13:47.525Z"}
{"cert":{"publicKey":{"algorithm":{"hash":"SHA-256","name":"RSASSA-PKCS1-v1_5","sensitive":false,"token":true},"extractable":true,"id":"808bd30a74af2e9e947dd8ce748195bf5f1a208d","type":"public","usages":["encrypt","verify","wrapKey"]},"subjectName":"C=US, O=Organization name removed - GlobalSign ePKIAdmin certificate, OU=Email control validated by GlobalSign - authenticated by LRA, CN=PAR12694_PeterD, E=peter.desfosses@globalsign.com","token":true,"type":"x509"},"crypto":"Windows CryptoAPI","level":"info","message":"certStorage/getItem","source":"server-api","timestamp":"2023-03-13T20:13:47.556Z"}
{"level":"info","message":"Looking for slot","slots":3,"source":"provider","timestamp":"2023-03-13T20:13:47.582Z"}
{"level":"info","message":"Use default TemplateBuilder","source":"provider","timestamp":"2023-03-13T20:13:48.553Z"}
{"cryptokiVersion":{"major":2,"minor":30},"firmwareVersion":{"major":0,"minor":1},"level":"info","library":"C:\\Program Files\\Fortify\\pvpkcs11.dll","libraryVersion":{"major":1,"minor":1},"manufacturerId":"Module","message":"PKCS#11 library information","source":"provider","timestamp":"2023-03-13T20:13:48.554Z"}
{"id":"b565f1b3ccab8c8624a2724682e78e4d38f5fdb4663b2525139078b3d9c1fff2","level":"info","library":"C:\\Program Files\\Fortify\\pvpkcs11.dll","message":"Crypto provider was added to the list","name":"SCard Windows API","reader":"SafeNet Token JC 0","source":"provider","timestamp":"2023-03-13T20:13:48.556Z"}
{"added":1,"level":"info","message":"Amount of tokens was changed","removed":0,"source":"provider-service","timestamp":"2023-03-13T20:13:48.557Z"}
{"action":"provider/action/getCrypto","level":"info","message":"Run action","session":"b7a6810e649558fb1a2289dc7645b27a5deee0e463e032966183a761afb863d9","source":"server","timestamp":"2023-03-13T20:13:48.563Z"}
{"action":"crypto/certificateStorage/getItem","level":"info","message":"Run action","provider":"5f720fe330e297a3a3525a69bd450758728ba87c","session":"b7a6810e649558fb1a2289dc7645b27a5deee0e463e032966183a761afb863d9","source":"server","timestamp":"2023-03-13T20:13:48.575Z"}
{"crypto":"Windows CryptoAPI","index":"x509-80dc196f-c6648103c11e31e9d93e8a9092dae2035cfbfc49","level":"info","message":"certStorage/getItem","source":"server-api","timestamp":"2023-03-13T20:13:48.576Z"}
{"cert":{"publicKey":{"algorithm":{"hash":"SHA-256","name":"RSASSA-PKCS1-v1_5","sensitive":false,"token":true},"extractable":true,"id":"c6648103c11e31e9d93e8a9092dae2035cfbfc49","type":"public","usages":["encrypt","verify","wrapKey"]},"subjectName":"DC=com, DC=globalsign, DC=internal, OU=GS-FE, OU=AMER, OU=US, OU=PSM, OU=users, OU=standard, CN=Farhood Nigjeh","token":true,"type":"x509"},"crypto":"Windows CryptoAPI","level":"info","message":"certStorage/getItem","source":"server-api","timestamp":"2023-03-13T20:13:48.609Z"}
{"action":"provider/action/getCrypto","level":"info","message":"Run action","session":"b7a6810e649558fb1a2289dc7645b27a5deee0e463e032966183a761afb863d9","source":"server","timestamp":"2023-03-13T20:13:48.713Z"}
{"action":"crypto/isLoggedIn","level":"info","message":"Run action","provider":"ad69036e042dc347b3177df6c1265953fd81a424fd879173552243cb9bda9908","session":"b7a6810e649558fb1a2289dc7645b27a5deee0e463e032966183a761afb863d9","source":"server","timestamp":"2023-03-13T20:13:48.721Z"}
{"crypto":"GIDS card (UserPIN)","level":"info","message":"crypto/isLoggedIn","source":"server-api","timestamp":"2023-03-13T20:13:48.723Z"}
{"action":"crypto/certificateStorage/getItem","level":"info","message":"Run action","provider":"5f720fe330e297a3a3525a69bd450758728ba87c","session":"b7a6810e649558fb1a2289dc7645b27a5deee0e463e032966183a761afb863d9","source":"server","timestamp":"2023-03-13T20:13:48.727Z"}
{"crypto":"Windows CryptoAPI","index":"x509-30d2196f-34ae7182af224f9ebaec17f330fdcd3b77195034","level":"info","message":"certStorage/getItem","source":"server-api","timestamp":"2023-03-13T20:13:48.728Z"}
{"cert":{"publicKey":{"algorithm":{"hash":"SHA-256","name":"RSASSA-PKCS1-v1_5","sensitive":false,"token":true},"extractable":true,"id":"34ae7182af224f9ebaec17f330fdcd3b77195034","type":"public","usages":["encrypt","verify","wrapKey"]},"subjectName":"C=US, O=Organization name removed - GlobalSign ePKIAdmin certificate, OU=Email control validated by GlobalSign - authenticated by LRA, CN=PAR108999_CertAdmin, E=peter.desfosses@globalsign.com","token":true,"type":"x509"},"crypto":"Windows CryptoAPI","level":"info","message":"certStorage/getItem","source":"server-api","timestamp":"2023-03-13T20:13:48.773Z"}
{"action":"crypto/isLoggedIn","level":"info","message":"Run action","provider":"b565f1b3ccab8c8624a2724682e78e4d38f5fdb4663b2525139078b3d9c1fff2","session":"b7a6810e649558fb1a2289dc7645b27a5deee0e463e032966183a761afb863d9","source":"server","timestamp":"2023-03-13T20:13:48.814Z"}
{"crypto":"SCard Windows API","level":"info","message":"crypto/isLoggedIn","source":"server-api","timestamp":"2023-03-13T20:13:48.814Z"}
{"action":"crypto/certificateStorage/getItem","level":"info","message":"Run action","provider":"5f720fe330e297a3a3525a69bd450758728ba87c","session":"b7a6810e649558fb1a2289dc7645b27a5deee0e463e032966183a761afb863d9","source":"server","timestamp":"2023-03-13T20:13:48.818Z"}
{"crypto":"Windows CryptoAPI","index":"x509-30dd196f-e2f740e9c1a1319ebced9bf4f8a5c3ac43885930","level":"info","message":"certStorage/getItem","source":"server-api","timestamp":"2023-03-13T20:13:48.819Z"}
{"cert":{"publicKey":{"algorithm":{"hash":"SHA-256","name":"RSASSA-PKCS1-v1_5","sensitive":false,"token":true},"extractable":true,"id":"e2f740e9c1a1319ebced9bf4f8a5c3ac43885930","type":"public","usages":["encrypt","verify","wrapKey"]},"subjectName":"C=US, ST=New Hampshire, L=Portsmouth, O=GlobalSign\\, Inc., OU=IT Systems Administrator, CN=Peter Desfosses, E=peter.desfosses@globalsign.com","token":true,"type":"x509"},"crypto":"Windows CryptoAPI","level":"info","message":"certStorage/getItem","source":"server-api","timestamp":"2023-03-13T20:13:48.851Z"}
{"action":"crypto/certificateStorage/getItem","level":"info","message":"Run action","provider":"5f720fe330e297a3a3525a69bd450758728ba87c","session":"b7a6810e649558fb1a2289dc7645b27a5deee0e463e032966183a761afb863d9","source":"server","timestamp":"2023-03-13T20:13:48.870Z"}
{"crypto":"Windows CryptoAPI","index":"x509-40c02273-95cc1758608e33d776bc190f7ce7335cfdb065d8","level":"info","message":"certStorage/getItem","source":"server-api","timestamp":"2023-03-13T20:13:48.871Z"}
{"cert":{"publicKey":{"algorithm":{"hash":"SHA-256","name":"RSASSA-PKCS1-v1_5","sensitive":false,"token":true},"extractable":true,"id":"95cc1758608e33d776bc190f7ce7335cfdb065d8","type":"public","usages":["encrypt","verify","wrapKey"]},"subjectName":"C=US, O=Organization name removed - GlobalSign ePKIAdmin certificate, OU=Email control validated by GlobalSign - authenticated by LRA, CN=PAR108999_CertAdmin, E=peter.desfosses@globalsign.com","token":true,"type":"x509"},"crypto":"Windows CryptoAPI","level":"info","message":"certStorage/getItem","source":"server-api","timestamp":"2023-03-13T20:13:48.899Z"}
{"action":"crypto/certificateStorage/getItem","level":"info","message":"Run action","provider":"5f720fe330e297a3a3525a69bd450758728ba87c","session":"b7a6810e649558fb1a2289dc7645b27a5deee0e463e032966183a761afb863d9","source":"server","timestamp":"2023-03-13T20:13:48.915Z"}
{"crypto":"Windows CryptoAPI","index":"x509-90b42273-84437c1858d73fccd899f3916b7446a2a5c8a272","level":"info","message":"certStorage/getItem","source":"server-api","timestamp":"2023-03-13T20:13:48.916Z"}
{"cert":{"publicKey":{"algorithm":{"hash":"SHA-256","name":"RSASSA-PKCS1-v1_5","sensitive":false,"token":true},"extractable":true,"id":"84437c1858d73fccd899f3916b7446a2a5c8a272","type":"public","usages":["encrypt","verify","wrapKey"]},"subjectName":"C=BE, O=GlobalSign nv-sa, CN=Peter Desfosses","token":true,"type":"x509"},"crypto":"Windows CryptoAPI","level":"info","message":"certStorage/getItem","source":"server-api","timestamp":"2023-03-13T20:13:48.943Z"}
{"action":"crypto/certificateStorage/getItem","level":"info","message":"Run action","provider":"5f720fe330e297a3a3525a69bd450758728ba87c","session":"b7a6810e649558fb1a2289dc7645b27a5deee0e463e032966183a761afb863d9","source":"server","timestamp":"2023-03-13T20:13:48.961Z"}
{"crypto":"Windows CryptoAPI","index":"x509-f0c02273-318ee64011f113b03cc5a4a0b88651656e2e4b1b","level":"info","message":"certStorage/getItem","source":"server-api","timestamp":"2023-03-13T20:13:48.962Z"}
{"cert":{"publicKey":{"algorithm":{"hash":"SHA-256","name":"RSASSA-PKCS1-v1_5","sensitive":false,"token":true},"extractable":true,"id":"318ee64011f113b03cc5a4a0b88651656e2e4b1b","type":"public","usages":["encrypt","verify","wrapKey"]},"subjectName":"C=US, O=Organization name removed - GlobalSign ePKIAdmin certificate, OU=Email control validated by GlobalSign - authenticated by LRA, CN=PAR108999_CertAdmin, E=peter.desfosses@globalsign.com","token":true,"type":"x509"},"crypto":"Windows CryptoAPI","level":"info","message":"certStorage/getItem","source":"server-api","timestamp":"2023-03-13T20:13:48.990Z"}
{"action":"crypto/certificateStorage/getItem","level":"info","message":"Run action","provider":"5f720fe330e297a3a3525a69bd450758728ba87c","session":"b7a6810e649558fb1a2289dc7645b27a5deee0e463e032966183a761afb863d9","source":"server","timestamp":"2023-03-13T20:13:49.009Z"}
{"crypto":"Windows CryptoAPI","index":"x509-20b12273-41e875a7fc1406cf605940d7440a517531e7ed5f","level":"info","message":"certStorage/getItem","source":"server-api","timestamp":"2023-03-13T20:13:49.010Z"}
{"cert":{"publicKey":{"algorithm":{"hash":"SHA-256","name":"RSASSA-PKCS1-v1_5","sensitive":false,"token":true},"extractable":true,"id":"41e875a7fc1406cf605940d7440a517531e7ed5f","type":"public","usages":["encrypt","verify","wrapKey"]},"subjectName":"DC=com, DC=globalsign, DC=internal, OU=GS-BE, OU=AMER, OU=US, OU=PSM, OU=users, OU=admin, CN=Farhood Nigjeh","token":true,"type":"x509"},"crypto":"Windows CryptoAPI","level":"info","message":"certStorage/getItem","source":"server-api","timestamp":"2023-03-13T20:13:49.039Z"}
{"action":"crypto/certificateStorage/getItem","level":"info","message":"Run action","provider":"5f720fe330e297a3a3525a69bd450758728ba87c","session":"b7a6810e649558fb1a2289dc7645b27a5deee0e463e032966183a761afb863d9","source":"server","timestamp":"2023-03-13T20:13:49.056Z"}
{"crypto":"Windows CryptoAPI","index":"x509-80bd2273-f51283cf008b30f123a5e68b79e0b47f275efeba","level":"info","message":"certStorage/getItem","source":"server-api","timestamp":"2023-03-13T20:13:49.057Z"}
{"cert":{"publicKey":{"algorithm":{"hash":"SHA-256","name":"RSASSA-PKCS1-v1_5","sensitive":false,"token":true},"extractable":true,"id":"f51283cf008b30f123a5e68b79e0b47f275efeba","type":"public","usages":["encrypt","verify","wrapKey"]},"subjectName":"C=BE, ST=Vlaams-Brabant, L=Leuven, O=GlobalSign nv-sa, CN=Peter Desfosses","token":true,"type":"x509"},"crypto":"Windows CryptoAPI","level":"info","message":"certStorage/getItem","source":"server-api","timestamp":"2023-03-13T20:13:49.084Z"}
{"action":"crypto/certificateStorage/getItem","level":"info","message":"Run action","provider":"5f720fe330e297a3a3525a69bd450758728ba87c","session":"b7a6810e649558fb1a2289dc7645b27a5deee0e463e032966183a761afb863d9","source":"server","timestamp":"2023-03-13T20:13:49.101Z"}
{"crypto":"Windows CryptoAPI","index":"x509-20bc2273-42a62eaaf9083f377309861ec2aebbf144fbbc79","level":"info","message":"certStorage/getItem","source":"server-api","timestamp":"2023-03-13T20:13:49.102Z"}
{"cert":{"publicKey":{"algorithm":{"hash":"SHA-256","name":"RSASSA-PKCS1-v1_5","sensitive":false,"token":true},"extractable":true,"id":"42a62eaaf9083f377309861ec2aebbf144fbbc79","type":"public","usages":["encrypt","verify","wrapKey"]},"subjectName":"DC=com, DC=globalsign, DC=internal, OU=GS-BE, OU=AMER, OU=US, OU=PSM, OU=users, OU=admin, CN=Jack Murray (Admin)","token":true,"type":"x509"},"crypto":"Windows CryptoAPI","level":"info","message":"certStorage/getItem","source":"server-api","timestamp":"2023-03-13T20:13:49.131Z"}
{"action":"crypto/certificateStorage/getItem","level":"info","message":"Run action","provider":"5f720fe330e297a3a3525a69bd450758728ba87c","session":"b7a6810e649558fb1a2289dc7645b27a5deee0e463e032966183a761afb863d9","source":"server","timestamp":"2023-03-13T20:13:49.146Z"}
{"crypto":"Windows CryptoAPI","index":"x509-50c22273-9d408fced171d2ca6724bf8423c677bf0054be45","level":"info","message":"certStorage/getItem","source":"server-api","timestamp":"2023-03-13T20:13:49.147Z"}
{"cert":{"publicKey":{"algorithm":{"hash":"SHA-256","name":"RSASSA-PKCS1-v1_5","sensitive":false,"token":true},"extractable":true,"id":"9d408fced171d2ca6724bf8423c677bf0054be45","type":"public","usages":["encrypt","verify","wrapKey"]},"subjectName":"C=IN, ST=Delhi, L=Delhi, OU=GMOA, O=GlobalSign Certificate Services Private Limited, E=prince.kumar@globalsign.com, CN=Prince Kumar (GM Operator)","token":true,"type":"x509"},"crypto":"Windows CryptoAPI","level":"info","message":"certStorage/getItem","source":"server-api","timestamp":"2023-03-13T20:13:49.172Z"}
{"action":"crypto/certificateStorage/getItem","level":"info","message":"Run action","provider":"5f720fe330e297a3a3525a69bd450758728ba87c","session":"b7a6810e649558fb1a2289dc7645b27a5deee0e463e032966183a761afb863d9","source":"server","timestamp":"2023-03-13T20:13:49.185Z"}
{"crypto":"Windows CryptoAPI","index":"x509-80b22273-4b406693da55efb84a3431f0c660f782b96cd8d8","level":"info","message":"certStorage/getItem","source":"server-api","timestamp":"2023-03-13T20:13:49.186Z"}
{"cert":{"publicKey":{"algorithm":{"hash":"SHA-256","name":"RSASSA-PKCS1-v1_5","sensitive":false,"token":true},"extractable":true,"id":"4b406693da55efb84a3431f0c660f782b96cd8d8","type":"public","usages":["encrypt","verify","wrapKey"]},"subjectName":"C=US, O=Organization name removed - GlobalSign ePKIAdmin certificate, OU=Email control validated by GlobalSign - authenticated by LRA, CN=PAR108999_CertAdmin, E=peter.desfosses@globalsign.com","token":true,"type":"x509"},"crypto":"Windows CryptoAPI","level":"info","message":"certStorage/getItem","source":"server-api","timestamp":"2023-03-13T20:13:49.214Z"}
{"action":"crypto/certificateStorage/getItem","level":"info","message":"Run action","provider":"5f720fe330e297a3a3525a69bd450758728ba87c","session":"b7a6810e649558fb1a2289dc7645b27a5deee0e463e032966183a761afb863d9","source":"server","timestamp":"2023-03-13T20:13:49.262Z"}
{"crypto":"Windows CryptoAPI","index":"x509-10ba2273-3001a0a28f9aea8feda7bc505d273fb46e812d58","level":"info","message":"certStorage/getItem","source":"server-api","timestamp":"2023-03-13T20:13:49.262Z"}
{"cert":{"publicKey":{"algorithm":{"hash":"SHA-256","name":"RSASSA-PKCS1-v1_5","sensitive":false,"token":true},"extractable":true,"id":"3001a0a28f9aea8feda7bc505d273fb46e812d58","type":"public","usages":["encrypt","verify","wrapKey"]},"subjectName":"C=BE, ST=Vlaams-Brabant, L=Leuven, O=GlobalSign nv-sa, CN=Rocio Buroz","token":true,"type":"x509"},"crypto":"Windows CryptoAPI","level":"info","message":"certStorage/getItem","source":"server-api","timestamp":"2023-03-13T20:13:49.295Z"}
{"action":"crypto/certificateStorage/getItem","level":"info","message":"Run action","provider":"5f720fe330e297a3a3525a69bd450758728ba87c","session":"b7a6810e649558fb1a2289dc7645b27a5deee0e463e032966183a761afb863d9","source":"server","timestamp":"2023-03-13T20:13:49.308Z"}
{"crypto":"Windows CryptoAPI","index":"x509-f0cb2273-704a18ba92c2766d0e822fda453ef90a9f3f57ff","level":"info","message":"certStorage/getItem","source":"server-api","timestamp":"2023-03-13T20:13:49.309Z"}

**Comment by microshine** [comment]
It looks like the ATR is not recognized by Fortify. Therefore, the application is using the SCard API to interact with the token. We can register this token in our application using the ATR from the log. However, before publishing these changes, it would be good to test this with a real token. Please update the card.json file on your computer (~/.fortify/card.json or /User/<Name>/.fortify/card.json) by adding the following object to the list of cards:

```json
{
  "atr": "3bff9600008131fe4380318065b0855956fb12017882900088",
  "name": "SafeNet 5110 (940 B)",
  "driver": "39b3d7a3662c4b48bb120d008dd18648"
},
```

After modifying the file, you will need to restart the application. After that, the program will start using the SafeNet library for this token.

**Comment by PeterGS123** [comment]
I have updated my card.json file. After restarting the app, fortify is able to read and write to the token. I was able to create a new private key and request file on the token. I tried to install a certificate using my company's website but it is still telling me to plug in a token. 
It looks like everything is working but perhaps the app needs to be updated before it will work with our web app. Please let me know if you need me to test anything else.

**Comment by microshine** [comment]
We have added the ATR to our card.json and have published an update. Fortify automatically checks the file https://fortifyapp.com/packages/card.jws and updates the local card.json, which does not require a complete reinstallation of the Fortify application.

**Comment by PeterGS123** [comment]
Thank you for the fast resolution of this!
