### ISSUE TITLE
Unable to Install Node modules 

### ISSUE THREAD

**Issue by sanawershoukat** [PeculiarVentures/fortify#544]
Hi,

I have cloned the master repository of Fortify and when I execute the command `npm install`  it fails with the error, screenshot is attached for reference. 

My current node version is v15.14.0 and I even tried with the latest node version but still failed on the same step.

Looking forward to the solution. Thanks in advance.

<img width="1148" alt="Screenshot 2023-05-08 at 7 30 45 PM" src="https://user-images.githubusercontent.com/15729583/236852701-e642d083-ad4a-4e5f-b5b0-fb94ce8e57dc.png">

**Comment by sanawershoukat** [comment]
Step is missing to compile the Fortify app using the latest version of node, so I figure out that step and was successfully able to compile and run the Fortify app. 

You can update the Readme.md to add `yarn` command before compiling the Fortify app.

**Comment by donskov** [comment]
Thank you @sanawershoukat. Updated README.
