### ISSUE TITLE
Add support for '3b9f958131fe9f006646530510323871df000000000019' token

### ISSUE THREAD

**Issue by adnanelgalla** [PeculiarVentures/fortify#549]
Reader name: FT ePass2003Auto 00 00
ATR: 3b9f958131fe9f006646530510323871df000000000019

```js
{
   "cards": [{
   	"atr": "3b9f958131fe9f006646530510323871df000000000019",
   	"name": "FT ePass2003Auto",
   	"driver": "ECA050606FD48FAB340EA9F1FCB582A1E0F1B740"
   }]
}
```

[Smart card ATR parsing 3b9f958131fe9f006646530510323871df000000000019](https://smartcard-atr.apdu.fr/parse?ATR=3b9f958131fe9f006646530510323871df000000000019)

Tested by adding snippet above to `cards.json` and can confirm it works

**Comment by microshine** [comment]
I've published the new version of `card.json@1.1.13` please restart your Fortify application to get the latest version. It includes ATR `3b9f958131fe9f006646530510323871df000000000019`

**Comment by adnanelgalla** [comment]
Tested it and it works, thank you.
