### ISSUE TITLE
Feitian ePass 2003 Token not Read by Fortify

### ISSUE THREAD

**Issue by PeterGS123** [PeculiarVentures/fortify#563]
I have a Fetian ePass 2003 token which is plugged into my windows 11 laptop. Using the ePass 2003 software from Feitian I am able to manage the token to see the certificates installed on it. Fortify does not seem to be able to read the token contents. I have the latest version of fortify installed.

When looking at Fortify tools I am able to see the virtual smart cards and the safenet 5110 token however this Feitian token does not show. I see an entry for "SCard windows API" which might be the feitian token. The last time this happened there was an identifier for the token which had to be whitelisted.

I have attached my fortify logs for your review.

[fortify.log](https://github.com/PeculiarVentures/fortify/files/12861403/fortify.log)

**Comment by microshine** [comment]
From what I can see in the log file, there seems to be difficulty reading the card.json configuration file.

```
{"atr":"3bff9600008131fe4380318065b0855956fb12017882900088","level":"info","message":"Cannot get Card config. Use pvpkcs11 SmartCard slot","reader":{"_events":{},"_eventsCount":4,"connected":false,"name":"SafeNet Token JC 0","state":65826},"source":"card-watcher","timestamp":"2023-03-13T20:13:44.300Z"}
{"atr":"3bd518ff8191fe1fc38073c821100a","level":"info","message":"Cannot get Card config. Use pvpkcs11 SmartCard slot","reader":{"_events":{},"_eventsCount":4,"connected":false,"name":"Feitian SCR301 0","state":65826},"source":"card-watcher","timestamp":"2023-10-10T18:40:13.114Z"}
{"atr":"3b8d0180fba000000397425446590401cf","level":"info","message":"Cannot get Card config. Use pvpkcs11 SmartCard slot","reader":{"_events":{},"_eventsCount":4,"connected":false,"name":"Microsoft Virtual Smart Card 2","state":65826},"source":"card-watcher","timestamp":"2023-10-10T18:40:33.378Z"}
```

Following this, the application attempts to fetch data using built-in libraries, either opnesc or pvpkcs11.

Please ensure that the `card.json` file is present in the `~/.fortify` directory and has been corrected. You can download the original file here: https://raw.githubusercontent.com/PeculiarVentures/webcrypto-local/master/packages/cards/lib/card.json. After updating the file, you'll need to restart the Fortify application.

I noticed that only 4 tokens are being used. Their ATRs are: `3b1696417374726964`, `3bff9600008131fe4380318065b0855956fb12017882900088`, `3bd518ff8191fe1fc38073c821100a`, and `3b8d0180fba000000397425446590401cf`. Only the first two are supported by Fortify and are added to `card.json`.

**Comment by PeterGS123** [comment]
I have uninstalled fortify and reinstalled it. Everything appears to be working now. The software is able to read the json file. Thank you for your help.
