### ISSUE TITLE
Support Nix package manager and NixOS please

### ISSUE THREAD

**Issue by damccull** [PeculiarVentures/fortify#579]
I would like to see this app supporting the nix package manager and NixOS. Thanks.

**Comment by rmhrisk** [comment]
@damccull I'm a Nix fan, but with our limited resources, I'm unsure how soon we can get to it. Where I've used Nix, it's been in server environments; the immutability is a great property.

Could you talk a bit about the use case on endpoints? Or are you maybe using this as part of some server administrative user stories?

**Comment by damccull** [comment]
Well, I understand the limited time and resources so maybe it's not a great project for now and I'll get over it.

I run nix on my desktop, am building a website prototype that needs to be able to digitally sign documents, and wanted to be able to install fortify to try it out. I will try it in an Ubuntu VM for now.

If my website works and I can supply smart cards cheaply enough I want to use it for customers to sign their documents and contracts and such. Originally I was going to to try sign with fido2 but that's not possible it seems. So back to pki!

There's probably not enough need out there for nix specifically, yet. I tried building it myself in a nix package but yarn is a bit of a pain on nix apparently. I'll just keep trying until I get it and I'll send my results your way to see if you want to include it.

**Comment by rmhrisk** [comment]
Makes sense.

Checkout Hancock.ink for an example of a document signing application we’ve made that uses Fortify.

A single desktop won’t be enough for us to justify the package maintenance but I’d love for us to support nix eventually.
