### ISSUE TITLE
Add token.name or reader name to the pin entry prompt

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/fortify#67]
We should include the name of the token or label in the pin dialog so users know which pin to use

![image](https://user-images.githubusercontent.com/1619279/31034678-f0ff559e-a519-11e7-8f10-a5eeb9daa851.png)

We can do this like this:

```
To provide access you will need to provide the PIN or password protecting <device>.
```

**Comment by donskov** [comment]
Added to the window title

![image](https://user-images.githubusercontent.com/9417251/98816090-d675b300-2430-11eb-8596-b1fb1e14fef2.png)
