### ISSUE TITLE
If a card is inserted and the middleware was installed display a message

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/fortify#70]
If someone inserts a card where we have the metadata but the libraries do not exist we should probably pop an allert.

```
The inserted smart card is supported by Fortify but we were unable to find middleware for the card. Make sure it is installed and try again.
```

**Comment by donskov** [comment]
Added

![image](https://user-images.githubusercontent.com/9417251/98816676-b1357480-2431-11eb-8caf-874157e0b0b9.png)
