### ISSUE TITLE
Show dialog on SCardEstablishContext error

### ISSUE THREAD

**Issue by microshine** [PeculiarVentures/fortify#81]
Error from npm module pcsclite
> Error: SCardEstablishContext error: The Smart card resource manager is not running. (0x8010001d)

We should add dialog on this error

“It looks like the Windows Smart Card Resource Manager is not running. Use the Services snap-in to start the service.

[ ] Don’t show me this again”

**Comment by riyupatel** [comment]
@microshine i got same issue in pcsclite , you found any solution for this?

**Comment by microshine** [comment]
@riyupatel Try to run Smart Card services

![image](https://user-images.githubusercontent.com/7333669/91966774-fabf6000-ed1a-11ea-81b2-6faca65d1043.png)

**Comment by riyupatel** [comment]
thank you @microshine , yes i did this but it's not working , i got this error

"C:\node_pro\node_modules\pcsclite\lib\pcsclite.js:39
var p = new PCSCLite(); ^ Error: SCardEstablishContext error: The Smart Card Resource Manager is not running. (0x8010001d)"

card reader : verifone vx 520 (connected via USB Serial Device(COM3)) 
system : windows 10

**Comment by donskov** [comment]
Window added

![image](https://user-images.githubusercontent.com/9417251/98816898-007ba500-2432-11eb-93d3-876cb82866b9.png)

**Comment by syariffortask** [comment]
I using windows,and get sampe problem,anybody please help how to solve?
I have already start services scard,but did not work
