### ISSUE TITLE
Auto release and updating landing

### ISSUE THREAD

**Issue by apilguk** [PeculiarVentures/fortify#87]
We need an automation way to releasing fortify app and updating download links on a landing page.

Steps to make it possible:
- building script - should build files for different platforms
- script which releases files [here](https://github.com/PeculiarVentures/fortify-web/releases)
- script which updates links and deploy landing to gh-pages, it should automatically check last version of app

Should we use CI for this work?

**Comment by donskov** [comment]
fixed
