### ISSUE TITLE
Need to improve driver not found error

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/fortify#88]
Currently we show:

![image](https://user-images.githubusercontent.com/1619279/33510563-3c0eb654-d6c2-11e7-8f30-ac6857935b68.png)

```
The good news is we support your smart card. The bad news is we were unable to find the middleware for your smart card.

We were looking for: {P11 and path}

But we could not find it. Contact your smart card or security token issuer.
```

**Comment by donskov** [comment]
Added

![image](https://user-images.githubusercontent.com/9417251/100114304-f1591600-2e79-11eb-9aa0-f2236bdf8986.png)
