### ISSUE TITLE
YubiKey has poor session management and we need to handle it better

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/fortify#97]
Create a session in Fortify Tools to a Yubikey.

Remove the token.

Refresh, you will see:

![image](https://user-images.githubusercontent.com/1619279/33646193-56bb848e-da03-11e7-9c8c-4b29ae676a4b.png)

To get past this you need to restart Fortify. 

Issues:
1. There is no button so the user is trapped, OK button should be present.
2. Text is no good, maybe add something like:
```
Oh no. It looks like the token was removed and not re-inserted or maybe the middleware invalidated our session.  

Please insert the token or smart card and try again.
````
3. If you have an invalid session shouldn't we just try again creating a new one and not requiring the restart of fortify?

**Comment by donskov** [comment]
@rmhrisk Please check
